### PR TITLE
Add raster image source example

### PR DESCRIPTION
**Pull request by bhousel**
We have a video on a map example, but not an image on a map example.
So this example shows a raster image overlay on a dark vector basemap.
:umbrella: 

screenshot 2015-10-09 22 40 18

### CODE REVIEW

**Comment by jfirebaugh** [comment]
How about putting the labels on top of the raster?

**Comment by bhousel** [comment]
> How about putting the labels on top of the raster?

Yes that does look better!
screenshot 2015-10-12 10 23 04

**Comment by jfirebaugh** [comment]
:+1: 

Does this depend on `master` features or can it go straight to `mb-pages`?

**Comment by bhousel** [comment]
The example can go in now - the `raster-opacity` fix doesn't really affect the demo.

**Comment by jfirebaugh** [comment]
Cool, please go ahead and commit it to `mb-pages` then.

**Comment by bhousel** [comment]
Cool, just merged it to `mb-pages`

**Pull request closed without merging**
