### PR TITLE
Added an error when referencing a nonexistent vector source layer

### LINKED ISSUE #1636: Throw an exception if a user references an unknown source layer
I've seen a few GL support requests having to do with users not understanding source layers or not knowing the name of their source layer.

We could alleviate the situation by throwing a runtime exception if the specified `source-layer` could not be found on the specified `source`, maybe even providing a list of layers that *are* available on that source.

ref https://github.com/mapbox/mapbox-gl-js/issues/1631#issuecomment-149561809

cc @lyzidiamond

### PR DESCRIPTION
**Pull request by lucaswoj**
resolves #1636 

cc @mourner @jfirebaugh

### CODE REVIEW

**Comment by jfirebaugh** [comment]
How sure are we that `vector_layers` is complete everywhere it exists? If that's not the case, this could start triggering validation errors for things that were actually working.

**Comment by lucaswoj** [comment]
Just confirmed with the data team that `vector_layers` *is* complete everywhere it exists.

**Comment by lucaswoj** [comment]
@yhahn Thoughts?

**Comment by lucaswoj** [comment]
Ping @jfirebaugh @yhahn

**Comment by jfirebaugh** [comment]
:+1:

**Comment by yhahn** [comment]
y :+1:

**Pull request merged**
