### PR TITLE
Make example names more consistent

### PR DESCRIPTION
**Pull request by lucaswoj**
There doesn't seem to be an convention around the naming of examples: some are named after the API used, some are named after functionality they add; some are noun phrases, some are verb phrases.

This PR standardizes all example names as verb phrases focused on the functionality they add. 

screen shot 2015-12-14 at 12 55 39 pm

cc @jfirebaugh @lyzidiamond @danswick @mourner

### CODE REVIEW

**Comment by jfirebaugh** [comment]
:+1: 

Can you add this naming convention to https://github.com/mapbox/mapbox-gl-js/blob/master/docs/README.md#examples?

**Comment by danswick** [comment]
This looks great, @lucaswoj! Looks ready to go to me.

**Comment by lyzidiamond** [comment]
I love this, @lucaswoj. Let's make sure it gets added to a `README` or `CONTRIBUTING.md`.

**Comment by lucaswoj** [comment]
@jfirebaugh @lyzidiamond Good idea. Just added to `docs/README.md`.

**Pull request merged**
