### PR TITLE
fix compact attribution positioning

### LINKED ISSUE #7439: Compact attribution broken in top-left/top-right locations.
**mapbox-gl-js version**: 0.50.0

**browser**: Chrome

### Steps to Trigger Behavior
Create a new map with attribution set to false.
add a new attribution control with the compact setting set to true to either the 'top-left' or 'top-right' locations.

### Link to Demonstration

The attribution control does not appear.

[https://jsfiddle.net/LiquidDivide/3o1nfmza/2/](https://jsfiddle.net/LiquidDivide/3o1nfmza/2/)

by adding some space to the top, you can see it is added to the map, however, it is above the map and not displayed. In addition, hovering/clicking the attribution icon causes the attribution to appear below the icon, and flicker since it is immediately blurred/hovered repeatedly.
[https://jsfiddle.net/LiquidDivide/3o1nfmza/5/](https://jsfiddle.net/LiquidDivide/3o1nfmza/5/)

### Expected Behavior

the icon appears on the map correctly and doesn't change position when hovered.

### Actual Behavior

the attribution appears above the map, out of view, and custom styling to move the attribution back into view reveals a blur/hover flicker loop.

### PR DESCRIPTION
**Pull request by mollymerp**
fix #7439 

image

image

image

note: the 10px margin that the `bottom-right` compact control has looks odd when applied to the other control locations, so I reduced it to 5px. I would be in favor of  making them all consistent at 5px – thoughts? 

## Launch Checklist

 - [x] briefly describe the changes in this PR
 - [x] manually test the debug page

### CODE REVIEW

**Comment by mollymerp** [comment]
🤦‍♀️sorry I meant I *would* be in favor of making them all consistently 5px (edited OP to fix) This is what it looks like: 
image

**Comment by ryanhamley** [comment]
I'm always in favor of symmetry. I think 5px is fine.

**Comment by mollymerp** [comment]
turns out 10px looks better with other controls, so I'm going with that for all positions.

**Comment by mollymerp** [comment]
I ended up switching back to 10px margin because it ends up looking better when using other controls on the map.

**Pull request merged**
