### PR TITLE
[wip] add showUserHeading option to GeolocateControl

### LINKED ISSUE #8034: Give Geolocation Control Marker Pitch Alignment Properties
Currently when the geolocation control marker is added to the map, the blue marker has no options to change color or set pitch such as "circle-pitch-alignment": "map". For aesthetic purposes, it may be useful for the marker to have more paint options that are exposed to a normal circle type layer.

Current:
Screen Shot 2019-03-13 at 11 21 56 PM

### LINKED ISSUE #8329: Add heading to GeolocateControl
## Motivation
Navigating yourself from a map with only position is difficult, showing a direction indicator or compass heading makes it much easier. Most modern mobile devices have a compass built in. Google Maps supports it.

## Design
  map.addControl(new mapboxgl.GeolocateControl({
        positionOptions: {
                  enableHighAccuracy: true
              },
        fitBoundsOptions: {
          maxZoom:7,
        },
        trackUserLocation: true
        trackUserHeading: true <----
  }), 'bottom-left');

### Mock-Up
Example from Google Maps, see the direction arrow pointing out of the blue dot.
xbZ8a

### PR DESCRIPTION
**Pull request by andrewharvey**
## Launch Checklist

 - [x] briefly describe the changes in this PR

Add a `showUserHeading` option to the GeolocateControl to show the device heading as an arrow next to the user location dot.

Sensor access is disabled by default in Safari from iOS 12.2+, so for this to work you need to enable that setting in Safari Settings, once enabled it uses `deviceOrientationEvent.webkitCompassHeading`.

closes #8329
closes #8034

 - [x] include before/after visuals or gifs if this PR includes visual changes

heading

 - [ ] write tests for all new functionality
 - [x] document any changes to public APIs
 - [ ] post benchmark scores
 - [ ] manually test the debug page
 - [ ] tagged `@mapbox/studio` and/or `@mapbox/maps-design` if this PR includes style spec or visual changes
 - [ ] tagged `@mapbox/gl-native` if this PR includes shader changes or needs a native port
- [ ] cross device testing
- [ ] investigate if it's better to use https://developer.mozilla.org/en-US/docs/Web/API/Coordinates/heading instead of `deviceorientation`.

### CODE REVIEW

**Comment by ahk** [comment]
Thanks for this PR. I'm curious if you have knowledge/experience/thoughts about how many users choose to enable sensor access in mobile Safari. Is this different from the permissions dialog that asks if location data should be enabled on a per-site basis?

**Comment by andrewharvey** [comment]
> Thanks for this PR. I'm curious if you have knowledge/experience/thoughts about how many users choose to enable sensor access in mobile Safari. Is this different from the permissions dialog that asks if location data should be enabled on a per-site basis?

No idea how many enable it, but probably very little have it enabled since it's off by default and most users would have no reason to enable it, that said an application could prompt you to go into settings and enable, and I think applications can still do that independently if they like. So I still think we should support it when it is enabled.

It's an all or nothing switch in Safari (in the app settings) it's different to the permissions dialog for location access.

I investigated the coords.heading field from the geolocation API https://developer.mozilla.org/en-US/docs/Web/API/Coordinates/heading and found that iOS Safari doesn't support it (tested on iOS 12.4.2). Chrome on Android does, but that already supports an absolute bearing from `deviceorientation`.

**Comment by ahk** [comment]
> I investigated the coords.heading field from the geolocation API
Do you think we should also support this field as well? I have FireFox and FireFox Preview on my Android phone. As well it's possible for desktop/laptop FireFox to have a compass reading in some weird cases right?

**Comment by ahankeosi** [comment]
Any movement on this?  Would really love this feature!

**Comment by andrewharvey** [comment]
> Any movement on this? Would really love this feature!

Nope, feel free to pick up my work in progress if you feel it's helpful.

**Comment by CptHolzschnauz** [comment]
Stick to one's guns ! Any movement to PR?

**Comment by andrewharvey** [comment]
this was completed by @tsuz in #10817

**Pull request closed without merging**
