### PR TITLE
Add a filter option for GeoJSON sources

### LINKED ISSUE #2613: Support preclustering filtering
Allow users to filter features before they are clustered. Some users may want this filtering to happen without transferring GeoJSON between the main thread and worker threads. 

We can filter these within the GL JS codebase before passing them to `supercluster`.

continued from https://github.com/mapbox/supercluster/issues/11

cc @mourner @lyzidiamond

### PR DESCRIPTION
**Pull request by mourner**
Introduces a `filter` option to GeoJSON sources that allows filtering out features prior to processing (e.g. before clustering) with an expression. Closes #2613.

## Launch Checklist

 - [x] briefly describe the changes in this PR
 - [x] write tests for all new functionality
 - [x] document any changes to public APIs
 - [x] manually test the debug page
 - [ ] tagged `@mapbox/map-design-team` `@mapbox/static-apis` if this PR includes style spec API or visual changes (not sure if that's relevant to these teams since it only targets GeoJSON)
 - [x] tagged @mapbox/gl-native (needs a native port)
 - [x] apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog'
 - [x] add an entry inside this element for inclusion in the `mapbox-gl-js` changelog: `<changelog>Add a filter option to GeoJSON sources.</changelog>`

### CODE REVIEW

**Comment by mourner** [comment]
@asheemmamoowala I've touched on this in my comment here https://github.com/mapbox/mapbox-gl-js/issues/2613#issuecomment-656252608. Basically we only need source-level filtering for clustering use cases, because we have to do it prior to clustering (which needs to run on all of the data), and other use cases such as geojson-vt are covered with layer-level filtering. We could add `setFilter` for convenience (and `Supercluster` already retains a reference to all the original points), but functionally it shouldn't be much different from removing the source and adding a new one with the same `id`.

**Comment by asheemmamoowala** [comment]
>  we only need source-level filtering for clustering use cases, because we have to do it prior to clustering

Should this be restricted to `clusterFilter` then so that there isn't confusion over which to use for non-clustered GeoJSON sources.

https://github.com/mapbox/mapbox-gl-js/issues/2613#issuecomment-656252608 suggests that:
> , and the file by the URL is already cached by the browser.

But this would only work when using a geoJSON by URL, not GeoJSON data, where an application might also be updating the feature dynamically

>  We could add `setFilter` for convenience (and Supercluster already retains a reference to all the original points), but functionally it shouldn't be much different from removing the source and adding a new one with the same id.

This can be added in the future if necessary.

**Comment by ryanhamley** [comment]
Reminder to @mourner that this PR just needs some tests

**Comment by enersis-pst** [comment]
like i understand there is no possibility to update the source filter, right? Only by removing and adding a new source is not a solution for me, because therefore i also need to remove all depening layers.

**Pull request merged**
