### PR TITLE
Update to Jekyll 3

### PR DESCRIPTION
**Pull request by tristen**
Capturing small changes here to update for [Jekyll 3](https://github.com/mapbox/publisher/issues/159)

### CODE REVIEW

**Comment by jfirebaugh** [comment]
This is backwards compatible with Jekyll 2 right? So we can merge it immediately?

**Comment by tristen** [comment]
I don't think so? I'm removing specifics about `rdiscount` and `pygments` as the highlighter in this commit.

**Comment by mourner** [comment]
@jfirebaugh not backwards compatible mostly because layout variables can only be accessed through `layout.var` and not `page.var` now. It requires careful update of layout code in many places.

**Comment by jfirebaugh** [comment]
@mourner There aren't any changes to layout code in this PR.

**Comment by tristen** [comment]
@jfirebaugh there are in `_layout/default.html` which this pr will require from www.mapbox.com

**Comment by jingsam** [comment]
Today in the morning my rss subscription was filled of posts of mapbox blog. It seems that you have switched to Jekyll 3 and rebuilt all of the posts. Cheers!

**Pull request merged**
