### PR TITLE
Fix rendering of tiles with extent != 4096

### LINKED ISSUE #1952: Tiles with non-standard extent are broken
I'm guessing the regression is a result of the layer-by-layer PR.

### PR DESCRIPTION
**Pull request by lucaswoj**
fixes #1952 

regression caused by #1886, as predicted

### CODE REVIEW

**Comment by lucaswoj** [comment]
I still see a number of instances of the :sparkles: constant `4096` scattered around the codebase but rendering seems to be correct in all cases I can identify.

:eyes: @ansis @mourner

**Comment by ansis** [comment]
It would be good to remove more of the remaining 4096's. It looks like some of them will cause clipping, drouble-drawing and pattern-sizing issues. the instances in:
- circle_bucket.js
- symbol_bucket.js
- draw_fill.js
- get_anchors.js

I think some of the others should be removable too

**Comment by mikemorris** [comment]
Would be great to get this ported to gl-native too, happy to lend a hand if you want to give it a shot @lucaswoj.

Refs https://github.com/mapbox/mapbox-gl-native/issues/250

**Comment by lucaswoj** [comment]
@mikemorris this feature was implemented by @tmcw in https://github.com/mapbox/mapbox-gl-js/pull/1234, I'm just fixing a regression caused by layer-by-layer.

**Comment by lucaswoj** [comment]
Good call @ansis. Fixing those exposed some bugs in test suite.

**Pull request merged**
