### PR TITLE
Fix the floating circles/heatmap artifact which occurs during globe/mercator transition

### PR DESCRIPTION
**Pull request by akoylasar**
This PR fixes the issues of "floating" circles during the transition from globe to mercator. Please also see this which address the same issue for the heatmap differently https://github.com/mapbox/mapbox-gl-js/issues/11476

Before:

https://user-images.githubusercontent.com/67509069/167471130-f1eaa8cb-828c-47c3-8934-33d653adb3c1.mp4

After:

https://user-images.githubusercontent.com/67509069/167471157-cba4bf1a-e6de-4edc-9023-c9345bffd0f8.mp4

## Launch Checklist

 - [x] briefly describe the changes in this PR
 - [x] include before/after visuals or gifs if this PR includes visual changes
 - [x] write tests for all new functionality
 - [x] apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog'

### CODE REVIEW

**Comment by SnailBones** [comment]
Any idea what's causing the sharp diagonal cutoffs as seen here?
Screenshot from 2022-05-03 10-54-58

**Comment by akoylasar** [comment]
> Any idea what's causing the sharp diagonal cutoffs as seen here? Screenshot from 2022-05-03 10-54-58

please see https://github.com/mapbox/mapbox-gl-js/pull/11851

**Comment by mpulkki-mapbox** [comment]
> > Any idea what's causing the sharp diagonal cutoffs as seen here? Screenshot from 2022-05-03 10-54-58
> 
> please see #11851

Seems like quads used for heatmap rendering are not properly aligned on the tangent plane. This can be seen on the other PR https://github.com/mapbox/mapbox-gl-js/pull/11851 as well. I'm not able to reproduce it using the `heatmap.html` debug page

**Comment by akoylasar** [comment]
> > > Any idea what's causing the sharp diagonal cutoffs as seen here? Screenshot from 2022-05-03 10-54-58
> > 
> > 
> > please see #11851
> 
> Seems like quads used for heatmap rendering are not properly aligned on the tangent plane. This can be seen on the other PR #11851 as well. I'm not able to reproduce it using the `heatmap.html` debug page

Here is the `index.html` I am using:

```
<!DOCTYPE html>
<html>
<head>
    <title>Mapbox GL JS debug page</title>
    <meta charset='utf-8'>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <link rel='stylesheet' href='../dist/mapbox-gl.css' />
    <style>
        body { margin: 0; padding: 0; }
        html, body, #map { height: 100%; }
    </style>
</head>

<body>
<div id='map'></div>

<script src='../dist/mapbox-gl-dev.js'></script>
<script src='../debug/access_token_generated.js'></script>
<script>

var map = window.map = new mapboxgl.Map({
    container: 'map',
    zoom: 3.5,
    center: [-122.4194, 37.7749],
    style: 'mapbox://styles/mapbox/streets-v11',
    // style: 'debug/test.json',
    hash: true,
    projection: 'globe'
});

map.on('load', () => {
    // Add a geojson point source.
    // Heatmap layers also work with a vector tile source.
    map.addSource('earthquakes', {
        'type': 'geojson',
        'data': 'https://docs.mapbox.com/mapbox-gl-js/assets/earthquakes.geojson'
    });

    map.addLayer(
        {
            'id': 'earthquakes-heat',
            'type': 'heatmap',
            'source': 'earthquakes',
            'maxzoom': 16,
            'paint': {
                'heatmap-radius': 50,
                'heatmap-opacity': 1
            }
        },
        'waterway-label'
    );


});

</script>
</body>
</html>

```

**Review by karimnaaji — APPROVED** [review]
LGTM % CI

**Comment by akoylasar** [comment]
added render test can capture future regressions as seen below: 
render-test-circle-near-transition

**Pull request merged**
