### PR TITLE
Remove support for building mapbox-gl with webpack and other non-browserify bundlers

### LINKED ISSUE #3230: Cannot find module 'sinon'
As of 0.24.0, `sinon` appears to be used outside of the testing environment:

https://github.com/mapbox/mapbox-gl-js/blob/07feb8d6e1f7be693bdeadf3d6c0300202122c0b/js/util/window.js#L5

This causes an issue with `npm install mapbox-gl`, because devDependencies are not installed with this command without explicitly using the `--dev` flag.

With webpack, this results in the following stack trace:

```js
Error: Cannot find module 'sinon'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/code/node_modules/mapbox-gl/js/util/window.js:5:13)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/code/node_modules/mapbox-gl/js/util/browser.js:8:14)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/code/node_modules/mapbox-gl/js/mapbox-gl.js:3:15)
```

### PR DESCRIPTION
**Pull request by mourner**
Closes #3230 #3229 #2458 and will prevent a ton of new issues like this in future.

This makes all the fragile webpack hacks unnecessary, gives us the possibility to confidently depend on Browserify (e.g. for things like #3034), and saves us a lot of time on future tricky bugs and support requests. There's also seem to be no benefit to building Mapbox GL with another bundler. We'll also be free to switch to any other bundle system in future when we see fit without legacy support concerns.

The only trouble this brings is that Webpack will throw a warning, which does not make sense in our particular case:

> WARNING in ./dist/mapbox-gl.js
> Critical dependencies:
> 1:481-488 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.

cc @jfirebaugh @lucaswoj @tmcw

### CODE REVIEW

**Comment by jfirebaugh** [comment]
👍 Given webpack's architectural choices, this seems like the only sane choice to me.

Should we remove `webpack.config.example.js` too?

**Comment by mourner** [comment]
Ah, forgot to commit removal of the webpack config. Done.

**Comment by holman** [comment]
This fixed a lot of the problems I've been running into recently; thanks a bunch! 💟

As a sidenote for others running into this, if you're not down with the `pre-build javascript file` warnings you can [suppress the errors](https://github.com/webpack/webpack/issues/1617#issuecomment-223676403) for mapbox-gl's distribution build in your webpack config:

```js
module: {
    noParse: /node_modules\/mapbox-gl\/dist\/mapbox-gl.js/,
    loaders: [{
    ...
    }]
}
```

**Comment by contra** [comment]
If you can't switch to dist (a module you use uses mapbox-gl, not you) you can still use the old way! Update webworkify-webpack once https://github.com/borisirota/webworkify-webpack/pull/21 is published and your existing stuff should work fine.


Alternatively, you can remove all of the old hacks and set up an alias which should work in most cases:

```js
resolve: {
  alias: {
    'mapbox-gl/js/mapbox-gl.js': 'mapbox-gl/dist/mapbox-gl.js'
  }
}
```

**Pull request merged**
