### PR TITLE
Add a debug page with per-bucket/property GPU memory statistics

### PR DESCRIPTION
**Pull request by mourner**
Adds `debug/bucket-stats.html` debug page that breaks down the size of the buffers uploaded to the GPU by layer names and their data-driven properties. This is helpful for debugging performance bottlenecks in styles, and coming up with ideas for memory footprint optimizations in GL JS.

image

## Launch Checklist

 - [x] briefly describe the changes in this PR
 - [x] include before/after visuals or gifs if this PR includes visual changes
 - [x] manually test the debug page
 - [x] tagged @mapbox/map-design-team — let's explore exposing this in a more convenient internal page or a Studio option for debugging style performance issues.
 - [x] apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog'

### CODE REVIEW

**Review by rreusser — APPROVED** [review]
This looks great. 👏 I learned a bit about how to navigate the data, but I'm of course taking a bit of it on faith that you know all the right places to tabulate the data that deserves to be counted. Looks good though.

I'm not sure if the goal is to make a tool out of _this page_ or whether the goal would be to lift the essence of it into another, more permanent location so that people can benefit from it. But toward the goal of this being useful by itself, I added a couple minor cosmetic features as I worked through it, for which I've submitted PR #10588 rather than request/convey possibly-meaningless wishlist features. If it's not in line with the goals of the PR, you're free to disregard :)

Screen Shot 2021-04-16 at 9 40 16 AM

I'm continuing to consider the question: how might the information be counted or conveyed such that people would learn as much as possible from it.

**Comment by rreusser** [comment]
Ah, we should also add this page to `test/release/index.js`.

**Comment by mourner** [comment]
> Ah, we should also add this page to `test/release/index.js`.

Not sure — it's more of an exploration tool than something to use for verifying that things are working properly.

**Comment by rreusser** [comment]
Ah, I see. 👍  I've used it for accessing/sharing pages on circle ci, but that makes sense that that's not really the goal of that page.

**Comment by tristen** [comment]
👋 @mourner it's different but could this also support raster and 3d terrain? Noticed putting this style in with satellite+dem in mapbox://styles/tristen/ckni5szoi0a7e17qi6eg99hsl didn't calculate overhead

**Comment by mourner** [comment]
> 👋 @mourner it's different but could this also support raster and 3d terrain? Noticed putting this style in with satellite+dem in mapbox://styles/tristen/ckni5szoi0a7e17qi6eg99hsl didn't calculate overhead

Yeah, this is just a subset of the vector data memory footprint (not including raster data like glyph/icon sprites and raster layers). It might be worth expanding the things it captures, although vertex data vs texture footprint isn't directly comparable in terms of performance.

**Pull request merged**
