### PR TITLE
WIP: add feature-state expression support in filter #6876

### PR DESCRIPTION
**Pull request by stepankuzmin**
I've started digging into #6876 issue, but I'm not sure, is this a right direction.

### CODE REVIEW

**Comment by jfirebaugh** [comment]
Thanks for the PR @stepankuzmin -- however, there are some architectural fundamentals that make supporting `feature-state` for filters problematic. In order to make `setFeatureState` fast and synchronous, it does its work on the main thread. But filter evaluation happens on a web worker at layout time. So right now they are not a good fit for each other.

**Comment by stepankuzmin** [comment]
Oh Okay! Thanks for the reply, @jfirebaugh!

**Comment by annehulsey** [comment]
At @jfirebaugh do you have a suggestion for filtering polygons based on a cursor hover? 

Fill-extrusions don't allow for data driven opacity so I need another way to make objects appear or disappear based on user input. Since I can't use setFeatureState for the expression and it also doesn't work as a filter, I looked into joining a dummy attribute to the data, which could then be used for the filter. However, from what I can tell, data joins only work for expressions that drive the layer symbology. Which leads back to the original problem of fill-extrusions not allowing data driven opacity.

Suggestions would be much appreciated. (I want to use the mouse hover to overlay a transparent black on the hovered building in [this map](https://annehulsey.github.io/SF_Tall_Buildings/). In theory, temporarily darkening the building under the cursor will reduce confusion about which building's info is being displayed on the left.)

**Comment by asheemmamoowala** [comment]
@annehulsey Check out [this](https://github.com/mapbox/mapbox-gl-js/blob/master/debug/extrusion-query.html) demo to see how the `fill-extrusion-color` can be changed on hover. Alternatively, you can copy the hovered over geometry to a separate layer and apply a translation.

**Pull request closed without merging**
