### PR TITLE
[needs code review] Add ImageSource for VideoSource-like image sources.

### LINKED ISSUE #700: Support for ImageSource, similar to VideoSource
I would appreciate support for an image overlay source, similar to the video source but for images. 

Would a naïve porting of the video source code suffice for this?

Would it be complex to have support for changing the coordinates on the source after it has been added (goes for both video and image)?

### PR DESCRIPTION
**Pull request by tmcw**
2015-04-20 at 3 32 pm

* [ ] Add to mapbox-gl-style-spec

Fixes #700

### CODE REVIEW

**Comment by mourner** [comment]
There's quite a lot of code duplication between `image_source` and `video_source`, in particular in `createTile` method — needs refactoring (maybe cutting some shared code into utility functions).

**Comment by tmcw** [comment]
Created a util that de-duplicates the most obviously refactorable chunk of createTile.

**Comment by mourner** [comment]
Yeah, that's better.

**Comment by tmcw** [comment]
Folded into #1081 V8 PR

**Pull request closed without merging**
