### PR TITLE
Add rudimentary support for line-offset

### LINKED ISSUE #1778: Support "line-offset" style property
ref https://github.com/mapbox/mapbox-gl-style-spec/pull/383
ref https://github.com/mapbox/mapbox-gl-native/pull/3092

### PR DESCRIPTION
**Pull request by lucaswoj**
fixes #1778 

ref https://github.com/mapbox/mapbox-gl/issues/3

cc @kkaefer @jfirebaugh

### CODE REVIEW

**Comment by lucaswoj** [comment]
Looks like these tests are [ignored in native](https://github.com/mapbox/mapbox-gl-test-suite/blob/master/render-tests/line-pattern/info.json#L4) so I think this is alright. Adding to the test suite.

**Comment by lucaswoj** [comment]
ready to :ship: @kkaefer @jfirebaugh @mourner?

**Comment by mourner** [comment]
Looks good to me. Did you make sure it doesn't regress performance? Line vertex shader is pretty hot in particular...

**Comment by lucaswoj** [comment]
Buffer benchmark on `master` is 630 ms and on `line-offset-1778` is 614 ms. 

(Yes, it is consistently slightly faster. I've noticed that eliminating variable reassignment is a tiny :+1: for v8 perf.)

**Comment by mourner** [comment]
Great! But I'm wondering about GPU performance (perhaps it doesn't have any impact, I'm just curious). Is it possible to completely skip all the added calculations in the shader if the offset is 0? cc @kkaefer

**Comment by lucaswoj** [comment]
I don't see any red flags in the fps benchmark

```
duration: 3000
43.3 fps https://api.tiles.mapbox.com/mapbox-gl-js/v0.10.0/mapbox-gl.js
55.3 fps https://api.tiles.mapbox.com/mapbox-gl-js/v0.11.5/mapbox-gl.js
55.2 fps /dist/mapbox-gl.js
41.6 fps https://api.tiles.mapbox.com/mapbox-gl-js/v0.10.0/mapbox-gl.js
51.8 fps https://api.tiles.mapbox.com/mapbox-gl-js/v0.11.5/mapbox-gl.js
54.9 fps /dist/mapbox-gl.js
```

**Pull request merged**
