### PR TITLE
Calculate correct canvas size if more than one parent container has a css transform property

### LINKED ISSUE #11492: Map canvas sizing regressed when multiple parent elements have CSS transforms applied to them
This was reported by @jrohland in [this comment](https://github.com/mapbox/mapbox-gl-js/issues/11085#issuecomment-1032981556).

**mapbox-gl-js version**:
2.7.0

**browser**:
Any

### Steps to Trigger Behavior

 1. Set up a map container with multiple parent elements that have CSS transforms applied to them
 2. The map container is not sized correctly

### Link to Demonstration
https://jsfiddle.net/jesserohland/40kzeg7x/2/

### Expected Behavior
The map container should be sized correctly. This happened on older versions as demonstrated in https://jsfiddle.net/jesserohland/40kzeg7x/1/

### Actual Behavior
Map container is not sized correctly.

This is caused by this section of the code. The `while (el && !transformValues)` prevents the container from having multiple transformed parents.
https://github.com/mapbox/mapbox-gl-js/blob/9f780181794d2a41b0ae65abf60eb741677819e0/src/ui/map.js#L2662-L2668

### PR DESCRIPTION
**Pull request by avpeery**
Fixes #11492. Original solution did not consider if more parent containers had transform properties. This fix continues looking for transform values, and avoids exiting early.

## Launch Checklist

 - [x] briefly describe the changes in this PR
 - [x] manually test the debug page
 - [x] apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog'
 - [x] add an entry inside this element for inclusion in the `mapbox-gl-js` changelog: `<changelog>Fixes canvas size if more than one parent container has a transform css property.</changelog>`

### CODE REVIEW

**Review by ryanhamley — COMMENTED** [review]
I spent some time trying this out and I think that there's two potential issues.

1) We only apply the outermost `transform: scale` to the container width. This works in this case where there's 2 transformed elements but only one has a scaled transform. If we have more than one parent element with `transform: scale`, we won't get the correct output.

Something like this doesn't seem to work. Can/should we apply the transform at each step to end up with the final container width?
```
        #new-container {
          width: 1200px;
          height: 800px;
          transform: scale(2);
          transform-origin: top left;
        }

        #scaled-container {
          width: 1920px;
          height: 1080px;
          transform: scale(0.35);
          transform-origin: top left;
          background-color: grey;
        }

        #map-container {
          width: 1720px;
          height: 880px;  
          transform: translate(100px, 100px);
        }

        #map {
          height: 100%;
          width: 100%; 
        }

    <div id="outer-container">
      <div id="scaled-container">
        <div id="map-container">
          <div id="map"></div>
        </div>
      </div>
    </div>
```

2) I think I see why you had the `&& !transformValues`. It's not exactly the right check, but without it, this loop will always iterate all the way out to the `<html>` tag. This could easily be a performance drag, especially if there's quite a bit of nesting in the HTML structure. I'm not sure how to get around this without limiting the potential number of transforms that can be applied.

**Comment by avpeery** [comment]
@ryanhamley Thanks for digging into this. It seems the `!transformValues` check wasn't very useful - if no parents containers had a transform css property it would end up looping through till the outermost container anyways. One potential approach that was previously discussed could be getting clientWidth or offsetWidth (whichever is more appropriate) and get the difference with the getBoundingClientRect to get an approximate scale?

**Comment by avpeery** [comment]
@ryanhamley  This solution works in most transform use-cases with the exception of rotateY and rotateX. Since rotateY and rotateX did not previously work since using getBoundingClientRect was introduced, I think it is ok to not support these use-cases, that are likely very unlikely. Let me know what you think

**Review by ryanhamley — APPROVED** [review]
This works well to fix the reported issue. Handling rotation seems to involve more than just applying the transformation since it breaks zooming around center and possibly other interactions, so it's fine to not handle it, especially since the use case is unclear.

**Pull request merged**
