### PR TITLE
Enable property functions for fill-opacity

### LINKED ISSUE #2728: Enable property functions for fill-opacity

### PR DESCRIPTION
**Pull request by lucaswoj**
fixes #2728

ref https://github.com/mapbox/mapbox-gl-shaders/issues/18
ref https://github.com/mapbox/mapbox-gl-test-suite/issues/109

### CODE REVIEW

**Comment by lucaswoj** [comment]
ready for 👀  @jfirebaugh @mourner @lbud @mollymerp

**Comment by jfirebaugh** [comment]
The tests for this are disabled -- what's the issue there?

**Comment by lucaswoj** [comment]
All of the `fill-opacity != 1` tests are ignored. 

Git history (https://github.com/mapbox/mapbox-gl-test-suite/commit/8e79185e18e33c555e879c0074919ecfbff523d2 and https://github.com/mapbox/mapbox-gl-test-suite/commit/5f81ae5c329540e0e3b341a64680fc03994a9c00) points to https://github.com/mapbox/mapbox-gl-native/issues/1555 as the root cause.

**Comment by lucaswoj** [comment]
Sample test-suite diff:

image

**Comment by jfirebaugh** [comment]
Oooh, I bet it's the same underlying issue as #1702.

**Comment by lucaswoj** [comment]
> Oooh, I bet it's the same underlying issue as #1702.

I think that's a good theory.

What would you like to see from this PR before we :shipit:?

**Comment by lucaswoj** [comment]
# Next Steps

 - [x] point ignored test-suite tests to https://github.com/mapbox/mapbox-gl-js/issues/1702
 - [ ] leave a note on https://github.com/mapbox/mapbox-gl-js/issues/1702 about the fill tests
 - [ ] rebase this branch
 - [ ] 🍏 
 - [ ] :shipit:

**Pull request merged**
