### PR TITLE
Add perspective correction for image, canvas and video sources

### LINKED ISSUE #9158: Mapbox GL JS Image Overlay Coordinates Precision Issue
I'm facing a precision issue with Mapbox GL JS when placing an image overlay on the map with 4 corners coordinates, there is a shift from the expected position by 50-250 m. To reach this conclusion and find this bug, the projection of the image was compared to Leaflet and QGIS, both of them shows the same position of the image but Mapbox GL JS is showing a shift. 

I think this may be a bug in the framework that needs to be fixed. I'm using React Mapbox GL JS and was able to recreate this issue using Mapbox GL JS library within a normal html file. So most probably it's not being caused by React.

To recreate the issue try to overlay an image on the map using Mapbox, Leaflet and QGIS and then compare the results.

**mapbox-gl-js version**: 1.4.0

**browser**: Google Chrome Version 79.0.3945.88 (Official Build) (64-bit)

### Steps to Trigger Behavior

 1. Add an image overlay to Mapbox GL JS using 4 coordinates
```
map.addSource("imageTest", {
"type": "image",
"url": "/DIR/TO/IMAGE",
"coordinates": [
    [LON1,LAT1],
    [LON2,LAT2],
    [LON3,LAT3],
    [LON4,LAT4]
]
})

map.addLayer({
"id": "overlay",
"source": "imageTest",
"type": "raster"
})

```
 2. Geo reference the same image using GDAL Georeferencer on QGIS  with the same coordinates and use QGIS to load the resulting GeoTIFF.

 3. Overlay the image using Leaflet Distortable Image https://github.com/publiclab/Leaflet.DistortableImage 
 4. Compare the 3 projections, a shift shall be observed only with the Mapbox projection and on the y axis most probably.

### Expected Behavior

All of these methods should yield the same results.

### Actual Behavior

Mapbox is showing a major shift sometimes up to 250 meters for an image with a swath of 3 km.

Check this screenshot: (QGIS left, Mapbox center, Leaflet right)

photo_2020-01-07_18-08-05

### PR DESCRIPTION
**Pull request by mourner**
Closes #9158. Currently, our image, canvas and video sources do simple linear interpolation when mapping a texture to a quad for the layer. This only works if the quad is exactly a rectangle — in other cases, the texture is distorted:

image

This PR introduces perspective correction, calculating a perspective transform matrix given the four coordinates (based on [this brilliant StackOverflow answer](https://math.stackexchange.com/a/339033/48653) by @gagern 🙏), and then passing a part of it as a uniform to the raster vertex shader so that it can properly calculate the `w` component (used by WebGL for texture mapping correction) for each of the four vertices.

before | after
--- | ---
image | image

## Launch Checklist

 - [x] briefly describe the changes in this PR
 - [x] include before/after visuals or gifs if this PR includes visual changes
 - [x] write tests for all new functionality
 - [ ] document any changes to public APIs
 - [ ] post benchmark scores
 - [x] manually test the debug page
 - [x] tagged @mapbox/gl-native — this PR includes shader changes and needs a native port
 - [x] apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog'
 - [x] add an entry inside this element for inclusion in the `mapbox-gl-js` changelog: `<changelog>Add perspective correction for non-rectangular image, canvas and video sources</changelog>`

### CODE REVIEW

**Review by ansis — APPROVED** [review]

**Comment by mourner** [comment]
One thing I forgot to mention is that the updated render test images, apart from the perspective correction, look a little darker — not different enough to fail tests but noticeable. I guess this is some kind of color profile difference between machines / OS? The new fixtures are how the CI renderes it in Circle too so this seems fine.

**Comment by HansBrende** [comment]
@mourner that's probably because you're not doing due diligence in correcting the image gamma before transforming the image. One of the most common bugs in most image scaling software. See: http://www.ericbrasseur.org/gamma.html

**Comment by mourner** [comment]
@HansBrende this wouldn't explain why they were lighter in fixtures before and got darker subsequently, implying we handled gamma correctly before but then somehow broke it.

**Comment by HansBrende** [comment]
@mourner no clue! Could be that perspective transform handles gamma worse than affine transform. All I know is: when images' brightness is off after scaling/transforming... it is _usually, in my experience, in fact never once has it **not** been_, a gamma issue.

**Comment by endanke** [comment]
@mourner I have one theory: maybe there were some other changes previously that changed the brightness, but the render tests didn't catch it because it wasn't a large enough difference. This could be verified if we revert these changes and compare the output manually with the previous expectations.

**Pull request merged**
