### PR TITLE
Handle 'Not Found' errors to allow 'loaded' event

### LINKED ISSUE #1800: Suppress error messages for missing tiles
There is log spew about missing tiles, though it is valid for a tile endpoint to return a 404 to express "no data". We should suppress these error messages.

ref #1549

### PR DESCRIPTION
**Pull request by laurenancona**
We've been running our own fork with this patch since `0.11.0` because the errors prevent `loaded` from returning `true`. Still results in noisy logs, but find it preferable to silent failure while debugging. 

Closes #1800.

### CODE REVIEW

**Comment by lucaswoj** [comment]
Thank you for the PR @laurenancona! 

# Next Steps

 - [ ] create an `ajax.Error` error class with `statusText` and `statusCode` properties (requires changing both `util/ajax` and `util/browser/ajax`)
 - [ ] check for `error instanceof ajax.Error && error.statusCode === 404` before silently dismissing the error
 - [ ] squash into one commit

**Comment by laurenancona** [comment]
Excellent, thanks @lucaswoj. We're taking a shot at it. :gun:

**Comment by lucaswoj** [comment]
Thank _you_ @laurenancona! Ping me in Slack if you have any questions!

**Comment by lucaswoj** [comment]
Replaced by #2176

**Pull request closed without merging**
