### PR TITLE
Standardize on a 1024x768 map for FPS benchmarking

### PR DESCRIPTION
**Pull request by lucaswoj**
The previous benchmarking page was rendering a 0x0 map and pretty much always produced 60 FPS. Unless I'm missing something, we should aim for a reasonable map size, like 1024x768. This results in about 10 FPS on my machine, which is generally consistent with my experience using GL JS in the wild. 

cc @jfirebaugh @kkaefer @ansis

### CODE REVIEW

**Comment by jfirebaugh** [comment]
The existing behavior might be browser specific. In Chrome it uses a map the size of the window.

**Comment by jfirebaugh** [comment]
> This results in about 10 FPS on my machine, which is generally consistent with my experience using GL JS in the wild.

Hmm, that's unexpectedly slow, extremely so. I get near 60 fps on chrome (on this `benchmark` branch).

**Comment by ansis** [comment]
It looks like the benchmark is currently using `dist/mapbox-gl.js` instead of `dist/mapbox-gl-dev.js` which gets built only when you run `npm install` or `npm run production`. We should switch that to -dev.

I get 30fps for master and v0.7 running full screen on retina.

@jfirebaugh are you running the benchmark on an external monitor?

**Comment by jfirebaugh** [comment]
@ansis I think you might have `dist/mapbox-gl.js` vs `dist/mapbox-gl-dev.js` backwards. I think we want to use `dist/mapbox-gl.js`, the production version.

External monitor vs laptop screen makes no difference for me -- it's always 60fps.

**Comment by lucaswoj** [comment]
@jfirebaugh I set the map in the benchmark to `height: 100%` yesterday in [this PR](https://github.com/mapbox/mapbox-gl-js/pull/1258), merged yesterday. 

Before that, it was implicitly 600px high and 100px wide, but all inside a 0px high container/`body`/`html`... You're right that different browsers handled that differently.
screen shot 2015-06-10 at 12 47 10 pm

We're always going to see different perf on different laptops, and on the same laptop under different loads but I think standardizing our benchmarks on 1024x768 is a good start.

**Comment by lucaswoj** [comment]
Closing all open programs on my laptop is the difference between 10fps and 30fps.

**Comment by lucaswoj** [comment]
The debug page, which definitely shows the latest code changes, uses `/debug/mapbox-gl.js`. Maybe bench should be consistent?

**Comment by jfirebaugh** [comment]
> I think standardizing our benchmarks on 1024x768 is a good start.

Agreed.

> `/debug/mapbox-gl.js`

This file isn't generated by any build scripts and I don't have it locally. Are you sure you didn't copy it from `dist`?

**Comment by jfirebaugh** [comment]
Never mind, I see now where `/debug/mapbox-gl.js` is coming from... hard to keep up with the build changes.

**Comment by lucaswoj** [comment]
:ship:?

**Comment by jfirebaugh** [comment]
:ship:

**Pull request merged**
