### PR TITLE
Add "placeholder-loading-*" properties

### LINKED ISSUE #3280: raster layer "loading" pattern and "errored" pattern
Is there a way to set a grid pattern as the bg while tile requests are waiting to be loaded?

### PR DESCRIPTION
**Pull request by lucaswoj**
**[Play with the demo!](http://bl.ocks.org/lucaswoj/raw/66b9311793be3fd39b944779270f21e7/#16/40.6892/-74.0447)**

This PR allows developers to show a pattern or color in lieu of a still-loading raster tile. 

 - `placeholder-loading-color`
 - `placeholder-loading-pattern`
 - `placeholder-loading-opacity`

This feature is useful when loading raster tiles that use transparency to represent "no data." In the image below 👇  is there really no storm over SF? Or has the tile not loaded? Or has the tile errored? 

screen shot 2016-11-23 at 3 20 25 pm

In some industries, there is a regulatory requirement that a pattern be shown to disambiuate between "no data", "data loading", and "data errored"

cc @lbud @jfirebaugh @mourner 

fixes #3280 

## Launch Checklist

 - [x] create a new style layer type
 - [x] briefly describe the changes in this PR
 - [ ] write tests for all new functionality
 - [ ] document any changes to public APIs
 - [ ] post benchmark scores
 - [x] manually test the debug page

### CODE REVIEW

**Comment by jfirebaugh** [comment]
This would be useful for vector sources as well. Can we make it more general, taking into account the ideas in https://github.com/mapbox/mapbox-gl-style-spec/issues/219?

**Comment by lucaswoj** [comment]
I see the value in making this it's own layer type. That would give developers the ability to use this feature with vector tiles and control the z-ordering of the loading pattern.

Glomming this onto the `raster` layer type was just a prototyping expediency 😄

**Comment by lucaswoj** [comment]
The latest commit adds a new layer type called `source`. I like how self-explanitory the property names are: `source-loading-pattern`, `source-loading-opacity`, etc. 

Open to other naming ideas that convey a layer which displays source metadata. Also open to creating separate `source-loading` and `source-errored` layer types.

**Comment by lucaswoj** [comment]
Updated to put the functionality on a new layer type called `placeholder`

 - `placeholder-loading-color`
 - `placeholder-loading-pattern`
 - `placeholder-loading-opacity`

Thoughts @jfirebaugh?

**Comment by lucaswoj** [comment]
ping @jfirebaugh @lbud 

----

I'm thinking about redoing the style spec such that it consists of

 - `placeholder-color`
 - `placeholder-pattern`
 - `placeholder-opacity`
 - `placeholder-type`: `loading` or `errored`

This will simplify the API and give users more control over layering order

**Comment by lucaswoj** [comment]
Gonna take this back to the drawing board somewhat 😄

**Pull request closed without merging**
