### PR TITLE
Refactor StyleLayer

### LINKED ISSUE #1957: Refactor StyleLayer to prepare for data-driven styles
As a step towards data-driven styling #1626 we need a good way to share information about shader attributes between workers and the main thread. This should be done through `StyleLayer` subclasses. 

We should create a class per layer type (i.e. `LineStyleLayer`, `CircleStyleLayer`, `FillStyleLayer`, ...) like we did in mapbox-gl-native. In the long run, these classes should encapsulate all layer-specific operations, including drawing, bucket building, etc. For data-driven styling, these classes need to 

 - be easily instantiatable in workers 
 - be able to tell which shader attributes are enabled / disabled

### PR DESCRIPTION
**Pull request by lucaswoj**
This PR is some housecleaning before I tackle #1957 

# Next Steps

 - [x] Add `StyleLayer.create` factory function
 - [x] Remove `StyleLayer#resolveReference` method
 - [x] Shore up `StyleLayer` terminology
 - [x] Add `StyleLayer` subclasses
 - [x] Move all layer-type-specific logic into `StyleLayer` subclasses
 - [x] Traipse back in time to remove source-layer TODO and _refLayer property
 - [x] Create `StyleLayer#isHidden` method
 - [x] Inline `premultiplyLayer`
 - [x] Rename `source-layer` to `sourceLayer`
 - [x] Performance testing

### CODE REVIEW

**Comment by mourner** [comment]
@lucaswoj this looks really good! Minor thing: let's profile and make sure premultiplying refactor didn't increase CPU usage per frame much, as it was already taking a noticeable amount of time before.

**Comment by lucaswoj** [comment]
@mourner I further refactored to remove the `premultiply` method altogether, opting instead to do that calculation in the `draw_*` methods. This adds a few more operations to the render, but only on the order of a couple dozen multiplications. Performance testing indicates no impact. 

```
duration: 3000
47.2 fps https://api.tiles.mapbox.com/mapbox-gl-js/v0.12.4/mapbox-gl.js
48.7 fps /dist/mapbox-gl.js
47.8 fps https://api.tiles.mapbox.com/mapbox-gl-js/v0.12.4/mapbox-gl.js
47.7 fps /dist/mapbox-gl.js
```

**Comment by lucaswoj** [comment]
This is ready for :eyes: @ansis @mourner @jfirebaugh @kelvinabrokwa

**Comment by ansis** [comment]
looks good to me!

**Comment by jfirebaugh** [comment]
Nice!

**Pull request merged**
