### PR TITLE
Add rules for High Contrast mode on Windows

### PR DESCRIPTION
**Pull request by kkaefer**
High Contrast White:

high-contrast-white-ie11

High Contrast Black:

high-contrast-black-ie11

We're inlining SVGs in our stylesheet, and this patch inlines almost identical SVGs several times. This is likely compressed away with gzipping the CSS file, but we could look into using a different way of rendering the icons, e.g. by embedding the SVG in the document and then using CSS to style individual paths rather than using `postcss` to materialize the recolored SVGs at build time.

### CODE REVIEW

**Comment by kkaefer** [comment]
Fixes https://github.com/mapbox/mapbox-gl-js/issues/5784

**Comment by andrewharvey** [comment]
> We're inlining SVGs in our stylesheet, and this patch inlines almost identical SVGs several times. This is likely compressed away with gzipping the CSS file, but we could look into using a different way of rendering the icons, e.g. by embedding the SVG in the document and then using CSS to style individual paths rather than using postcss to materialize the recolored SVGs at build time.

This is being discussed in #8767

**Comment by kkaefer** [comment]
@andrewharvey Thanks for pointing out that issue, I wasn't aware of it.

**Comment by kkaefer** [comment]
> Do we have any qualms about using this given the warning on MDN?

What MDN page is this from?

**Comment by ryanhamley** [comment]
> > Do we have any qualms about using this given the warning on MDN?
> 
> What MDN page is this from?

https://developer.mozilla.org/en-US/docs/Web/CSS/@media/-ms-high-contrast

**Comment by kkaefer** [comment]
Updated this PR with the optimized SVGs from https://github.com/mapbox/mapbox-gl-js/pull/8884. I also made a few changes to unify the way we use CSS:

- All clickable buttons are `<button>` elements. They get the `disabled` attribute set when they aren't active. Previously, some were disabled, some had the `mapboxgl-ctrl-icon-disabled` class set.
- All `<button>` elements now have a child node `<span class="mapboxgl-ctrl-icon" aria-hidden="true"></span>` that contains the icon as the background image. This is necessary because some icons are transformed and the clickable/hoverable area would change otherwise.
- The buttons are now 29 pixels wide instead of 30. I made this change because most icons have an odd width so that there's a pixel that is in the dead center of the icon.
- Removed a few `>` specifiers; they aren't necessary and make it harder to override the CSS

**Comment by kkaefer** [comment]
IE11 regular:

regular

IE11 High Contrast Mode Black on White:

high-contrast-white

IE11 High Contrast Mode White on Black:

high-contrast-black

**Pull request merged**
