### PR TITLE
Update Code of Conduct (v2.0, https links)

### PR DESCRIPTION
**Pull request by mourner**

### CODE REVIEW

**Comment by kkaefer** [comment]
What are the differences between 1.2 and 2.0?

**Comment by mourner** [comment]
@kkaefer the biggest change in a new section about enforcement of the rules, and generally tighter wording. Take a look at the full texts in the respective links to compare.

**Comment by vakila** [comment]
Thanks for the update @mourner! 

@kkaefer I was wondering this too! Seems they don't have a changelog but from https://github.com/ContributorCovenant/contributor_covenant/pull/709:

> Changes include:
> 
>   Language updates to emphasize community over project scope
>   Additional examples of positive behavior
>   Clarification around sexual attention and advances
>   Community Impact Guidelines


@mourner  while we're updating this, per https://www.contributor-covenant.org/version/2/0/code_of_conduct#enforcement I think we need to explicitly let people know where & how to report violations or other concerns/questions. Without that the CoC is basically useless. @asheemmamoowala do we have a team email account we could use for that? (Asking folks to tag the team in public won't work for this.)

Also - not a blocker, but - we should add Mapbox to the [adopters list](https://github.com/ContributorCovenant/contributor_covenant/blob/release/static/adopters.csv)! I can do that

**Comment by vakila** [comment]
https://github.com/ContributorCovenant/contributor_covenant/pull/750

**Pull request merged**
