### PR TITLE
Support credentialed requests for images.

### PR DESCRIPTION
**Pull request by vicapow**
Support for credentialed requests for map image textures / sprites.

### CODE REVIEW

**Comment by jfirebaugh** [comment]
I believe this will break an existing case that currently works, namely where the server responds with `Access-Control-Allow-Origin` but not `Access-Control-Allow-Credentials`.

**Comment by jfirebaugh** [comment]
Oh, I see you're only setting `Use-Credentials` for _non_ cross-origin requests. I bet you're trying to work around https://code.google.com/p/chromium/issues/detail?id=412163, right?

**Comment by vicapow** [comment]
Oh, I didn't realize it was a bug. But yeah, that's what I'm trying to fix.

**Comment by jfirebaugh** [comment]
@vicapow Can you test https://github.com/mapbox/mapbox-gl-js/commit/d1a35f75ff2fdd9199a2093d2250d03a9a43d294?

**Comment by vicapow** [comment]
Seems like img.crossOrigin would always be "Anonymous"

**Comment by jfirebaugh** [comment]
Not always -- only when it's actually a cross-origin request. Same origin requests shouldn't need any `crossOrigin` attribute.

**Comment by vicapow** [comment]
whoops. red means minus.

**Comment by vicapow** [comment]
okay, tested it out. Looks good!

FYI, I get this error from documentation generation with that commit sha.

````
> mapbox-gl@0.7.0 docs /home/vicapow/projects/mapbox-gl-js
> node docs/_generate/generate.js


/home/vicapow/projects/mapbox-gl-js/node_modules/documentation/streams/nest_params.js:30
      var parts = param.name.split(/(\[\])?\./);
                             ^
TypeError: Cannot call method 'split' of null
    at /home/vicapow/projects/mapbox-gl-js/node_modules/documentation/streams/nest_params.js:30:30
    at Array.forEach (native)
    at Stream.<anonymous> (/home/vicapow/projects/mapbox-gl-js/node_modules/documentation/streams/nest_params.js:28:20)
    at Stream.stream.write (/home/vicapow/projects/mapbox-gl-js/node_modules/through/index.js:26:11)
    at Readable.write (/home/vicapow/projects/mapbox-gl-js/node_modules/documentation/node_modules/stream-splicer/node_modules/readable-wrap/index.js:52:31)
    at Readable.ondata (/home/vicapow/projects/mapbox-gl-js/node_modules/documentation/node_modules/stream-splicer/node_modules/readable-stream/lib/_stream_readable.js:572:20)
    at Readable.emit (events.js:95:17)
    at readableAddChunk (/home/vicapow/projects/mapbox-gl-js/node_modules/documentation/node_modules/stream-splicer/node_modules/readable-stream/lib/_stream_readable.js:195:16)
    at Readable.push (/home/vicapow/projects/mapbox-gl-js/node_modules/documentation/node_modules/stream-splicer/node_modules/readable-stream/lib/_stream_readable.js:162:10)
    at Stream.<anonymous> (/home/vicapow/projects/mapbox-gl-js/node_modules/documentation/node_modules/stream-splicer/node_modules/readable-wrap/index.js:39:20)
````
I had to prevent doc generation to get it to build:
````diff
diff --git a/package.json b/package.json
index baf83ab..5bdc96b 100644
--- a/package.json
+++ b/package.json
@@ -70,7 +70,7 @@
     "lint": "eslint js test",
     "test": "npm run lint && prova test/js/*/*.js",
     "test-suite": "node test/render.test.js || true",
-    "build": "browserify -d js/mapbox-gl.js --standalone mapboxgl > dist/mapbox-gl-dev.js && npm run docs",
+    "build": "browserify -d js/mapbox-gl.js --standalone mapboxgl > dist/mapbox-gl-dev.js",
     "production": "browserify js/mapbox-gl.js -d -p [minifyify --map mapbox-gl.js.map --output dist/mapbox-gl.js.map] --standalone mapboxgl > dist/mapbox-gl.js",
     "prepublish": "npm run build && npm run production",
     "cov": "istanbul cover prova test/js/*/*.js test/render.test.js -x js/lib/debugtext.js",
````

**Comment by jfirebaugh** [comment]
Cool, committed as 519a6e996ed344f5e42ae6f9f4c18a1214bab775. The doc bug was my bad, that's also fixed.

**Pull request closed without merging**
