### PR TITLE
Experiment: New rotation and pitch alignments for markers on globe

### PR DESCRIPTION
**Pull request by SnailBones**
image

Extension of https://github.com/mapbox/gl-js-team/issues/373.

This PR is an experiment with potential new alignment for markers on globe, facing the horizon. (Since the horizon is curved in globe, this corresponds to `viewport` alignment in flat projections, but could be another option alongside `viewport` alignment in globe.)

### Globe rotation alignment:

https://user-images.githubusercontent.com/14878684/160705714-7de80b7e-f16e-4615-9d2d-4149461d4c7a.mov

```js
const marker = new mapboxgl.Marker({
      rotationAlignment: 'globe',
      pitchAlignment: 'viewport' // This line can also be left out
  })
```

### Globe rotation alignment and globe pitch alignment:

This affect can be heightened by changing the marker's length to suggest rotation in 3d, and the effect can be controlled by a pitch alignment option of the same name. With custom linear markers, this could be used to create an effect similar to [pitch-based filtering](https://docs.mapbox.com/mapbox-gl-js/example/switch-symbol-style-pitch/) but providing full interactivity.

https://user-images.githubusercontent.com/14878684/160705141-7767f00f-b531-4c79-90e6-f81c7f2ea50d.mov

```js
const marker = new mapboxgl.Marker({
      rotationAlignment: 'globe',
      pitchAlignment: 'globe'
  })
```
Currently, both of these properties smoothly transition to the behavior of "viewport" alignment as the map zooms in. The transition can be adjusted, but my opinion is that it should probably be hard-coded rather than exposed to the user. Similarly,, the behavior in non-Mercator projections is identical to "viewport." 

The new behavior(s) require a new alignment option in the API. The existing marker names ("map", "viewport", "auto") describe not a direction but a coordinate space, reflecting that markers can be rotated to face any direction within that space. Ideas for the new option include: "globe", "horizon" or "origin".

## Launch Checklist

 - [X] briefly describe the changes in this PR
 - [X] include before/after visuals or gifs if this PR includes visual changes
 - [ ] write tests for all new functionality
 - [ ] document any changes to public APIs
 - [ ] post benchmark scores
 - [ ] manually test the debug page
 - [ ] tagged `@mapbox/gl-native` if this PR includes shader changes or needs a native port
 - [ ] apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog'
 - [ ] add an entry inside this element for inclusion in the `mapbox-gl-js` changelog: `<changelog></changelog>`

@mapbox/map-design-team @mapbox/static-apis

### CODE REVIEW

**Comment by akoylasar** [comment]
@SnailBones The first option looks really nice and also easy to work with! The markers in the second one IMHO could be hard to pick especially if they're directly below the camera (which is visible like a line only).

**Comment by tristen** [comment]
@SnailBones agree with @akoylasar that the second option has some usability and visual issues. 

Is it possible to avoid adding a `globe` value altogether? I would expect:

```js
const marker = new mapboxgl.Marker({
  rotationAlignment: 'map',
  pitchAlignment: 'viewport'
});
```

to work just as prescribed in that first option. rotation alignment is just adapting to the map projected as a globe and not irrespective of `map`.

**Comment by SnailBones** [comment]
> @SnailBones The first option looks really nice and also easy to work with! The markers in the second one IMHO could be hard to pick especially if they're directly below the camera (which is visible like a line only).

@akoylasar @tristen Good idea! I've tried adding a limit to their tilt at 80 degrees, how's this?

https://user-images.githubusercontent.com/14878684/160910688-33c03064-88d6-4966-8d04-7049dc72fb10.mov

> Is it possible to avoid adding a `globe` value altogether? I would expect:
> 
> ```js
> const marker = new mapboxgl.Marker({
>   rotationAlignment: 'map',
>   pitchAlignment: 'viewport'
> });
> ```
> 
> to work just as prescribed in that first option. rotation alignment is just adapting to the map projected as a globe and not irrespective of `map`.

@tristen My understanding is that both cases with opposite `rotationAlignment` and `pitchAligment` are not commonly used, so I first attempted to fit this new behavior into thew behavior into the existing API as you propose.

One concern is that this would be a breaking change. Currently, the combination you mention above creates markers with a top pointing north, but no pitch compression. Here's what that looks like on Mercator:

image

and Globe:

image

I think that we would need to verify that the number of affected users would be sufficiently negligible. I could see this alignment option being used to create a compass rose.

Besides the breaking change, there's two other reasons why I think expanding the API would be the better choice here.

- Using the "map" + "viewport" combo to trigger the new alignment may not be very intuitive, since "map" alignment already has a precise definition. `rotationAlignment: "map"` means that the marker's rotation matches that of the map, or in the case of globe, the longitude line at the point of the marker as demonstrated in https://github.com/mapbox/mapbox-gl-js/pull/11556. (This alignment option is needed to support draping labels.) The proposed behavior is quite different: rotation is relative to the globe center, so using the same options for each opens potential for confusion.

- This choice would lock us in and leave less room for expanding alignment options. Even if we decide against adding the option in my second video above (proposed as globe rotation + globe pitch) for now, it would make it difficult to add it (or another similar alignment option) in the future. (In theory, we could fill the also rarely used `{ rotationAlignment: 'viewport', pitchAlignment: 'map' };`, but at that point we'd just be wedging in new behaviors with no regard for the meaning of the words in the API.)

**Comment by tristen** [comment]
> One concern is that this would be a breaking change. Currently, the combination you mention above creates markers with a top pointing north, but no pitch compression. Here's what that looks like on Mercator:

Is it possible to preserve the same behavior for all other projections and just change the behavior for `projection:globe`?

> I've tried adding a limit to their tilt at 80 degrees, how's this?

Personally, I don't see a strong use case for `pitchAlignment: 'globe'` I wonder if it should be left out for now but I'm curious what @mapbox/map-designers think and whether behavior is more suitable for [custom markers](https://docs.mapbox.com/mapbox-gl-js/example/custom-marker-icons/)?

**Comment by karimnaaji** [comment]
`rotationAlignment: 'globe',` is an interesting concept and enhances the 3d effect. To help visualizing the behavior, I would try to also experiment with different types of marker, such as this one:

Screen Shot 2022-04-04 at 1 59 07 PM

Between `globe` and `horizon`, `horizon` seems clearer as you shouldn't have to think of the projection, but where the marker will be pointing towards, and `rotationAlignment: 'horizon'` seems to suggest the final visual behavior.

Otherwise, I've got two questions:
- Since marker alignment are matching and 1:1 with symbol alignments, I wonder whether we should think of this holistically and consider whether this alignment should be introduced on symbols too and as part of the style specification? If so, we should probably think whether there is a strong use case for that alignment for iconography/symbols.
- How would popup be handled with these alignment modes? As they usually represent information you'd like to read, it seems like that it might bring some UX issues since the marker can be shown upside down.

Screen Shot 2022-04-04 at 2 09 11 PM

**Comment by SnailBones** [comment]
> Between `globe` and `horizon`, `horizon` seems clearer as you shouldn't have to think of the projection, but where the marker will be pointing towards, and `rotationAlignment: 'horizon'` seems to suggest the final visual behavior.

Good point @karimnaaji , it's not clear what behavior a `globe` aligned marker should have in Mercator.

> - Since marker alignment are matching and 1:1 with symbol alignments, I wonder whether we should think of this holistically and consider whether this alignment should be introduced on symbols too and as part of the style specification? If so, we should probably think whether there is a strong use case for that alignment for iconography/symbols.

My sense is that use cases for this alignment will largely overlap with those where HTML markers are a preferable option to symbols: low zoom and a small number of points of interest, so I would call this a nice-to-have but less essential for symbol layers. I'd be interested in hearing the thoughts of the @mapbox/map-design-team on whether this might have broader styling uses.

> - How would popup be handled with these alignment modes? As they usually represent information you'd like to read, it seems like that it might bring some UX issues since the marker can be shown upside down.

Popups do not have alignment options and are always viewport aligned, regardless of the map direction and marker alignment. This behavior has not changed with this PR. Here's an upside-down marker with a popup.

image

**Comment by willymaps** [comment]
@SnailBones thanks for all the demos! Echoing what's already been mentioned above – I think `rotationAlignment: 'globe'` is problematic for two-dimensional symbols/markers. When thinking about more complex symbology:

- legibility would be a concern
- manipulating the dimensions could have unexpected results

> My sense is that use cases for this alignment will largely overlap with those where HTML markers are a preferable option to symbols: low zoom and a small number of points of interest, so I would call this a nice-to-have but less essential for symbol layers. I'd be interested in hearing the thoughts of the https://github.com/orgs/mapbox/teams/map-design-team on whether this might have broader styling uses.

I don't think this behavior is essential to any of our core styles, but I could see users in Studio potentially wanting this for icon-only symbol layers.

**Comment by karimnaaji** [comment]
Closing in favor of https://github.com/mapbox/mapbox-gl-js/pull/11894

**Pull request closed without merging**
