### PR TITLE
Fix easeTo interpolation on pitched maps

### LINKED ISSUE #4178: easeTo goes in the wrong direction
**mapbox-gl-js version**:0.32.1

### Steps to Trigger Behavior

 1. View https://bl.ocks.org/stevage/c80f9b241866642abdb2e6da8231cde6
 2. Wait for the second camera transition

### Expected Behavior
Camera should ease south

### Actual Behavior
Camera eases north, then miraculously reappears from the south.

It works properly with flyTo instead of easeTo.

### PR DESCRIPTION
**Pull request by mourner**
A PR in place of #4320. Should close #4178 and #3112.

Changes `easeTo` implementation to have more robust interpolation, fixing weird behavior on pitched maps, making it more consistent with `flyTo`, and makes the definition of `offset` less ambiguous.

Haven't updated expected values in the camera tests, but otherwise this is ready for review.

cc @joswinter

## Launch Checklist

 - [x] briefly describe the changes in this PR
 - [x] write tests for all new functionality
 - [x] document any changes to public APIs
 - [ ] ~~post benchmark scores~~
 - [x] manually test the debug page

### CODE REVIEW

**Comment by mourner** [comment]
This turned out to be more complicated than I thought. We can't simply interpolate linearly through projected center because e.g. as you zoom in to a non-centered point, the scale increases exponentially while map center interpolates linearly, leading to a curved animation.

**Comment by mourner** [comment]
OK, I think I finally got this right, with proper offset handling, and the tests pass. The easing while zooming interpolation formula is still probably not 100% scientifically correct, but it works well in practice, and me and @anandthakker couldn't come up with anything better.

I'd like to improve the easing code further as there is still some logic duplication going on between `easeTo` and `flyTo`, but I'd rather do that in a follow-up PR.

**Comment by mourner** [comment]
@1ec5 should this be ported to native? It changes the way `easeTo` animations are calculated quite substantially.

**Comment by 1ec5** [comment]
The native implementation diverged from the GL JS implementation shortly after I ported it, but we probably do have to revisit the native implementation in light of mapbox/mapbox-gl-native#5292.

**Pull request merged**
