### PR TITLE
Fixing render test console.logs in browser

### PR DESCRIPTION
**Pull request by SnailBones**
This change fixes console.log() not working on successful render tests.
 - [x] apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog'

### CODE REVIEW

**Comment by rreusser** [comment]
Can you clarify the effect this has? It looks like this is the implementation:

https://github.com/testem/testem/blob/152b25f377a18411fed597494968204932a725cc/public/testem/testem_client.js#L385-L402

Does it duplicate the console log within the browser?

**Comment by SnailBones** [comment]
> Can you clarify the effect this has? It looks like this is the implementation:
> 
> https://github.com/testem/testem/blob/152b25f377a18411fed597494968204932a725cc/public/testem/testem_client.js#L385-L402
> 
> Does it duplicate the console log within the browser?

Yes, with this change the logs appear in the browser rather than only in the terminal.

**Comment by rreusser** [comment]
Works for me. Do you encounter this when running via `watch-render`?

**Comment by ryanhamley** [comment]
Have you tried running this with the full suite? The render tests were tough to get performant and I'm guessing constantly logging to the console may slow things down quite a bit.

**Comment by avpeery** [comment]
A thought is perhaps it there could be an additional flag set when running tests to console.log in browser so it doesn't automatically do it for every test if it interferes with performance?

**Comment by avpeery** [comment]
@SnailBones LGTM, I ran it the test-suite on your branch and it finished in ~236 seconds and on the main branch, the test-suite finished in ~245 seconds, so it doesn't appear to be slower on my end

**Review by avpeery — APPROVED** [review]

**Comment by SnailBones** [comment]
> @SnailBones LGTM, I ran it the test-suite on your branch and it finished in ~236 seconds and on the main branch, the test-suite finished in ~245 seconds, so it doesn't appear to be slower on my end

Thanks for doing that @avpeery! To clarify, those times are for `yarn run test-suite`?

**Review by karimnaaji — DISMISSED** [review]
Can we make sure to not regress the "normal" logs that are in the default console with this change? Refer for example the logs of this CI build https://app.circleci.com/pipelines/github/mapbox/mapbox-gl-js/7566/workflows/3f665c87-da9e-4471-b54c-540941f354c3/jobs/97744 that now has a lot of noise and clutters the console with extra information:
```
ok 1372 Chrome 91.0 - [undefined ms] - render-tests/text-variable-anchor/all-anchors
    ---
        browser log: |
            LOG: ok 1372 render-tests/text-variable-anchor/all-anchors
            LOG: # render-tests/text-variable-anchor/avoid-edges-tile-map-mode
            LOG: # SKIP render-tests/text-variable-anchor/avoid-edges-tile-map-mode
            LOG: # render-tests/text-variable-anchor/icon-image-all-anchors
            LOG: # render-tests/text-variable-anchor/icon-image-all-anchors
    ...
ok 1373 Chrome 91.0 - [undefined ms] - render-tests/text-variable-anchor/icon-image-all-anchors
    ---
        browser log: |
            LOG: ok 1373 render-tests/text-variable-anchor/icon-image-all-anchors
            LOG: # render-tests/text-variable-anchor/icon-image
            LOG: # render-tests/text-variable-anchor/icon-image
    ...
```
with the following warning:
Screen Shot 2021-08-17 at 1 11 31 PM

The default output should remain minimal:
```
ok 1433 Chrome 91.0 - [undefined ms] - render-tests/zoom-visibility/above
ok 1434 Chrome 91.0 - [undefined ms] - render-tests/zoom-visibility/below
ok 1435 Chrome 91.0 - [undefined ms] - render-tests/zoom-visibility/in-range
ok 1436 Chrome 91.0 - [undefined ms] - render-tests/zoom-visibility/out-of-range
ok 1437 Chrome 91.0 - [undefined ms] - render-tests/zoom-visibility/was-above
ok 1438 Chrome 91.0 - [undefined ms] - render-tests/zoom-visibility/was-below
ok 1439 Chrome 91.0 - [undefined ms] - render-tests/zoomed-fill/default
```

**Comment by avpeery** [comment]
> > @SnailBones LGTM, I ran it the test-suite on your branch and it finished in ~236 seconds and on the main branch, the test-suite finished in ~245 seconds, so it doesn't appear to be slower on my end
> 
> Thanks for doing that @avpeery! To clarify, those times are for `yarn run test-suite`?

@SnailBones, yes this was with yarn run test-suite.

**Comment by SnailBones** [comment]
> Can we make sure to regress the "normal" logs that are in the default console with this change? 

Good catch @karimnaaji! Thoughts on if there's a way to make that distinction in `tape_config`?

> A thought is perhaps there could be an additional flag set when running tests to console.log in browser so it doesn't automatically do it for every test if it interferes with performance?

@avpeery I think this is a great idea!

**Comment by karimnaaji** [comment]
@SnailBones After giving a quick look these outputs seem to be the result of the following line https://github.com/testem/testem/blob/master/lib/reporters/tap_reporter.js#L59, so maybe using one of the options from https://github.com/testem/testem#tap-options
```
{
  "tap_quiet_logs": true
}
```
While keeping your change in `handleConsoleMessage`.

**Comment by SnailBones** [comment]
> @SnailBones After giving a quick look these outputs seem to be the result of the following line https://github.com/testem/testem/blob/master/lib/reporters/tap_reporter.js#L59, so maybe using one of the options from https://github.com/testem/testem#tap-options
> 
> ```
> {
>   "tap_quiet_logs": true
> }
> ```
> 
> While keeping your change in `handleConsoleMessage`.

Thanks @karim! Just added that option and CI logs seem back to normal.

**Comment by karimnaaji** [comment]
Tested that locally and that worked to remove the extra info on successful tests.

I explicitly made one test fail, and for such test it seems like a side effect of handling the console log duplicates some information on failure, making it a bit harder to see what went wrong, I'm not entirely sure how to address this one but maybe we need to inspect the message status in `handleConsoleMessage` and prevent the console message in such case, I'm not sure.

```
* Error: ENOENT: no such file or directory, open '/Users/karimnaaji/dev/mapbox-gl-js/test/integration/mapbox:/styles/mapbox/streets-v11'
ok 1 Chrome 92.0 - [undefined ms] - render-tests/fill-extrusion-pattern/opacity-terrain-flat
not ok 2 Chrome 92.0 - [undefined ms] - render-tests/fill-extrusion-pattern/opacity-terrain
    ---
        ok: >
            false
        id: >
            2
        name: >
            render-tests/fill-extrusion-pattern/opacity-terrain
        diag: >
            [object Object]
        stack: >
            |-
              Error: render-tests/fill-extrusion-pattern/opacity-terrain
                  at Test.assert [as _assert] (http://localhost:7357/test/integration/dist/tape.js:10537:54)
                  at Test.bound [as _assert] (http://localhost:7357/test/integration/dist/tape.js:10358:32)
                  at Test.assert (http://localhost:7357/test/integration/dist/tape.js:10656:10)
                  at Test.bound [as ok] (http://localhost:7357/test/integration/dist/tape.js:10358:32)
                  at Test.runTest (http://localhost:7357/test/integration/dist/integration-test.js:150000:15)
            
        actual: >
            false
        expected: >
            true
        operator: >
            ok
        browser log: |
            LOG: not ok 2 render-tests/fill-extrusion-pattern/opacity-terrain
            LOG:   ---
            LOG:     operator: ok
            LOG:     expected: true
            LOG:     actual:   false
            LOG:     stack: |-
            LOG:       Error: render-tests/fill-extrusion-pattern/opacity-terrain
            LOG:           at Test.assert [as _assert] (http://localhost:7357/test/integration/dist/tape.js:10537:54)
            LOG:           at Test.bound [as _assert] (http://localhost:7357/test/integration/dist/tape.js:10358:32)
            LOG:           at Test.assert (http://localhost:7357/test/integration/dist/tape.js:10656:10)
            LOG:           at Test.bound [as ok] (http://localhost:7357/test/integration/dist/tape.js:10358:32)
            LOG:           at Test.runTest (http://localhost:7357/test/integration/dist/integration-test.js:150000:15)
            LOG:   ...
            LOG: 
    ...

1..2
```

Is enabling the browser console a must-have? In which situation do you find it useful?

**Comment by SnailBones** [comment]
> Is enabling the browser console a must-have? In which situation do you find it useful?

I have found it useful for debugging with `yarn watch-render`. I wouldn't call it a must have but I find browser logs to be easier to work with than logs in terminal.

**Comment by karimnaaji** [comment]
>I have found it useful for debugging with yarn watch-render. I wouldn't call it a must have but I find browser logs to be easier to work with than logs in terminal. Of course, I could always make the change locally.

Sounds good! If you find it useful I don't see a blocker if you find an easy way to fix the duplication of logs on failure.

**Comment by SnailBones** [comment]
I believe this can be fixed with a change of [testem reporter](https://github.com/testem/testem/blob/master/docs/custom_reporter.md). The quickest fix would be to switch to another one of the default options, or we can write a custom reporter. Is it important to maintain consistency besides removing the `browser log` field?

**Comment by karimnaaji** [comment]
>Is it important to maintain consistency besides removing the browser log field?

I don't think we're particularly attached to the current format, so as long as the output is clear and doesn't have redundant information I think we could use a custom reporter if you think that's the right way to go about this (For example, I could imagine only showing the stack, or what is really relevant to inspect and show when a render test has failed).

**Comment by SnailBones** [comment]
@arindam1993 just shared a simpler way: checking the environment variable in `handleConsoleMessage()` to print console logs only when calling watch-render. I'll push the update in a moment.

**Review by arindam1993 — APPROVED** [review]
Looks good to me

**Review by karimnaaji — APPROVED** [review]

**Pull request merged**
