### PR TITLE
Improve queryRenderedFeatures docs

### PR DESCRIPTION
**Pull request by lucaswoj**
ref https://github.com/mapbox/mapbox-gl-js/issues/2434#issuecomment-219238487

cc @jfirebaugh @gmaclennan @ansis

### CODE REVIEW

**Comment by gmaclennan** [comment]
Thanks! This would have saved some debugging time and trawling through issues.
You should probably mention that the geometry is also copied from the geoJSON too. It is, right?

**Comment by lucaswoj** [comment]
screen shot 2016-05-16 at 11 14 17 am

**Comment by gmaclennan** [comment]
Ah, thanks @lucaswoj - reading the diff I missed that. Makes sense to me.

**Comment by lucaswoj** [comment]
closed in favor of #2574

**Pull request closed without merging**
