### PR TITLE
Terrain render loop: Prioritize large batches and lazy framebuffer switches

### PR DESCRIPTION
**Pull request by karimnaaji**
Ports two different optimizations to the render cache from native.

- (1) In terrain render cache prioritize large render batches first, this prevents allocating pool entry to small layer groups, which eventually leads to more draw call when the render cache pool is fully used. In an example location this changed FPS from 44 to 55.
- (2) In the terrain render loop, prevent overly binding/clearing framebuffers when nothing was drawn in a render batch. Unnecessary binding/clears are expensive gl calls. The full stats are attached in the before/after below. In an example frame this reduced the number of framebuffer bindings from 228 to 88 and number of clears from 103 to 71. This prevents such sequence of unnecessary bindFramebuffer:

Screen Shot 2021-05-19 at 8 23 04 PM

<details>

**before/after (1)**

Screen Shot 2021-05-19 at 6 04 52 PM
Screen Shot 2021-05-19 at 6 04 03 PM

**before/after (2)**

Screen Shot 2021-05-21 at 2 06 24 PM
Screen Shot 2021-05-21 at 2 06 16 PM

</details>

- `<changelog>Improve terrain performance by reducing number of framebuffer switches during draping</changelog>`
- `<changelog>Improve terrain performance by prioritizing allocation of large render cache batches</changelog>`

### CODE REVIEW

**Comment by astojilj** [comment]
There seems to be an issue with symbols in `optimizeForTerrain: false` mode.

**Comment by karimnaaji** [comment]
Thanks for the catch, it was missing a reset to main framebuffer (fixed by https://github.com/mapbox/mapbox-gl-js/pull/10701/commits/995f819fba29f0963686907fae60cce372eb4c3b + assert in https://github.com/mapbox/mapbox-gl-js/pull/10701/commits/3c604bb77443f67a71da1e4b0099c820ecbd95a1)

**Review by astojilj — APPROVED** [review]
👍

**Review by rreusser — COMMENTED** [review]
Sorry I was slow on the review! I only had the tiniest nitpick and put most of my energy into working to understand the PR. I have a couple questions I'll follow up with after the fact.

**Pull request merged**
