### PR TITLE
Fix alpha blending of alpha layers

### PR DESCRIPTION
**Pull request by gribbet**
Fixes mapbox/mapbox-gl-js#1698

### CODE REVIEW

**Comment by lucaswoj** [comment]
This looks great! Thanks @gribbet!

Next steps:

 - [ ] Ensure this works across modern browsers
 - [ ] Ensure this does not cause any performance regressions
 - [ ] Add tests to [mapbox-gl-test-suite](https://github.com/mapbox/mapbox-gl-test-suite) 

cc @jfirebaugh @ansis @mourner

**Comment by gribbet** [comment]
Note another potential fix is to set the premultipliedAlpha setting to false during webgl context creation.

**Comment by jfirebaugh** [comment]
@gribbet Thanks for the contribution! Would you mind pasting into a comment here an example tile from your rasterized contour layer with alpha? Any tile, doesn't matter -- just something we can drop into https://github.com/mapbox/mapbox-gl-test-suite/tree/master/tiles to make sure this gets fixed and doesn't regress on either mapbox-gl-js or mapbox-gl-native.

**Comment by gribbet** [comment]
alpha-raster

**Comment by lucaswoj** [comment]
I think this is good to :ship: @jfirebaugh. 

`headless-gl` doesn't seem to support alpha blending (see https://github.com/mapbox/mapbox-gl-test-suite/issues/57). This prevents us from testing this functionality properly in the test suite.

**Comment by lucaswoj** [comment]
Closed in #1705 via 846aecbd9bad7ff088ccfb21163e3ae26c10f0bd

**Comment by lucaswoj** [comment]
Thanks @gribbet! :tada:

**Pull request closed without merging**
