### PR TITLE
Bump directions plugin

### PR DESCRIPTION
**Pull request by mollymerp**

### CODE REVIEW

**Comment by mollymerp** [comment]
Includes 2 versions due to a patch bump that happened before this was merged. ready for 👀 @lucaswoj @tristen

**Comment by tristen** [comment]
Not sure we need to include `v3.1.0` here if it's a broken version?

**Comment by mollymerp** [comment]
Yeah, happy to remove too. Wasn't sure if it was important to keep as a record or not, but guessing that #3947 will remove all of them anyways so that probably makes sense.

**Comment by mollymerp** [comment]
Deployed and manually tested the example page 👍

**Pull request merged**
