### PR TITLE
Update to shelf pack v2

### PR DESCRIPTION
**Pull request by bhousel**
I released shelf pack v2 today!  It includes reference counting, which will let us reuse parts of the glyph atlases (#141) and symbol atlases (#2164) that aren't used to render visible tiles.  This will keep the atlases from growing so big when rendering CJK labels and other interesting maps.

I haven't made the changes in the atlas code yet to support the new reference counting yet - so don't merge!

To better visualize what the atlases are doing, I made this cool debug page that will let us look at them:

glyph atlas debug

More coming soon!

### CODE REVIEW

**Comment by mourner** [comment]
Awesome! Some kind of weird blow up happened in one of the render tests but it seems unrelated so I'll try to rerun and see if it persists.

**Comment by mollymerp** [comment]
Niiiice 🎉  cc @xrwang @lbud @amyleew @nickidlugash

**Comment by bhousel** [comment]
Hoping to improve the debug page a bit today, then make the changes to reuse bins and record some before/after pics..

**Comment by xrwang** [comment]
\o/ This is fantastic, thank you for making the time to do this @bhousel !!

**Comment by bhousel** [comment]
glyph atlas debug2

**Comment by amyleew** [comment]
Nice @bhousel !!

**Comment by bhousel** [comment]
Just dropping an update here - 24ed82f does unref glyphs when a tile unloads, however this didn't improve the glyph atlas congestion as much as I had hoped because.. tiles don't really unload often..  The source cache holds on to them for a while.

So I'm going to look into more clever ways to update the glyph atlases so that they contain only glyphs on _visible_ tiles.

**Comment by lucaswoj** [comment]
I am closing this PR because it has been inactive for a long time. The branch isn't going anywhere so please keep working on this feature and re-open the PR when it is ready! 

Let me know if you have any questions.

**Pull request closed without merging**
