### PR TITLE
Move github files to .github/

### PR DESCRIPTION
**Pull request by tomscholz**
Moved the files `ISSUE_TEMPLATE.md`, `PULL_REQUEST_TEMPLATE.md` to `.github/`. These files are only valid on github and with the change, the root folder just seems to be a little bit more clean. Have fun

### CODE REVIEW

**Comment by jfirebaugh** [comment]
I don't mind one way or the other, but the directory name is misspelled in this PR (`.gtihub`).

**Comment by tomscholz** [comment]
oh boi. Did not see that. Sorry.

**Comment by tomscholz** [comment]
Fixed!

**Comment by anandthakker** [comment]
Thanks @tomscholz

**Pull request merged**
