### PR TITLE
Improve collision detection for labels along lines by switching to runtime evaluation of collision circle's pixelated radius

### PR DESCRIPTION
**Pull request by zmiao**
## Launch Checklist

Collision circles are used during collision detection for line labels. 
Previously collision circle's pixel radius was calculated in symbol layout time with a constant value. This patch moves the calculation into placement time, so the collision circle's radius would be more aligned with the text's size in different zoom levels, thus leading to a better collision detection behavior.

 - [x] briefly describe the changes in this PR
 - [ ] include before/after visuals or gifs if this PR includes visual changes
 - [ ] write tests for all new functionality
 - [x] post benchmark scores
 - [x] manually test the debug page
 - [x] tagged @mapbox/map-design-team @mapbox/static-apis if this PR includes style spec API or visual changes
 - [x] tagged @mapbox/gl-native if this PR includes shader changes or needs a native port
 - [x] apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog'
 - [x] add an entry inside this element for inclusion in the `mapbox-gl-js` changelog: `<changelog>Improve collision detection for labels along lines by switching to runtime evaluation of collision circle's pixelated radius</changelog>`

### CODE REVIEW

**Comment by zmiao** [comment]
Benchmark test result:
Screen Shot 2021-08-09 at 9 56 02 AM

**Review by mourner — APPROVED** [review]
This looks great! Nit: we should use PR titles and changelog descriptions in a way that describes user impact if possible, e.g. in this case I'd name it "Improve collision detection for labels along lines", because it's not clear what collision circle pixelated radius means for the end user.

**Comment by zmiao** [comment]
@mourner Thank you for the suggestion! I will update the title and changelog entry accordingly.

**Review by ansis — APPROVED** [review]
Looks great!

**Pull request merged**
