### PR TITLE
Added a setImage convenience method in ImageManager.js

### PR DESCRIPTION
**Pull request by ashishshroti14**
## Launch Checklist

Added setImage convenience method as highlighted in [#10941](https://github.com/mapbox/mapbox-gl-js/issues/10941)
I'm quite new and this is my first PR. I hope that solves the problem to some extent. 

 - [x] briefly describe the changes in this PR
 - [ ] include before/after visuals or gifs if this PR includes visual changes
 - [ ] write tests for all new functionality
 - [ ] document any changes to public APIs
 - [ ] post benchmark scores
 - [x] manually test the debug page
 - [ ] tagged `@mapbox/map-design-team` `@mapbox/static-apis` if this PR includes style spec API or visual changes
 - [ ] tagged `@mapbox/gl-native` if this PR includes shader changes or needs a native port
 - [ ] apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog'
 - [ ] add an entry inside this element for inclusion in the `mapbox-gl-js` changelog: `<changelog></changelog>`

### CODE REVIEW

**Review by SnailBones — CHANGES_REQUESTED** [review]
Thank you so much for your contribution @ashishshroti14!

The content looks good to me but I'm a bit concerned by all the syntactical changes. Perhaps you're using Prettier? This code uses ESLint and I expect your changes will fail the linting test. (Currently CI is failing for all external P.R.s but we should have that fixed soon!)

Would you be able to reduce the changes to just the new function and to test that the linter is passing by running `yarn run lint`?

I think this might need a test too, but if we can get that done I'd love to see it as a part of next week's release!

**Review by ryanhamley — COMMENTED** [review]
I think a `setImage` convenience method is probably worth adding but this implementation isn't correct. I'm somewhat inclined to close it, but if you want to take another shot at it @ashishshroti14 go ahead. Please turn off whatever formatter you're using first though, as @SnailBones noted.

**Comment by mbullington** [comment]
Hey @ashishshroti14 ! Thanks for taking a look at this ticket and contributing to GL JS !

As @ryanhamley mentioned this implementation needs reworking (for example `map` in my example refers to `map.js`, not D3). I'm on the Studio team so/how when this feature gets implemented is completely up to GL JS, but if you wanted to continue working on this I think the following steps would be a good start:

1. The `setImage` method needs added to `map.js`. I believe this would have the function signature `(id, image, opts)` but unclear? A decision would need to be made on if `opts` should be checked as part of this function.
2. The `setImage` method needs added to `style.js` and to be called in the same pattern as `addImage` and `updateImage`.
3. Unit tests for both files and making sure any related tests are updated.

**Comment by ashishshroti14** [comment]
Thank you @SnailBones @ryanhamley @mbullington for the guidance. I'll try to follow the above-mentioned steps and make the required changes.

**Comment by ansis** [comment]
Thanks for opening this. I'm going to close it for now. 

The problem pointed out by @mbullington is something we should try to address but I think it needs a bit more discussion. I'm not sure if we should do this by adding another API method or by changing one of the existing methods. Or if we should wait until we can deprecate the existing methods.

**Pull request closed without merging**
