### PR TITLE
documented style.load

### PR DESCRIPTION
**Pull request by Countdown369**

### CODE REVIEW

**Review by stepankuzmin — CHANGES_REQUESTED** [review]
The `style.load` event already exist on the `MapEvent` type here. Could you please remove the duplication and move the description and the example there?

https://github.com/mapbox/mapbox-gl-js/blob/2d61f885841ddfe33fb0aa5e404b4d22e792b637/src/ui/events.js#L1506-L1512

**Comment by Countdown369** [comment]
By the way, this is done in order to have complete documentation of code for this soon-to-be example: https://github.com/mapbox/mapbox-gl-js-docs/pull/843

...but, in doing this I've also noticed that `style.error`, `style.change`, `source.add`, `source.remove`, `source.load`, `source.error`, `source.change`, `tile.add`, `tile.remove`, `tile.load`, and `tile.error` events also exist in the same changelog update as `style.load`. Should these events be documented and made public along with `style.load`, or just kept as is?

**Comment by stepankuzmin** [comment]
> …also exist in the same changelog update as `style.load`

Do you mean these events would be available in the GL JS docs despite being marked as `@private`?

**Review by chriswhong — CHANGES_REQUESTED** [review]
We can't just PR changes to these files, they are autogenerated from the source code.  This will require a PR to `mapbox-gl-js` first, then an update to the docs.

EDIT: disregard, I wasn't sure what I was looking at here.  I defer to @stepankuzmin who will know the right place to make these changes.

**Comment by Countdown369** [comment]
No, I mean to say that they would no longer be marked private; this is what I did with `style.load` so that it does appear in documentation (i.e. https://docs.mapbox.com/mapbox-gl-js/api/map/#map-events). But if they should be kept private, I won't touch them.

Separately, any idea why the Camera unit test is failing when I haven't edited anything that (I can tell) is directly related to the camera?

**Comment by Countdown369** [comment]
> This will require a PR to `mapbox-gl-js` first, then an update to the docs.

@chriswhong This PR we are in now is in `mapbox-gl-js`; I intend to merge this before https://github.com/mapbox/mapbox-gl-js-docs/pull/843.

**Comment by stepankuzmin** [comment]
> why the Camera unit test is failing

It looks like flakiness. We can re-run the unit test for that.

**Comment by stepankuzmin** [comment]
@Countdown369 we should keep these events private and only expose `style.load`

**Comment by Countdown369** [comment]
Could @stepankuzmin or @chriswhong rerun the unit test? I don't have permissions 🗿

**Review by stepankuzmin — APPROVED** [review]

**Review by chriswhong — APPROVED** [review]

**Comment by stevage** [comment]
Fwiw, the wording "base style" is confusing and misleading to me. Afaik "base style" isn't a term used elsewhere so I thought it must have meant only the first time a style is loaded, not subsequent style manipulations.

**Comment by stepankuzmin** [comment]
@stevage, good catch!

@Countdown369, could you please update the wording removing the mention of "base" and mentioning that this event would also be triggered on the subsequent `setStyle` calls?

**Pull request merged**
