### PR TITLE
Add optional visualizePitch option for NavigationControl and add touch support for pitching with compass icon

### LINKED ISSUE #3405: add mobile gesture handling for pitch
We need gesture support on mobile web to allow the map to be pitched. The way this works gesturally on native mobile is two fingers swiped up or down, both in parallel with each other and approximately the same y-value. 

Without this, there isn't a way to pitch on mobile without an external control button or similar that toggles between pitch values a là `View elevation profile` in https://www.mapbox.com/blog/dc-bikeshare-revisited/. 

Related: https://github.com/mapbox/mapbox-gl-js/issues/2449

### LINKED ISSUE #8208: Tilting compass as map tilted
## Motivation
When you rotate a map, compass on the navigation control rotates as much as the degree map rotated. but when you tilt the map, the compass doesn't interact for the pitch.

Also, when you click the compass, it makes the map degree to 0 as its default value but pitch would never be back to default even when you click the compass again.

I think when it interacts with both its bearing and pitch, will give better UX.
Implementation would look like(drag mouse on the MAP labeled element, and see compass below. and click the compass):
https://jsfiddle.net/cs09g/5an14p6r/

### PR DESCRIPTION
**Pull request by pakastin**
Reverting #8226, the revert of #8281 😄

Fixes #8208. Related: #3405

### CODE REVIEW

**Comment by pakastin** [comment]
Again, you can try out the feature here: https://aviamaps.com/map

**Comment by pakastin** [comment]
Oh sorry, I’ve never used Flow. I’ll study how to run it.

**Comment by pakastin** [comment]
All tests passing now and working perfectly: https://aviamaps.com/map

**Comment by mourner** [comment]
@pakastin this PR shouldn't close #3405 because that one is about mobile gesture on the map (two-finger pan to pitch like in native map apps), and this PR only targets the compass icon.

**Comment by pakastin** [comment]
Oh ok, you seem to already changed that 👍

**Comment by pakastin** [comment]
Ready to merge? :)

**Comment by andrewharvey** [comment]
I took a quick review and I can't see any issues, testing it out seemed to work very well.

In the future when #3731 lands I think we'll want to add a limit to how much the icon will pitch.

**Comment by pakastin** [comment]
Ok, so ready to merge? 🙂

**Comment by andrewharvey** [comment]
> Ok, so ready to merge? slightly_smiling_face

I'll leave it to Mapbox to make that call, but as far as my testing went, it looks good.

**Comment by mourner** [comment]
@pakastin thank you for your patience! This will get into v1.2.0 later this month.

**Comment by pakastin** [comment]
Ok great! Just waiting to get rid of the custom build hassle. 👍
Aviamaps now has custom build with v1.1.0 + this update working: https://aviamaps.com/map

**Pull request merged**
