### PR TITLE
feat: send geolocation as adapter

### PR DESCRIPTION
**Pull request by behnammodi**
- This PR can help developers to customize `geolocation` behavior.
 - We don't have any visual changes.
 - All test cases compatible with these changes.
 - I need your opinion and then add a document.
 
 So now we have:
 ```js
 const myGeolocation: Geolocation = {
    clearWatch: ...,
    getCurrentPosition: ...,
    watchPosition: ...,
};
 
 const geolocateControl = new GeolocateControl({
    geolocation: myGeolocation,
});

map.addControl(geolocateControl);
 ```
 
 I'll say welcome to your awesome feedback :)

### CODE REVIEW

**Comment by andrewharvey** [comment]
What's the motivation or use case for this? Isn't window.navigator.geolocation really the only geolocation provider? How else would it be provided if not window.navigator.geolocation?

**Comment by behnammodi** [comment]
@andrewharvey You're right but this PR related to https://github.com/mapbox/mapbox-gl-js/pull/10234#issuecomment-749244302, with this PR we can override the geolocation function.

for example, we want to show a popup UI before getting used location or ignore some coordinates

**Comment by behnammodi** [comment]
@andrewharvey Also imagine we going to enhance user location by their behavior and we don't want to **relying** on native geolocation.

**Comment by ImanMh** [comment]
> What's the motivation or use case for this? Isn't window.navigator.geolocation really the only geolocation provider? How else would it be provided if not window.navigator.geolocation?

Same issue here, I want to build a PWA wrapped in a native app. In this case I prefer native app to provide GPS coordinates but with this implementation mapbox goes directly to the browser APIs.

**Comment by behnammodi** [comment]
@ImanMh Thanks, It's an awesome use case

**Comment by behnammodi** [comment]
@andrewharvey what is your opinion?

**Comment by ansis** [comment]
@mourner this looks good to me. Thoughts?

**Comment by behnammodi** [comment]
@mourner @ansis @andrewharvey Hi there, do you have any updates?

**Comment by mourner** [comment]
@behnammodi this looks good to me too! Needs a rebase so that the CI tests pass before we can merge.

**Comment by behnammodi** [comment]
@mourner It's good news 🙏🏻, so we need a rebase by me or somebody else?

**Comment by asheemmamoowala** [comment]
> so we need a rebase by me or somebody else?

@behnammodi it's best if you can rebase and verify the changes locally before merging the changes.

**Comment by behnammodi** [comment]
@asheemmamoowala All right, I will do it

**Comment by behnammodi** [comment]
@asheemmamoowala I did it, but I need someone to help me for 4 failed stage

**Comment by karimnaaji** [comment]
@behnammodi , I rebased your branch off of main in https://github.com/mapbox/mapbox-gl-js/tree/karim/behnammodi-pr10232-rebased.

The CI job did not pass on unit tests and build (render tests failure is unrelated), https://app.circleci.com/pipelines/github/mapbox/mapbox-gl-js/5920/workflows/4ebe7ae1-c43f-425e-bbcc-2e62cf6c29d0.

```
git remote add upstream git@github.com:mapbox/mapbox-gl-js
git fetch upstream
git checkout upstream/karim/behnammodi-pr10232-rebased
git checkout -b geolocation-as-adapter-rebased
git push origin main
```

And then open up a new PR so the discussion can continue on a clean diff? We'll close this PR then.

**Comment by behnammodi** [comment]
@karimnaaji Thank you for your help, I did it https://github.com/mapbox/mapbox-gl-js/pull/10400

**Comment by karimnaaji** [comment]
@behnammodi Sounds good, thanks the diff look more approachable now! Closing this PR and I'll tag whoever was involved in reviewing this one there.

**Pull request closed without merging**
