### PR TITLE
Fix featuresAt for non-4096 vector sources

### LINKED ISSUE #1529: Strange featuresAt behavior
Apologies for the incredibly vague subject line.

The problem: using a source of US county boundaries made with `tippecanoe`, featuresAt returns empty most of the time, and when it doesn't, it's significantly offset from the passed-in point.  

Reproduction here: http://bl.ocks.org/anandthakker/67ff3076df1235c3be44.  Put your mouse in western Maryland and look in North Carolina.

featureat

### PR DESCRIPTION
**Pull request by mourner**
Closes #1529 and #1383. @jfirebaugh to review.

### CODE REVIEW

**Comment by mourner** [comment]
There are a few other broken places with 4096 hardcoded (specifically circle and symbol buckets), but that would be a subject for a separate PR.

**Comment by jfirebaugh** [comment]
Changes look good but because this is not in any common manual-testing paths it stands a high chance of regressing unless we add automated tests.

**Comment by mourner** [comment]
@jfirebaugh can we reference external vector sources like the one in the issue in tests? Without this, it would be tough to test since this needs an integration test rather than a unit test.

**Comment by tmcw** [comment]
This should also close #1383

**Comment by tmcw** [comment]
Whoops, accidental double-close :hamster:

**Comment by mourner** [comment]
Wow, actually I didn't touch the reopen button. I guess it's some sort of waffle race condition.

**Comment by jfirebaugh** [comment]
Could you check in a pbf with custom extent into `test/fixtures` and run against that? We have one tile pbf in there already.

Long term, especially once gl-native gets a featuresAt/featuresIn equivalent, I see us adding "querying" tests along side the rendering tests in https://github.com/mapbox/mapbox-gl-test-suite.

**Comment by mcwhittemore** [comment]
@mourner I have an example that breaks at different zoom levels if that would help you. Its using a dataset from tippecanoe.

**Comment by mourner** [comment]
@jfirebaugh I replaced the vector url with a local test fixture but had to mock ajax requests to fixtures with `fs.readFile` in `/util/ajax.js`. It only gets used for tests so I think this is fine. So should be good to go.

**Comment by jfirebaugh** [comment]
@mourner I pulled your test case into mapbox-gl-test-suite as the first test case in a new suite of "query" tests: https://github.com/mapbox/mapbox-gl-test-suite/pull/46. Implementation in mapbox-gl-js [here](https://github.com/mapbox/mapbox-gl-js/compare/fix-features-at...query-test-suite).

At the moment this can only be run on gl-js, because native lacks `featuresAt`/`featuresIn`, but the idea is it could serve the same purpose as the rendering tests but for VT queries.

WDYT?

**Comment by mourner** [comment]
@jfirebaugh LGTM, feel free to merge with your version of tests.

**Comment by jfirebaugh** [comment]
Committed as 768dd693ea03b20cc5acef546bc946a38f487227, tests in f9ba9db29e4511d2fa1714a71c07292309d01e59.

**Pull request closed without merging**
