### PR TITLE
Consolidate common code in featuresAt, featuresIn

### LINKED ISSUE #1747: featuresIn layer filter not working
I want the featuresIn for just one layer, but it does not work so far..., a fiddle:
https://jsfiddle.net/musicformellons/Lqdq31Lf/
```
map.on('load', function() {
	map.featuresIn( {layer: 'markersgreen'},
            function(err, features) {
                if (err) throw err;
                alert(JSON.stringify(features));
            });
        });
```
Although only markersgreen are requested, featuresIn returns both markersgreen and markersblue. BTW it works for the featuresAt in the fiddle as hovering just activates for the markersgreen.

An additional thing that puzzles me: As it seems no filter on layers is applied in my fiddle, I would expect to also get returned the features of the Mapbox Street-v8 map layers, so why do I not get these as well?

### PR DESCRIPTION
**Pull request by anandthakker**
Fixes #1747

@jfirebaugh: :eyes: Something like this seems the least invasive way to do this refactor, but it would also be possible to do it in `Source` (removing `featuresIn` and `featuresAt` in favor of a single `queryFeatures`).  Preference?

### CODE REVIEW

**Comment by jfirebaugh** [comment]
Yeah, this looks good. I was going to say push it through to `Source` too but the code would immediately branch on the query type there anyway.

**Comment by anandthakker** [comment]
:+1: 

@jfirebaugh Question: what's the purpose of [mocking Source.featuresAt in this set of tests](https://github.com/mapbox/mapbox-gl-js/blob/fb54d903266737ace49c901299af05db7d5d45b0/test/js/style/style.test.js#L871-L901)?   If I'm reading this right, having this function mocked here means that the subsequent tests are really just testing that `Style.featuresAt`: (a) formats `params.layerIds`, (b) calls `layer.json()` and sets it as `feature.layer` for each feature.  (In particular, testing for paint and layout properties seems like it's more a test of `layer.json()` than `featuresAt`.)

**Comment by jfirebaugh** [comment]
It's a unit test, so it's mocking its dependency on `Source#featuresAt`. You're correct that it's testing (a) and (b), though you've phrased (b) in terms of implementation details, while the test descriptions are phrased in terms of the desired postconditions.

I purposefully avoided writing unmocked tests here because a working `Source#featuresAt` would require tile loading, workers, etc. But we _have_ started full integration tests for queries [over in mapbox-gl-test-suite](https://github.com/mapbox/mapbox-gl-test-suite/pull/46) -- expanding those would be most welcome.

**Comment by anandthakker** [comment]
@jfirebaugh Ah--understood, thanks for explaining.  So is the best way to align w the testing strategy here for me to add analogous tests to these for `featuresIn`?

**Comment by anandthakker** [comment]
^ or... would it make more sense to mock `featuresIn` using exactly the same function, and then programmatically run each of the `featuresAt` unit tests on both?

**Comment by anandthakker** [comment]
@jfirebaugh :eyes: I did the latter.  It's a little weird, but it does run both `featuresAt` and `featuresIn` through all those unit tests...  Let me know if you want this to look different; otherwise, I think it's good to go.

**Comment by lucaswoj** [comment]
@anandthakker FWIW, we do some integration tests on `featuresIn` / `featuresAt` in `[mapbox-gl-test-suite](https://github.com/mapbox/mapbox-gl-test-suite)`

**Comment by jfirebaugh** [comment]
Looks good, thanks! Merged in 8790173654240bf8d006b8f4dd27da063f0506a8, 79721abff5e78fc1f57089f7d1125501a27f47dc, and 2665c4a5afa3733d5296949396ee5f8612947cb9.

**Pull request closed without merging**
