### PR TITLE
Adds a queryTerrainElevation example to API doc

### PR DESCRIPTION
**Pull request by domlet**
## Launch Checklist

- Adds a queryTerrainElevation example to API doc

 - [x] briefly describe the changes in this PR
 - [x] apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog'

### CODE REVIEW

**Review by karimnaaji — APPROVED** [review]
👍  we can also add a reference example to this one https://docs.mapbox.com/mapbox-gl-js/example/add-fog/ for the `setFog` API.

**Comment by domlet** [comment]
> 👍 we can also add a reference example to this one https://docs.mapbox.com/mapbox-gl-js/example/add-fog/ for the setFog API.

Love it. Added in cbb8134ec – look good? @karimnaaji

**Review by HeyStenson — APPROVED** [review]
✨

**Comment by karimnaaji** [comment]
Thanks @domlet . Merging.

**Pull request merged**
