### PR TITLE
Remove try/catch in actor.postMessage

### PR DESCRIPTION
**Pull request by mourner**
Makes actor.postMessage optimizable by V8 and also makes sure we see any errors thrown on postMessage. Not tested in IE yet.

- [x] actually test on IE!

### CODE REVIEW

**Comment by mourner** [comment]
This is also the reason why we didn't notice broken transferables after buffer refactoring: https://github.com/mapbox/mapbox-gl-js/commit/7e9ff516a917c2b029c4d5b7ca8e7e5303b7abc9

**Comment by jfirebaugh** [comment]
Well, WTF... I am now testing on IE11 and unable to reproduce any issue with Worker.postMessage and transferables. Using the same [test case that I tried earlier](https://gist.github.com/calvinmetcalf/5495466#gistcomment-1337192), IE 11.0.9600.17801 prints "postMessage with array transfer 0".

I'm not sure if MS patched this or what.

**Comment by mourner** [comment]
Wow. So apparently it does support transferring at least one object? Also, is the Win version the same?

**Comment by mourner** [comment]
@jfirebaugh OK I'm now trying to recall a conversation about IE11 transferable objects with a friend — as far as I remember, IE11 doesn't support transferable array buffers and the second argument, and it's there for a different purpose — for an array of MessagePort objects, whatever that means.

**Comment by jfirebaugh** [comment]
@mourner that's what I thought too, but testing is telling me otherwise.
Can you replicate?

**Comment by mourner** [comment]
@jfirebaugh don't have a Windows machine handy atm.

**Comment by mourner** [comment]
Summoning @danzel here who did the original IE11 PR, any thoughts?

**Comment by danzel** [comment]
Uh yeah this is weird. MS have been known to patch things in IE11 occasionally though.

The only notes on the original issue I have are here:
https://github.com/mapbox/mapbox-gl-js/issues/95#issuecomment-47508314

But it looks like it doesn't cause an error any more from my limited testing, so yay? :)


The MS docs on this are a bit trash for this:
https://msdn.microsoft.com/en-us/library/hh673568(v=vs.85).aspx
Clicking 'postMessage' on here links to the window.postMessage docs, they don't have a set for webWorker.postMessage.

**Comment by lucaswoj** [comment]
@mourner @jfirebaugh Do we still want to pursue these changes?

**Comment by mourner** [comment]
@lucaswoj I don't know, IE is a weird beast.

**Comment by lucaswoj** [comment]
As far as I can tell, all the `postMessage` quirks discussed in this thread apply to IE10 but not IE11. We only need to support IE11+. 

I'm testing this branch on our Windows machine now and everything looks good!

Anything else you'd like to see before :ship: this @mourner @jfirebaugh?

**Comment by jfirebaugh** [comment]
Nope. If it works, :shipit:.

**Pull request merged**
