### PR TITLE
Efficiently apply style changes

### PR DESCRIPTION
**Pull request by scothis**
This PR contains five discreet commits:
- Throw on style mutation before load
- Track the stylesheet as a pure JSON object
- Batch mode for efficiently mutating Style instances
- Utility to diff stylesheets
- Use styleDiff to apply setStyle changes incrementally

Issue: #1341

### CODE REVIEW

**Comment by jfirebaugh** [comment]
I really like this API:

```
    style.batch(function() {
        style.addLayer(layer1);
        style.addLayer(layer2);
        ...
        style.addLayer(layerN);
    });
```

The parts I'm concerned about with this PR as it stands are twofold:

* We should reduce the complexity in `Style` by inverting the relationship between `style.batch` and the non-batched mutation methods. That is, make the non-batched mutation methods simple wrappers around `style.batch`. And instead of temporarily overwriting selected style methods within `style.batch`, pass a helper object to the work function:

  ```
    style.batch(function(batch) {
        batch.addLayer(layer1);
        batch.addLayer(layer2);
        ...
        batch.addLayer(layerN);
    });
  ```

 And then:

  ```
  Style.prototype.addLayer = function(layer) {
      this.batch(function(batch) {
          batch.addLayer(layer);
      }
  };

  // etc for removeLayer, ...
  ```
* A diffing `setStyle` requires two representations of the stylesheet to be kept in sync: the pure JSON representation and the internal representation. This adds complexity, and moreover, whenever you try to keep keep two representations in sync, it's virtually inevitable that you will miss some case and they will end up not in sync. We need to find a way to have a single representation.
  * Eliminate the internal representation: calculate everything on the fly from the pure JSON representation. Probably not feasible.
  * Eliminate the pure JSON representation, and introduce the constraint that you can use _either_ the built-in style mutation APIs (including `style.batch`), or diffing `setStyle`, but _not both_. This is obviously a pretty big API gotcha. To make it more palatable, we could consider moving style-diff to an external module, have the default `setStyle` be non-diffing, and present `style.batch` as the only built-in method for making batched changes.

**Comment by scothis** [comment]
I agree around keeping two models in sync. I was worried the rich objects would introduce noise into the diff. I'll play around with generating a plain object model from the rich objects to see how feasible it is.

Inverting the mutation methods to leverage the batch is interesting. It would end up being more code, but should be cleaner. I'll play with it.

**Comment by scothis** [comment]
Exporting the json stylesheet from a rich object is mostly possible, however, it will create significant noise in the diff. Layout and paint layer properties are particularly tricky as they don't distinguish between explicit, default and constant values.

It's worth cleaning up, but will take a good chunk of effort. Should creating a unified model block this work?

**Comment by jfirebaugh** [comment]
Let's take the "throw on style mutation before load" and `style.batch` changes but not do diffing `setStyle` just yet.

**Comment by jfirebaugh** [comment]
Closing -- let's revisit diffing `setStyle` once the constants situation in v8 resolves. That may make it easier to generate JSON from internal objects.

**Pull request closed without merging**
