### PR TITLE
cherry-pick #12201: Marker terrain occluded opacity

### PR DESCRIPTION
**Pull request by karimnaaji**
Cherry-pick PR https://github.com/mapbox/mapbox-gl-js/pull/12201 from @jacadzaca for minor review fixes and CI: including renaming of public API + unit tests.

Fixes https://github.com/mapbox/mapbox-gl-js/issues/12123

## Launch Checklist

 - [x] briefly describe the changes in this PR
 - [x] write tests for all new functionality
 - [x] document any changes to public APIs
 - [x] manually test the debug page
 - [x] apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog'
 - [x] add an entry inside this element for inclusion in the `mapbox-gl-js` changelog: `<changelog>Allow to override marker opacity when occluded by terrain (h/t [jacadzaca](https://github.com/jacadzaca))</changelog>`

### CODE REVIEW

**Review by stepankuzmin — APPROVED** [review]
This looks good to me 👍

**Comment by jacadzaca** [comment]
Merging this entails solving #12123, but the issue's not linked.

**Comment by karimnaaji** [comment]
This only affects markers set via map (via [marker.addTo](https://docs.mapbox.com/mapbox-gl-js/api/markers/#marker#addto)). I think what you might be referring to are symbols? In that case there's no current way to adjust the opacity of occluded symbols. If that's something that might be useful to you, could you please open a feature request with the described use case?

Otherwise the documentation for this feature is here: https://docs.mapbox.com/mapbox-gl-js/api/markers/#marker#setoccludedopacity and https://docs.mapbox.com/mapbox-gl-js/api/markers/#marker-parameters.

**Comment by slavanga** [comment]
Thanks for your swift reply.
Yes, I was referring to markers added as symbols and will open a feature request.

**Pull request merged**
