### PR TITLE
Fix #1101 Support unicode range 65280-65535

### LINKED ISSUE #1101: Glyph range truncated a bit short
Same issue as mapbox/mapbox-gl-native/issues/931.

The glyph range is being truncated at [`65280`](https://github.com/mapbox/mapbox-gl-js/blob/241a07d0607447cbc393f2ccfab3f03e765ced13/js/symbol/glyph_source.js#L83) and [`65533`](https://github.com/mapbox/mapbox-gl-js/blob/241a07d0607447cbc393f2ccfab3f03e765ced13/js/symbol/resolve_text.js#L32), while the actual unicode block extends to `65535`. This has been fixed in fontstack (mapbox/node-fontnik/issues/71) and will be a simple fix here in JS.

This bug results in characters in that range not being displayed, [as you can see here](https://friedbunny.github.io/mapbox-gl-style-dark/example.html#16.35/36.45125/-222.74102). The text should read `国道４１号`, but `４１` is missing (while `41` is fine).

screen shot 2015-03-17 at 11 55 13 pm

### PR DESCRIPTION
**Pull request by friedbunny**
Fixes #1101.

I changed the test to check for support of this range (rather than if characters beyond the range are excluded) because the entire basic range is now supported. 

`charCodeAt()` [will always return <= 65535](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/charCodeAt), so that check shouldn't be necessary now. If there needs to be a check for codepoints > 0x10000 (like emoji), that'll have to be done some other way.

### CODE REVIEW

**Comment by ansis** [comment]
thanks!

**Comment by mikemorris** [comment]
I think we'll actually still want that `charCodeAt` check, so that we don't end up with `NaN` values in the `codepoints` array. Rest look good!

**Comment by ansis** [comment]
@mikemorris I think since since the index we call it with is always within the string it should never return NaN

> charCodeAt() returns NaN if the given index is not greater than 0 or is greater than the length of the string.

**Comment by mikemorris** [comment]
Was looking for a > `0x10000` character to test with, but I think you're right @ansis, although above 65535 `charCodeAt` will return surrogate pairs that we don't support though?

**Comment by ansis** [comment]
@mikemorris I opened a new issue https://github.com/mapbox/mapbox-gl-js/issues/1110. It seems like they are uncommon and that it would fail without throwing an error so it's probably not that important.

**Pull request merged**
