### PR TITLE
Add property functions for circle-opacity and circle-blur

### PR DESCRIPTION
**Pull request by lucaswoj**
This pull request adds support for property functions for circle-opacity and circle-blur 

ref https://github.com/mapbox/mapbox-gl-test-suite/pull/101
ref https://github.com/mapbox/mapbox-gl-shaders/pull/14

cc @mollymerp @lbud @jfirebaugh @mourner @ericfischer

### CODE REVIEW

**Comment by lucaswoj** [comment]
I seem to be getting some fun rendering artifacts in headless-gl

image

**Comment by jfirebaugh** [comment]
We saw that seam previously in #1702.

**Comment by lucaswoj** [comment]
@jfirebaugh Yes, it looks very similar. Interestingly I am unable to repro in the browser OR when running headless-gl locally.

**Comment by lucaswoj** [comment]
@jfirebaugh I'm not sure what we can do other than ignoring the failing tests (or increasing the "allowed" diff). 🚢 ?

**Comment by jfirebaugh** [comment]
🚢

**Pull request merged**
