### PR TITLE
Rename "Overlay" to "ElementMarker"

### PR DESCRIPTION
**Pull request by lucaswoj**
How do you feel about this rename @mourner? I’m ready to :ship: if you feel happy with it. 

cc @mourner @1ec5 @jfirebaugh

### CODE REVIEW

**Comment by bhousel** [comment]
Can we please only use names like `DOMSomething` to refer to an actual `DOM` interface or object?   This is a well established naming convention.

**Comment by 1ec5** [comment]
If the idea is to emphasize that these markers can contain arbitrary HTML elements, then how about `MarkerElement`?

**Comment by lucaswoj** [comment]
> Can we please only use names like `DOMSomething` to refer to an actual `DOM` interface or object?   This is a well established naming convention.

Good point. This wasn't on my radar.

> If the idea is to emphasize that these markers can contain arbitrary HTML elements, then how about `MarkerElement`?

Per Slack chat, I like `ElementMarker`. New commit coming.

**Comment by lucaswoj** [comment]
🚢 on 🍏!

**Pull request merged**
