### PR TITLE
Cache local glyphs

### PR DESCRIPTION
**Pull request by ChrisLoer**
Generating local glyphs is a significant portion of startup time for CJK-heavy maps, and has gotten even more expensive with the introduction of high resolution SDFs (#10298). This PR looks to significantly reduce that cost for every map load _after the first_ by caching locally generated glyphs. The current approach is to store them using the IndexedDB interface, which has a few nice properties:

- Serialization is simple and seems fairly fast, using the structured cloning algorithm
- The overhead to doing a single insert is not high, so we can just cache glyphs as we generate them, without worrying about how to batch up write operations.

Earlier drafts used the CacheStorage API used by `TileRequestCache`, but it wasn't the best fit because:

- HTTP-based interface is awkward when there aren't any actual HTTP requests
- Had to write our own serialization (although we have the glyph PBF format handy already, so this wasn't too big a problem)
- CacheStorage is not geared towards lots of small requests, so to get good results we had to batch lots of glyphs together, but then that makes "add one more glyph to the store" a lot more complicated.

My performance testing consisted primarily of reloading a glyph-heavy Tokyo scene and measuring the time to "all tiles loaded". For the scene/style I tested, load time across 5 runs went from 2571ms to 2032ms. Looking at these runs in the profiler, it looks like the ~550ms improvement comes from eliminating ~650ms in TinySDF time, and then adding back ~100ms in cache-fetching.

The cache starts loading as soon as the `GlyphManager` is constructed, and in my test runs it was always fully loaded before the first `getGlyphs` request arrived. To test the "wait for cache to load" code path, I inserted an artificial delay and made sure everything loaded quickly as soon as the artificial delay passed, but I didn't do any methodical performance testing of that pathway.

There's one annoying potential problem I haven't addressed -- what if the installed fonts change between runs? It would be possible to have a map mixing glyphs from the old and new fonts. This would probably not be super common, but when it happened it would be ugly and probably hard for most people to figure out what was happening. We could potentially do something like periodically "checking" glyphs against what we have in the cache, and if we find a discrepancy we clear the cache and start over (as we do when the "local font family" changes).

Another concern I have is that on the _very first_ load of a map, when nothing's in the cache, there's some extra overhead from caching the glyphs as we generate them. Ideally we should get this overhead as close to zero as possible, since "time to very first load" is such an important metric.

I haven't flow-ified or written tests for this functionality yet. I'm hopeful that this will allow us to check in local glyph caches as a test fixture so that our automated tests can actually cover local glyphs.

I'm going to start working on tests, but I wanted to get this PR up for feedback on the approach.

## Launch Checklist

 - [x] briefly describe the changes in this PR
 - [ ] include before/after visuals or gifs if this PR includes visual changes
 - [ ] write tests for all new functionality
 - [ ] document any changes to public APIs
 - [ ] post benchmark scores
 - [x] manually test the debug page
 - [ ] tagged `@mapbox/map-design-team` `@mapbox/static-apis` if this PR includes style spec API or visual changes
 - [ ] tagged `@mapbox/gl-native` if this PR includes shader changes or needs a native port
 - [ ] apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog'
 - [ ] add an entry inside this element for inclusion in the `mapbox-gl-js` changelog: `<changelog></changelog>`

cc @ansis @asheemmamoowala @mourner @zmiao @tmpsantos @tsuz

### CODE REVIEW

**Comment by ChrisLoer** [comment]
One other note: loading just the Tokyo scene in my test required 969 glyphs (at about 2MB of storage), but panning around through several major cities at different zoom levels got the cache up to a bit over 3000 glyphs (at around 7MB of storage). We could try to trim the cache size by expiring rarely used glyphs, but my impression is that rare glyphs are not going to be taking up too much of the space, and it'll be better to err on the side of keeping glyphs in the cache -- once we get to that ~3000 glyph range, I expect that we can load just about any scene without requiring more than a handful of new glyphs to be generated.

**Comment by ChrisLoer** [comment]
I fixed up flow/lint errors and wrote a very basic unit test. Unfortunately, `window.indexedDB` isn't super friendly to stubbing. I spent some time looking at using `level-js` to implement an IndexedDB cache that could be checked in and used by the test suite... but I backed off because:

- It wouldn't directly test the code using `window.indexedDB`
- It would only exercise cache read logic
- Render test results using the cache wouldn't really be that interesting because they wouldn't actually be exercising the TinySDF pathway

**Comment by ChrisLoer** [comment]
After further testing today, I think further changes are necessary. I wasn't thinking through what happens when multiple maps are sharing the same cache.

1) The current implementation nukes the glyph store whenever the font family changes, but that means two maps with two different font families will continually be nuking each other's cache. I'm not sure how common it would be to have maps with different local font families running on the same website, but it's certainly possible. I think probably we should have one object store per font family, but cache expiration probably starts to get more important if we're potentially piling up multiple families worth of glyphs.

2) Activity in one tab can block another tab. This doesn't sound so bad, since even our expensive operation (the full cache read) takes a fraction of a second, and most of the time we don't have any transactions open at all. But playing around with the version upgrade logic scared me. If you try to open a database with a version bump and it's open with the old version in another tab, you get an `onblocked` event fired. Fair enough -- but then subsequent attempts to open the database hang without firing any events at all, even if you reload the page or open a new tab. In Chrome the developer tool IndexedDB inspector will start hanging as well. The exact behavior is different between Chrome/Firefox/Safari (e.g. do all DB open calls hang, or just calls that require an upgrade), but in none of them can you count on getting a signal fired every time you try to open the database. You can play around with this with code like:

```
const open1 = window.indexedDB.open(CACHE_NAME,1);
open1.onsuccess = () => {
    console.log("Opened DB once.");
    const open2 = window.indexedDB.open(CACHE_NAME,2);
    open2.onblocked = event => {
        console.log("Couldn't open when a version upgrade was required.");
        const open3 = window.indexedDB.open(CACHE_NAME,2);
        open3.onblocked = () => {
            console.log("Never reached");
        };
```

We don't actually need to do DB version upgrades yet, and if we had to in the future, we could find some way to work around this. But the fact that it was so easy to introduce a map hang makes me nervous.

It looks like the [IndexedDB spec](https://w3c.github.io/IndexedDB/#introduction) addresses this situation by saying other users should listen for a `versionchange` event and disconnect from the DB whenever someone wants to do an upgrade. I guess that's fair, although their "Example 2" has a pretty fragile-looking solution:

```
request.onblocked = function() {
  // Give the other clients time to save data asynchronously.
  blockedTimeout = setTimeout(function() {
    displayMessage("Upgrade blocked - Please close other tabs displaying this site.");
  }, 1000);
};
```

**Comment by ChrisLoer** [comment]
I pushed a change that addresses the block-on-upgrade behavior. It's a little bit weird to test for because I exercise it with fake upgrades... but I think I'm approaching it the way the spec suggests and it seems to work.

Does anyone have input on how to handle to maps running on the same server with different font families? I'm leaning towards just throwing the font family into the cache key to avoid collisions. Then to do expiration, I'm thinking:

- Write a "last access time" to the DB for each glyph the first time it's accessed
- Maintain an [IDBIndex](https://developer.mozilla.org/en-US/docs/Web/API/IDBIndex) based on last access time
- Sometime after load completes (or periodically?) check if the glyph count is over a cache size limit. If so, iterate through the last access time index starting from the oldest glyphs and start deleting. Maybe remove from the in-memory cache as well (to save some memory and also make sure if the glyph _does_ get used in this session it gets re-added to the cache).

So this approach adds a little extra cost in that a DB update is required for every glyph on every load, but it can be done at our leisure (e.g. on an idle callback).

**Comment by ChrisLoer** [comment]
I've implemented an LRU cache limit along the lines I was considering above. I also made a change to batch DB writes into larger transactions, which turned out to make them considerably faster (although I wasn't focusing on write speed in my benchmarks since it doesn't affect initial load time).

Here are my latest benching results for five loads of `15.4/35.675906/139.764176/-22.7` with a 1391x1137 viewport. This time I tested across Firefox/Safari/Chrome:


Firefox diff (ms) | Safari diff (ms) | Chrome diff (ms)
-- | -- | --
-3256.4 | -618.4 | -461.4


Firefox improvement | Safari improvement | Chrome improvement
-- | -- | --
227.87% | 123.73% | 119.45%


Standard deviations are between 100-150ms.

The improvement in Chrome is a little smaller than what I saw before in both absolute ms and percentage improvement (460ms vs 550ms, 19% improvement vs 26% improvement). I want to poke into that a little more to see if it's just from using a different viewport size, some other changing part of the environment, noise -- or something that regressed a little. But basically it still seems like a good improvement in the general range we'd hope for. I also want to benchmark the cost of loading from an empty cache to verify it's no worse than before this change.

Safari looks similar -- slower across the board, but seems to benefit proportionally.

Firefox... oh my 🤭 . Its TinySDF performance is crazy slow. I need to dig into this and figure out if it was always that bad and/or how much worse I made it with the high-res SDF changes.

**Comment by ChrisLoer** [comment]
I updated the Firefox numbers after pulling in the fix to #10357, with those numbers the table looks like:

Firefox diff (ms) | Safari diff (ms) | Chrome diff (ms)
-- | -- | --
-452.6 | -618.4 | -461.4


Firefox improvement | Safari improvement | Chrome improvement
-- | -- | --
115.17% | 123.73% | 119.45%

However, since running that test I've been having trouble reproducing the same numbers (sometimes loading from cache doesn't seem any faster than generating the SDFs, even though the time spent "scripting" is still ~500ms lower). So.. I don't have high confidence. I'll continue investigating.

**Comment by ChrisLoer** [comment]
I dug into some flame graphs of page loads with and without the cache, and I think it gave me a stronger intuition for why the CPU time savings doesn't always show up as a load time savings. Basically, the second half of load time is constrained by the background workers, and the TinySDF time mainly matters to the extent that it starves background workers. In these two examples below, about 500ms of TinySDF time is saved but the page only loads 200ms faster -- the foreground starts working on the first `getGlyphs` batch while the background is still parsing other tiles, and it sends its first response in time to unblock the background while it keeps plugging away. More frames are dropped on the foreground, but it's not clear how noticeable that would be in a map that's not even fully loaded yet.

**Without cache, ~2660ms to full load, 527ms spent in TinySDF** 
Screen Shot 2021-02-11 at 14 48 01


**With cache, ~2460ms to full load, no time in TinySDF** 
Screen Shot 2021-02-11 at 14 48 27

I'm still not sure what changed in my environment that started changing my results, but my guess is it was because I initially had "disable cache" checked in the network profiler (and I was having a slow network day?) -- if tile results were coming in slowly enough, that would empty out the pipeline for the workers, so every delay in responding to `getGlyphs` would also stall a worker.

I _think_ this implies the cache should be relatively more important when either (a) the viewport is small (so not a lot of tiles queued up on the worker), or (b) tiles are uncached and the network is relatively slow (so they're spaced out).

**Comment by ryanhamley** [comment]
Closing as stale. We can revisit this PR if we make a decision on this approach.

**Pull request closed without merging**
