### PR TITLE
Refactored buffer creation

### PR DESCRIPTION
**Pull request by lucaswoj**
This is still in really early stages. Here, I'm trying to create some data-driven-styling-forward abstractions for passing data to the shaders. The current implementation of data driven styling implementation is a hack on top of buffers which only expect positions per feature (i.e. not colors, blurs, widths, etc) and expect that buffer values never change. 

cc @jfirebaugh @ansis

### CODE REVIEW

**Comment by jfirebaugh** [comment]
I like the direction here.

> Should we always allocate space for all attributes (colors, blurs, widths) in the buffer at construction time?

My assumption is that minimizing buffer size is meaningful for memory usage and GL performance, so I think it should allocate space only for data-driven attributes.

> Should we create a buffer per attribute?

@ansis @kkaefer Do you know if column-major or row-major orientation, or using one large buffer versus multiple smaller buffers, makes a different for GL performance?

**Comment by kkaefer** [comment]
@jfirebaugh https://developer.apple.com/library/ios/documentation/3DDrawing/Conceptual/OpenGLES_ProgrammingGuide/TechniquesforWorkingwithVertexData/TechniquesforWorkingwithVertexData.html

**Comment by lucaswoj** [comment]
Thanks Jon! 

> Do you know if column-major or row-major orientation, or using one large buffer versus multiple smaller buffers, makes a different for GL performance?

I'm interested to hear if @ansis or @kkaefer have any intuition here. I have a hunch that we'll have to run some experiments. I hope this refactoring will make it easier to run experiments on different buffer layouts!

**Comment by jfirebaugh** [comment]
That article is super helpful. Maybe the best layout for our needs is:

image

Use interleaved data for the attributes that are always present, and separate arrays for data-driven attributes, which are more likely to required updates from the use of the `set*Property` APIs.

**Comment by lucaswoj** [comment]
Takeaways from the article @kkaefer posted:

 > 
 > Apps that must submit a large number of primitives to render a frame need to carefully manage their vertex data and how they provide it to OpenGL ES. The practices described in this chapter can be summarized in a few basic principles:
 >
 > - **Reduce the size of your vertex data.**
 > - Reduce the pre-processing that must occur before OpenGL ES can transfer the vertex data to the graphics hardware.
 > - **Reduce the time spent copying vertex data to the graphics hardware.**
 > - Reduce computations performed for each vertex.

I think we're struggling with these two points being at odds. We're trying to decide between storing extra stuff in the buffer or spending time copying new stuff into the buffer. Hard to know what's going to be best for us. 

 > ### Avoid Storing Constants in Attribute Arrays
:ballot_box_with_check: 

 > Use the Smallest Acceptable Types for Attributes
:ballot_box_with_check: 

> ### Use Interleaved Vertex Data
> An exception to this rule is when your app needs to update some vertex data at a rate different from the rest of the vertex data, or if some data can be shared between two or more models. In either case, you may want to separate the attribute data into two or more structures. 

This is interesting. It suggests that we ought to use a buffer per style attribute.

 > ### Avoid Misaligned Vertex Data
:ballot_box_with_check: 

 > ### Consolidate Vertex Array State Changes Using Vertex Array Objects

I wonder if there's a JS equivalent of this? 

 > ### Map Buffers into Client Memory for Fast Updates

I wonder if there's a JS equivalent of this?

**Comment by lucaswoj** [comment]
@jfirebaugh Yes, that section looks to be the most relevant for us. I'll keep the one-buffer-per-likely-to-change-attribute use case in mind as I work on this refactoring.

**Comment by ansis** [comment]
> This is interesting. It suggests that we ought to use a buffer per style attribute.

If we want to update it on the cpu every frame, definitely.

> I wonder if there's a JS equivalent of this?

Yes, but it's an optional extension that isn't supported everywhere. We should use it where it's available.

> Map Buffers into Client Memory for Fast Updates
> I wonder if there's a JS equivalent of this?

No, there isn't

@lucaswoj you should also read through https://docs.google.com/presentation/d/12AGAUmElB0oOBgbEEBfhABkIMCL3CUX7kdAPLuwZ964/edit if you haven't already

**Comment by lucaswoj** [comment]
Oooooooook. We're still not out of the woods in terms of fully functional data-driven paint styles, but I'm going to call this PR functionally complete, ready for review, and start future work in separate branches.

cc @jfirebaugh @ansis @kkaefer 

(Only @kkaefer is in right now. We can probably hold off on merging this until @jfirebaugh is back because `mapbox-gl-js` isn't changing very much this week)

# Remaining Work (to occur in separate PRs, loosely ordered)

 1. Refactor `StyleLayer`, `StyleDeclaration`, and `StyleDeclarationSet` 
      - completely drop the distinction between "paint" and "layout" styles
      - clean up the API
      - better support data driven styles
 2. Refactor all other bucket types to use `Buffer2` and `Bucket2` (then drop the "2" suffix)
 3. Remove the `BufferSet` class. `Bucket2` will be responsible for creating its own buffers.
 4. Support `ref`ed layers in Bucket2
 4. Rebuild buffers when the stylesheet changes (`setPaintProperty` or class changes)
 5. Design an more efficient multi-vertex-attribute-buffer system for `Bucket2`

**Comment by lucaswoj** [comment]
Partially resolves #1318

**Comment by lucaswoj** [comment]
Gonna completely re-cut this PR

**Pull request closed without merging**
