### PR TITLE
Fire map#load if no initial style is set

### LINKED ISSUE #2042: Map#load never fires fire if a style isn't passed to the constructor
... even if a style is later set with `setStyle`

h/t @scothis

### PR DESCRIPTION
**Pull request by lucaswoj**
fixes #2042

cc @scothis @jfirebaugh @ansis @bhousel

### CODE REVIEW

**Comment by jfirebaugh** [comment]
:-1: 

I don't expect `load` to be fired if there is no style.

**Comment by scothis** [comment]
Feels like you're attacking #2042 from the wrong side. I agree with https://github.com/mapbox/mapbox-gl-js/issues/2042#issuecomment-180598721

**Comment by lucaswoj** [comment]
Great. I agree. Pushing a revision now.

**Comment by lucaswoj** [comment]
@jfirebaugh @scothis How do you feel about the latest revision?

**Comment by jfirebaugh** [comment]
:+1: :star2:

**Pull request merged**
