### PR TITLE
fix behavior of arrow keys when focused on a map container

### LINKED ISSUE #2302: Up-down keybindings don't preventDefault, so the page still scrolls
**mapbox-gl-js version**:

### Steps to Trigger Behavior

 1. Click on a map to focus it
 2. Hit up and down arrow keys
 3. The page scrolls

### Expected Behavior

The page should not scroll: only the map should move

### Actual Behavior

The page scrolls.

### PR DESCRIPTION
**Pull request by mollymerp**
fixes #2302 
I still need to add tests, and I'm not sure how to test user interactions like this so I will be looking into that!

### CODE REVIEW

**Comment by lucaswoj** [comment]
> I'm not sure how to test user interactions like this so I will be looking into that!

Neither are we! See #1550.

**Comment by lucaswoj** [comment]
You'll need to rebase this branch on `master` to fix CI.

**Comment by tmcw** [comment]
Did this get signoff before merging?

**Comment by lucaswoj** [comment]
@tmcw Yes, I gave a verbal :+1:

**Pull request merged**
