### PR TITLE
Upgrade buffer benchmark script

### PR DESCRIPTION
**Pull request by lucaswoj**
The buffer benchmark script is now much faster, much more robust, and prettier! Instead of collecting buffer statistics while doing a `flyTo`, the new benchmark manipulates `WorkerTile` directly.

 - tests are faster because workers are never idle
 - tests are more reliable because there is no dependency on network speed :grimacing: 
 - tests are more reliable because they always use the same number of samples
 - tests are more reliable because more samples are taken

screen shot 2015-11-05 at 1 18 13 pm

I'm open to discussion about the best way to structure this. We'll either need to expose the `bufferBenchmark` function OR several internal classes on `mapboxgl`. 

cc @jfirebaugh @mourner

### CODE REVIEW

**Comment by jfirebaugh** [comment]
What about directly browserifying `js/source/buffer_benchmark.js` for the benchmark page, or having budo handle it?

**Comment by mourner** [comment]
Very nice! Using the new benchmark, what are the times vs pre-bucket2 PR?

**Comment by lucaswoj** [comment]
@jfirebaugh I'll look into making a separate bundle. That's definitely the way to go, if its not too much work.

**Comment by lucaswoj** [comment]
@mourner I seem to have hit a bug while trying to get the freshest numbers for you. Working on it now. This benchmark was indicating ~50% slowdown earlier. 

I have a few new ideas to try to speed things up (independent of the bucket refactoring) too!

**Comment by lucaswoj** [comment]
This feels like its in a good place now.

The benchmark is no longer capable of testing multiple versions of GL JS in a single execution. However, now it boasts

 - the ability to compile a "production" version of GL JS on the fly (no more `npm run production`)
 - no new properties on `mapboxgl`
 - fewer lines of code :yum: 
 - no weird page redirects during the benchmark

**Comment by lucaswoj** [comment]
fixes #1669

**Comment by lucaswoj** [comment]
@mourner The latest stats are

 - with refactor: 887 ms
 - without refactor: 538 ms

...which represents a 65% difference. The next thing on my plate is closing that gap.

**Comment by lucaswoj** [comment]
I've managed to get the with-refactor benchmark score down to ~620ms! Still needs a little polish but I will push that in a separate PR once this lands.

:ship: @jfirebaugh @mourner?

**Comment by jfirebaugh** [comment]
:+1:

**Pull request merged**
