### PR TITLE
Add style API testing to mapbox-gl-test-suite

### PR DESCRIPTION
**Pull request by lucaswoj**
... and fixes a regression for #2534

ref https://github.com/mapbox/mapbox-gl-test-suite/issues/76

cc @jfirebaugh @mourner

### CODE REVIEW

**Comment by jfirebaugh** [comment]
Looks great! Glad to see that it caught a regression already.

**Comment by lucaswoj** [comment]
:shipit:?

**Comment by mourner** [comment]
Rebased, will merge once the build passes.

**Comment by mourner** [comment]
@lucaswoj there's one failing test — the #2477 regression one. Let's figure it out and then 🚢 once everything passes.

**Pull request merged**
