### PR TITLE
Move local type definitions out of flow-typed

### PR DESCRIPTION
**Pull request by anandthakker**
Prepares for #6963

### CODE REVIEW

**Comment by anandthakker** [comment]
Note also that I replaced our GeoJSON declarations with https://github.com/bigslycat/flow-geojson, which seems like a pretty well-written set of Flow types for GeoJSON.

**Comment by jfirebaugh** [comment]
Eh, I'm not a fan of those GeoJSON definitions. They're much more complicated than is necessary, and there are at least a couple of issues (feature geometry should be nullable, `JSONArray` type is wrong).

**Comment by anandthakker** [comment]
Dang, I missed those.  Alright, alternative: we could keep the ones we had and publish them as a separate npm pacakge `@mapbox/geojson-types`

**Comment by anandthakker** [comment]
> Edit: also properties should not be nullable

@jfirebaugh looks like the spec allows null for `properties`:

>      A Feature object has a member with the name "properties".  The
>      value of the properties member is an object (any JSON object or a
>      JSON null value).
https://tools.ietf.org/html/rfc7946#section-3.2

**Comment by anandthakker** [comment]
@jfirebaugh updated

**Pull request merged**
