### PR TITLE
Fix displaced markers when toggling projections

### LINKED ISSUE #12129: Marker position is not updated when changing from a projection with world copies to one without
**mapbox-gl-js version**: 2.9.2

**browser**: any

### Steps to Trigger Behavior

 1. Drag the map to the right until the marker jumps to the other world copy
 2. Click "switch projection"
 3. Marker is now outside the world

Aug-02-2022 17-21-44

### Link to Demonstration

https://codesandbox.io/s/trusting-bartik-vhk4j1?file=/src/App.js

### Expected Behavior
The marker position is updated and it shows in the correct place

### Actual Behavior
The marker appears off world

### PR DESCRIPTION
**Pull request by avpeery**
This PR fixes #12129, updating marker position correctly when toggling between a map that renders world copies and a map that doesn't by wrapping the lng of the marker when updating for projections that wrap.

BEFORE:

https://user-images.githubusercontent.com/42715836/190811871-e34fea2c-7515-45c2-9832-61c2893313dc.mov

AFTER:

https://user-images.githubusercontent.com/42715836/190811958-8bee6795-b70a-4ec3-ad29-1ccf0b38c1e2.mov

## Launch Checklist

 - [x] briefly describe the changes in this PR
 - [x] include before/after visuals or gifs if this PR includes visual changes
 - [x] write tests for all new functionality
 - [x] manually test the debug page
 - [ ] tagged `@mapbox/map-design-team` `@mapbox/static-apis` if this PR includes style spec API or visual changes
 - [ ] tagged `@mapbox/gl-native` if this PR includes shader changes or needs a native port
 - [x] apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog'
 - [x] add an entry inside this element for inclusion in the `mapbox-gl-js` changelog: `<changelog>Fix updating marker position when toggling between world copied projections and projections without</changelog>`

### CODE REVIEW

**Review by stepankuzmin — APPROVED** [review]
👍

**Review by SnailBones — CHANGES_REQUESTED** [review]
Nice fix! This should also be applied to popups to keep consistency with markers.

Also, this changes behavior of dragging markers off the edge of the map when `renderWorldCopies` is false, resulting in markers remaining on the map area and looping instead of being dragged off the edge.  I'm not 100% sure what the correct behavior is here, but should we consider snapping markers to the map edge?

https://user-images.githubusercontent.com/14878684/191038889-5f94626a-cf4b-46df-96dc-2c98c3e82cfb.mp4

https://user-images.githubusercontent.com/14878684/191038921-fe3a48d5-1d9a-486a-8269-db99f9d34372.mp4

**Comment by avpeery** [comment]
Good points @SnailBones. I think it's acceptable/reasonable to not allow setting popups/markers off of the map, but also wouldn't want to change the behavior if there is a potential customers are using this (but I think that would be unlikely). Do you have opinions on this?

**Comment by SnailBones** [comment]
> Good points @SnailBones. I think it's acceptable/reasonable to not allow setting popups/markers off of the map, but also wouldn't want to change the behavior if there is a potential customers are using this (but I think that would be unlikely). Do you have opinions on this?

Agreed, I think it's unlikely that many customers rely on markers outside of the map area, so in my opinion snapping would be the ideal behavior. But I'd also be happy with keeping the current behavior (i.e. only trigger looping on projection change).

**Comment by avpeery** [comment]
@SnailBones  Updated popups to wrap as well, and found that popups not attached to markers did not get positions updated when toggling projections, and found that popups not attached to markers were also not taking into account terrain exaggeration. I used the same implementation for markers for popup updating.

**Review by SnailBones — APPROVED** [review]
Nit: Thoughts on naming the property `options.wrap` instead of `options.setToWrap`? Or just passing a boolean instead of an object? Or might we need to add more properties in the future?

Otherwise looks great to me and works great, nice work!

**Comment by avpeery** [comment]
> Nit: Thoughts on naming the property `options.wrap` instead of `options.setToWrap`? Or just passing a boolean instead of an object? Or might we need to add more properties in the future?

Naming suggestion noted, and will do! I don't think we'd probably expand on the object, but just thought passing through `true` would read confusing since it'll still be updating the markers/popups when not passing `true` in.

**Pull request merged**
