### PR TITLE
Remove strictly-increasing fog range validation

### PR DESCRIPTION
**Pull request by rreusser**
Addresses #10739. This PR removes the fog range validation and is slated for release as gl-js 2.3.1 and style-spec 13.20.1.

Will need cherry-picking into release-v2.3.0.

I am not aware of any use-case for this, but if you have two boxes for `fog.range[0]` and `fog.range[1]`, you cannot currently simply set the two values independently:

1. range: `[0, 1]` <---- initial state
2. range: `[5, 1]` <---- change first value; error
3. range: `[5, 6]` <---- desired state

This change allows a reasonable alternative in which step 2 shows the specified, inverted appearance, as in the following, rather than a validation error:

Screen Shot 2021-06-14 at 9 53 48 AM copy

cc @mapbox/map-design-api @mapbox/map-design-studio @tristen 

## Launch Checklist

 - [x] briefly describe the changes in this PR
 - [x] include before/after visuals or gifs if this PR includes visual changes
 - [x] write tests for all new functionality
 - [x] document any changes to public APIs
 - [ ] post benchmark scores
 - [x] manually test the debug page
 - [x] tagged `@mapbox/map-design-team` `@mapbox/static-apis` if this PR includes style spec API or visual changes
 - [ ] tagged `@mapbox/gl-native` if this PR includes shader changes or needs a native port
 - [ ] apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog'
 - [x] add an entry inside this element for inclusion in the `mapbox-gl-js` changelog: `<changelog>Remove fog validation which requires strictly increasing range</changelog>`

### CODE REVIEW

**Comment by tristen** [comment]
I kind of like how this inverts and favors flexibility.

Just throwing it out there @rreusser but I'm curious if it would be preferable to keep validation in place but add some sort of `sequential: true` field to the spec? If new properties are introduced that would also need their order maintained that might be the best way at letting Studio know how to handle the UI?

**Comment by rreusser** [comment]
@tristen I agree. 👍  I like `sequential: true`. My only reservation is that it involves coordination with a few more projects to support a new type of constraint so that it requires a bit more care.

How would this effect studio? As in: if the validation were present via `sequential: true`, would the above sequence of events still trigger a validation error, and it instead wouldn't require custom workarounds to avoid an invalid internal state? Is it still preferable here to allow this inverted state for the reason above?

**Comment by tristen** [comment]
> Is it preferable here to allow this inverted state for the reason above?

Oh yeah, I think I would agree with this. That sequence of events shouldn't trigger a validation error. For Studio, if `sequential: true` is detected for a spec property we would lightly enforce it from the UI as we do for [`minimum` and `maximum`](https://github.com/mapbox/mapbox-gl-js/blob/09d9518449b032a04147ef1e694a1f49a52444c6/src/style-spec/reference/v8.json#L3695-L3696).

Screen Shot 2021-06-14 at 3 53 09 PM

**Comment by karimnaaji** [comment]
`sequential: true` is a good point, my only concerns:
- What other spec entry would adopt it now? If that's the only one, might be fine to hold until we see another use of it
- It's not clear whether all validation errors are necessarily represented as a token in the specification 

My personal preference would be to be flexible on the inputs (as in this PR), and eventually gate the values from the UI if we need to be stricter or need extended guidance on what values are correct. 

>As in: if the validation were present via sequential: true, would the above sequence of events still trigger a validation error, and it instead wouldn't require custom workarounds to avoid an invalid internal state?

That would be my question as well, as setting wrong min/max values result in validation errors. The only difference would be that this error is now explicit and part part of the spec.

**Review by karimnaaji — APPROVED** [review]
Looks good. Being flexible in the inputs works well In this case 👍

**Pull request merged**
