### PR TITLE
Simplify draw_line.js

### PR DESCRIPTION
**Pull request by mourner**
- Removed lots of repetition in `draw_line.js`
- Moved calculation of line antialiasing matrix and stretch coefficient to transform so that it’s not repeated

👀 @lucaswoj @ansis

### CODE REVIEW

**Comment by mourner** [comment]
## frame-duration benchmarks

**master cd6c761:** 10.6 ms, 15% > 16ms
**simplify-draw-line 3381447:** 10.2 ms, 14% > 16ms

**Comment by jfirebaugh** [comment]
Native will soon look quite a bit different: [preview](https://github.com/mapbox/mapbox-gl-native/blob/3ef3084425b59ee1ea2bc26787c7e2d6363e8a62/src/mbgl/renderer/painter_line.cpp).

**Comment by mourner** [comment]
> Can you port the lineAntialiasingMatrix and lineStretch changes to -native?

I can look into this, but I guess this would have much less impact in native.

**Comment by jfirebaugh** [comment]
I'll open an issue in native to hoist these calculations.

**Pull request merged**
