### PR TITLE
[not ready] Support padding positions in fitBounds

### PR DESCRIPTION
**Pull request by tristen**
- ref #995

### CODE REVIEW

**Comment by 1ec5** [comment]
:+1: Fixes #1339.

**Comment by tristen** [comment]
cc @jfirebaugh for review + what bases need to be covered before merging.

**Comment by jfirebaugh** [comment]
Good time to start getting some test coverage for `fitBounds`. :smile:

**Comment by tristen** [comment]
-> https://github.com/mapbox/mapbox-gl-js/pull/1682

**Pull request closed without merging**
