### PR TITLE
map.setStyle retains existing classes. Fixes #911

### LINKED ISSUE #911: Retain map classes after map.setStyle
If classes are active on the map (using `map.addClass` or `map.setClassList`) and the stylesheet is updated using `map.setStyle`, the classes are removed. We should keep the classes active until `map.removeClass` is called.

### PR DESCRIPTION
**Pull request by lbud**

### CODE REVIEW

**Comment by jfirebaugh** [comment]
I think if we do #911 we should make the API reflect the fact that classes are no longer tied to the style. I.e. move the class state and mutation methods (`addClass`, `removeClass`, etc) to `Map` and pass the class list into `style.cascadeClasses`.

**Comment by lbud** [comment]
Good point. Though I wonder if (additionally, or instead?) maybe we should also make `retainClasses` an optional `setStyle` param? Agreed that it's weird to untie classes and style while keeping the API `style.addClass`, but it also is a bit weird to untie classes and styles in general.

**Comment by jfirebaugh** [comment]
Hopefully the functionality of `{retainClasses: false}` would be adequately covered by `setStyle(...)` + `setClassList([])`.

**Comment by jfirebaugh** [comment]
⇢ #936

**Pull request closed without merging**
