### PR TITLE
Smart setStyle (part 1)

### PR DESCRIPTION
**Pull request by anandthakker**
Goal: make `map.setStyle({ layers: [ ..., { one layout property different from map's current style } ] })` as good as `map.setLayoutProperty()` (modulo a pretty cheap diff)

- [x] Add mapbox-gl-style-spec's diff implementation as `Style#setState`.
- [x] Change `Map#setStyle` to delegate to `Style#setState` (instead of constructing a new `Style` instance).
- [x] Properly handle changes to `layer.source`, `layer.source-layer`, or `layer.type`: https://github.com/mapbox/mapbox-gl-style-spec/issues/570
- [x] deref incoming layers before processing
- Handle `diff` operations that rely on currently-missing setters:
  - [x] setGlyphs, setSprite: I think we can reconstruct `this.glyphSource` and `this.sprite`, but need to make sure that tiles are then reloaded for all sources **ticketed separately: https://github.com/mapbox/mapbox-gl-js/issues/3625**
  - [x] setTransition: looks like this is used at update-time, so it may be safe to simply rely on setting `this.stylesheet` to the up-to-date style (i.e., no diff magic required)
  - setLayerProperty: used for every layer property other than `{min,max}zoom`, `layout`, `paint`, `filter`, `metadata`,  -- I think this just leaves: `paint.*`, `type`, `ref`, `source`, and `source-layer`.  If I didn't miss any, and we drop paint classes, then this should be a nonissue.
 - [x] Update unit tests for `Map#setStyle`
 - [x] Add tests for `Style#setState`
   - If `Style`'s individual mutators are going to be basically become [private helper functions](https://gist.github.com/anandthakker/91ab25fa3932ccf8cae9c4c4d08012d7#refactor), would it make sense to just change each of their unit tests into a corresponding test for `setState`?
 - [x] Add runtime-styling render tests for `setStyle`.  **Done in https://github.com/mapbox/mapbox-gl-test-suite/pull/170**, pending review/merge
 - [x] Merge https://github.com/mapbox/mapbox-gl-js/pull/3655 (fixes bug wherein removing a symbol layer and readding it as a circle layer causes an exception to be thrown)

## Launch Checklist

 - [x] briefly describe the changes in this PR
 - [x] write tests for all new functionality
 - [x] document any changes to public APIs
 - [x] post benchmark scores
 - [x] manually test the debug page

### CODE REVIEW

**Comment by anandthakker** [comment]
@jfirebaugh @lucaswoj Here's an initial working "mvp," with a few lingering tasks listed in the top of the ticket.  What are you thoughts on the questions re: unit tests?

**Comment by jfirebaugh** [comment]
> What does `diff` do if `layer.source`, `layer.source-layer`, or `layer.type` have changed?

Looks like those properties are one of the cases where it'll generate an exception trying to call `setLayerProperty`, which doesn't exist. What should happen is a removeLayer/addLayer pair.

I also notice that for sources, [any differences in properties](https://github.com/mapbox/mapbox-gl-style-spec/blob/512126c802dbb8f282e9826b181f0d53da00daf2/lib/diff.js#L119-L123) currently results in a removeSource/addSource pair. This will not produce the expected result if there are layers actively using that source. Removing an actively-used source is not supported.

> - [ ] Should we handle `layer.ref` in a style passed to `setState`? Reject it?

Use [deref](https://github.com/mapbox/mapbox-gl-style-spec/blob/mb-pages/lib/deref.js) on the style input before doing anything else.

> - [ ] Handle `diff` operations that rely on currently-missing setters:
>  - setGlyphs, setSprite: I think we can reconstruct `this.glyphSource` and `this.sprite`, but need to make sure that tiles are then reloaded for all sources

Yeah, let's try adding setters for these independently of this PR.

>    - If `Style`'s individual mutators are going to be basically become [private helper functions](https://gist.github.com/anandthakker/91ab25fa3932ccf8cae9c4c4d08012d7#refactor), would it make sense to just change each of their unit tests into a corresponding test for `setState`?

Eventually, yes. But for now let's make parallel setStyle tests.

My inclination is to do all testing for this via test-suite.

**Comment by anandthakker** [comment]
> Looks like those properties are one of the cases where it'll generate an exception trying to call setLayerProperty, which doesn't exist. What should happen is a removeLayer/addLayer pair.

Agreed: https://github.com/mapbox/mapbox-gl-style-spec/issues/570

> I also notice that for sources, any differences in properties currently results in a removeSource/addSource pair. This will not produce the expected result if there are layers actively using that source. Removing an actively-used source is not supported.

Oh, interesting.  I suppose the most straightforward thing to do here would be to modify the style diff so that `removeSource` implies `removeLayer` for any layers that use that source, with `removeSource`/`addSource` pairs thus producing `[removeSource, removeLayer, removeLayer, ..., addSource, addLayer, addLayer, ...]`

> Yeah, let's try adding setters for these [setSprite, setGlyphs] independently of this PR

👍  in the interim, I propose to have `Style#setState` throw when it encounters these, and `Map#setStyle` fall back to `new Style()` in that case.

> My inclination is to do all testing for this via test-suite

If/when we move the diffing logic to be resolved only once per 'batch', it will probably make sense for there to be some unit tests around that.

**Comment by anandthakker** [comment]
benchmark | master f1d1bf4 | smart-set-style b8f9a9c
--- | --- | ---
**map-load** | 192 ms  | 171 ms 
**style-load** | 119 ms  | 122 ms 
**buffer** | 938 ms  | 948 ms 
**fps** | 60 fps  | 60 fps 
**frame-duration** | 4.5 ms, 0% > 16ms  | 4.5 ms, 0% > 16ms 
**query-point** | 0.81 ms  | 0.85 ms 
**query-box** | 69.82 ms  | 74.15 ms 
**geojson-setdata-small** | 6 ms  | 3 ms 
**geojson-setdata-large** | 216 ms  | 253 ms

**Comment by anandthakker** [comment]
@jfirebaugh @lucaswoj k, I think this should be ready for 👀, pending also the merge of upstream PR mapbox/mapbox-gl-test-suite#170 (and subsequent update of package.json here)

A

**Comment by AndyMoreland** [comment]
@anandthakker above you mention that all sources are going to need to reload tiles when the sprite changes -- does that mean that raster tile sources are going to redraw? It'd be super nice for my company's use case if we could avoid that because we add lots of new sprites at runtime and right now the full-map flickers are pretty awful.

**Comment by anandthakker** [comment]
@AndyMoreland Yes, as of now (both before and after this particular PR), the fully reloading the style is still going to happen, but there are plans to remove this necessity -- check out the tickets referenced here: https://github.com/mapbox/mapbox-gl-js/issues/3625#issuecomment-261113572.  I'm not up to speed on how all of those interrelate, but the one that most directly bears on this problem is probably #2058

**Comment by AndyMoreland** [comment]
Thanks for the response. Will check the referenced issues out.

**Comment by anandthakker** [comment]
Added a fix for https://github.com/mapbox/mapbox-gl-js/issues/3633 in a540347

**Comment by anandthakker** [comment]
This should now only be pending https://github.com/mapbox/mapbox-gl-test-suite/pull/170.  It passes all of those tests, so if that one's good, then this should be ready as well.

**Comment by anandthakker** [comment]
@jfirebaugh @lucaswoj updated checklist at the top to include #3655  as a prerequisite.

**Comment by anandthakker** [comment]
Updated `setstyle.html` example to use light-v9/dark-v9.  Caveats:
 - Had to force the `sprite` to be the same URL for both, due to #2058
 - Had to add a missing fill-outline-color to a layer, due to: #3657 

setstyle

**Pull request merged**
