### PR TITLE
Cleanup debugging code

### LINKED ISSUE #2261: Remove GlyphAtlas debug mode
mapboxgl crashed when i debug the GlyphSource. the code as these:(glyph_source.js)
    var glyphAtlas = new GlyphAtlas(512, 512);
    glyphAtlas.debug=true;
    this.atlases[fontstack] = glyphAtlas;

by the way ,is there a online geojson data source site?

### PR DESCRIPTION
**Pull request by bhousel**
Included:
* Remove canvas atlas texture debug code (closes #2261)
* Rename "debug" -> "tileDebug"

### CODE REVIEW

**Comment by jfirebaugh** [comment]
:+1: on removing atlas debug code.

I'm :+1: on `debug` ⇢ `tileDebug` too. This'll be a semver bumping change that will affect Mapbox Studio in particular (cc @scothis), so let's make sure it gets into the CHANGELOG.

**Comment by bhousel** [comment]
> This'll be a semver bumping change that will affect Mapbox Studio in particular (cc @scothis), so let's make sure it gets into the CHANGELOG.

That's good to know... It's definitely something we can hold off on merging.

**Comment by lucaswoj** [comment]
How about `debug` ⇢ `showTileBoundaries`? It's a little longer but much more descriptive. Maybe `collisionDebug` ⇢ `showSymbolCollisionBoxes` too. 

> That's good to know... It's definitely something we can hold off on merging.

We can merge whenever! We just need to communicate the changes clearly.

**Comment by bhousel** [comment]
Merged as-is.   We can do a more thorough revision of the debugging code later.

Note that I didn't dig down into the buffer or shader code, so there are still "internal" things in there called `debug` that should probably be renamed to `tile-debug`.  I don't want this small rename to affect bigger changes in other PRs.

**Comment by lucaswoj** [comment]
merged in 2028b482ab7492fd4cfc4a3ec5772f353890219b and 6f5043fea3d9e7587421088229bad056d13d8b40

**Comment by scothis** [comment]
Thanks for the heads up. it's an easy change in Studio.

**Pull request closed without merging**
