### PR TITLE
add snapshot example

### PR DESCRIPTION
**Pull request by mollymerp**
this replaces #6518

@samsammurphy thanks for your contribution! I had to open a new PR because #6513 caused some of your work to break, and I didn't want to bother you further with more back and forth (I can't push to your branch). I also changed the styling around a bit and simplified the code a bit because we try to keep our examples as minimal as possible. 

we'll have to be careful with this example because it will break if we change our CSS for the logo control at all 😕 

## Launch Checklist

 - [x] briefly describe the changes in this PR
 - [x] manually test the debug page

### CODE REVIEW

**Comment by mollymerp** [comment]
_before clicking_
image

_after clicking_
image

**Comment by ryanhamley** [comment]
Sorry to do a little rewrite on the CSS. I think it looks good. Super cool demo. 👍

**Comment by mollymerp** [comment]
@jfirebaugh I agree this is a bit too brittle to be comfortable with, but the `LogoControl` is private now and I wasn't sure we would want to change that  – do you suggest we make `map.logoControl` public (we explicitly made it private in the past to encourage TOS compliance) or have `getLogoImage` on the `Map` object?

**Comment by andrewharvey** [comment]
While I agree relying on internal implementation details isn't a good idea, I think it's better to include this example as is and leave the door open to change/refine it later on.

That aside, any kind of implementation of the Logo and Attribution, even a no so ideal one makes complying with the TOS much easier.

> // Firefox requires SVG to have height and width specified
> // in the root SVG object when drawing to canvas

Can we not just add the `width` and `height` to the [`mapboxgl-ctrl-logo.svg`](https://github.com/mapbox/mapbox-gl-js/blob/master/src/css/svg/mapboxgl-ctrl-logo.svg)?

**Comment by ryanhamley** [comment]
I'm going to close this PR because we're uncomfortable with some of the implementation details here. @ChrisLoer and I are hoping to work on a video export feature soon and that could probably expose a snapshot method as well then we can revisit adding examples for these features.

**Comment by andrewharvey** [comment]
This has been handy in a few cases to demonstrate how to take a static snapshot of a map, hope it or a reincarnation of it does eventually make it into the examples at some point.

**Comment by andrewharvey** [comment]
@ryanbaumann I know some of the implementation details here quite deep, but I still find myself digging up this PR to use as a reference for new implementations.

Even if it gets changed later from a future video export feature or refactor, my 2c are it would be still useful for others to have this published in the meantime.

**Pull request closed without merging**
