### PR TITLE
Example 3rd party mvt

### PR DESCRIPTION
**Pull request by geografa**
This PR updates the [third party example](https://www.mapbox.com/mapbox-gl-js/example/third-party/) with Mapillary sequences due to changes with Mapzen.

## Launch Checklist

 - [ ] write tests for all new functionality
 - [x] no changes to public APIs
 - [ ] post benchmark scores
 - [x] manually test the debug page

### CODE REVIEW

**Comment by geografa** [comment]
oops. I think this should be for mb-pages. Is there a quick way to switch this?

**Comment by geografa** [comment]
Something is fishy with my branch and I'm not confident squashing these so making new PR.

**Comment by jfirebaugh** [comment]
@geografa Did you get around to opening a new PR?

**Comment by geografa** [comment]
@jfirebaugh zoops, slipped my radar. Making a new PR.

**Pull request closed without merging**
