### PR TITLE
Make benchmark runner able to run multiple benchmarks

### LINKED ISSUE #2405: Allow running multiple tests on the benchmark page

### LINKED ISSUE #2656: Use "WEBGL_lose_context" to destroy WebGL context in Map#remove
**mapbox-gl-js version**: 0.19.0

Chrome 50

### Steps to Trigger Behavior

 1. create a map
 2. `.remove()` the map
 3. repeat

### Expected Behavior

No warnings or errors should occur.

### Actual Behavior

After a certain number of iterations (about 10 for me) there is a warning in the console `Too many active WebGL contexts. Oldest context will be lost`. This error indicates that the GL context is not being cleaned up when the map is removed.

### LINKED ISSUE #2800: Add "copy as markdown" button to benchmark results page

### PR DESCRIPTION
**Pull request by lucaswoj**
fixes #2405
fixes #2656
fixes #2800 

This PR is a rewrite of our benchmark runner that makes it easy to run all the benchmarks in series and copy the results into a GitHub-Markdown-friendly format. My hope is that this makes it easier for our contributors to get benchmark results on their work and guides the evolution of our benchmark suite.

cc @mollymerp @mourner @tmcw @mapsam @anandthakker 

screen shot 2016-08-05 at 12 46 58 pm

_Note that the benchmark results depicted above ^ are slow because I had the debugger open_

### CODE REVIEW

**Comment by mollymerp** [comment]
OooOoo fancy :sparkles:

**Comment by anandthakker** [comment]
Nice!  @lucaswoj two small suggestions/requests:

1. I think it would still be helpful to be able to run a single benchmark, to make it easier to iterate when working on a particular perf issue.
2. Over in https://github.com/mapbox/mapbox-gl-js/pull/2812 I had occasion to add a "manual" benchmark that waits for a click (so that you can open up dev tools and start recording).  If we do 1, could we also include a way for a benchmark to be omitted from the automated run?

**Comment by mourner** [comment]
This is great, but I'm bummed to see the react dependencies added to our already super-bloated devdeps setup. :( The UI is very simple, could we go by without heavy frameworks?

**Comment by anandthakker** [comment]
> I'm bummed to see the react dependencies added 

Heh - I was gonna suggest just bringing in React from the CDN.  Alternatively, there's https://github.com/developit/preact

**Comment by lucaswoj** [comment]
What are your concerns about adding React as a dev dependency? 

Developing this page with React allowed me to iterate very quickly on the design. I suspect it'll help us maintain and extend the page too.

**Comment by mourner** [comment]
@lucaswoj the concerns are dependency creep and generally making things more complex in an already absurdly complex repository. You can ignore my concerns and still merge, I just thought I would mention them.

Also, `reactify` is [deprecated](https://github.com/andreypopp/reactify) and you need to bring [babelify](https://github.com/babel/babelify) and [babel-preset-react](https://github.com/babel/babel/tree/master/packages/babel-preset-react) instead, which bring a ton of other subdeps.

**Comment by lucaswoj** [comment]
> I think it would still be helpful to be able to run a single benchmark, to make it easier to iterate when working on a particular perf issue.

Agreed. Done in the latest commit. 

> Over in #2812 I had occasion to add a "manual" benchmark that waits for a click (so that you can open up dev tools and start recording). If we do 1, could we also include a way for a benchmark to be omitted from the automated run?

One of my intentions in this refactor is to prevent dead code in our `/bench` folder. In working on this project, I found a couple of broken benchmark scripts 😢. In the case you're describing, I would prefer to automate the benchmark or leave it out of `master`.

**Comment by lucaswoj** [comment]
> the concerns are dependency creep and generally making things more complex in an already absurdly complex repository.

Yes, this is an important consideration. Other important considerations include:

 - **How well-maintained the dependency is.** React is actively maintained by Facebook and a large community.
 - **What the dependency saves us from having to write or do ourselves.** React provides an abstraction over the DOM that allows us to develop dev tools more quickly and dev tools which are more maintainable. I would not have been able to create this tool within my timebox for this project without React. I look forward to creating more dev tools that use React. 
 - **Whether the dependency is a dev dependency or a production dependency.** This is a dev dependency. It will not impact our production users. It as a very minimal impact on our contributors.
 - **How well-architected the dependency is.** I know and trust the team that builds React. The interface it exposes is well designed.
 - **How familiar GL JS contributors and Mapboxers are with the dependency.** There exists a large amount of React experience at Mapbox.
 - **Whether the dependency is redundant to an existing dependency.** We do not have any existing dependencies to facilitate UI development. 

In all, the the wins for our team outweigh the costs.

**Pull request merged**
