### PR TITLE
fix light transitions

### LINKED ISSUE #5982: Transitionable light properties are not transitioning
`light-position`, `light-intensity` and `light-color` are currently not transitioning. At a glance this seems to have happened sometime between 0.42.0 and 0.43.0.

### PR DESCRIPTION
**Pull request by mollymerp**
fix #5982

seems like flow should have caught this one 🤔 

## Launch Checklist

 - [x] briefly describe the changes in this PR
 - [x] write tests for all new functionality
 - [x] document any changes to public APIs
 - [ ] post benchmark scores
 - [x] manually test the debug page

### CODE REVIEW

**Comment by mollymerp** [comment]
interestingly, pixelmatch isn't catching diffs in the image when lighting variables change (even though the rendered images are visually different) 🤔

**Comment by jfirebaugh** [comment]
> seems like flow should have caught this one

Agreed... looks like the reason it doesn't is related to the fact that `util.extend`'s return type is `Object`, a [very weak type](https://github.com/facebook/flow/issues/4726) in flow. We could fix this by typing `extend` as `Object$Assign`, which is a magic type used as the type of `Object.assign`.

**Comment by jfirebaugh** [comment]
The pixelmatch thing is related to the layer being semitransparent. It doesn't look like `"fill-extrusion-opacity": 0.7` is essential; to minimize the test how about:

```
{
  "version": 8,
  "metadata": {
    "test": {
      "width": 64,
      "height": 64,
      "description": "Tests that light transitions correctly by checking the rendering halfway through the (default 300ms long) transition",
      "operations": [
        [
          "setLight",
          {
            "position": [1.15, 0, 30],
            "intensity": 1,
            "color": "red"
          }
        ],
        [
          "wait",
          0
        ],
        [
          "wait",
          150
        ]
      ]
    }
  },
  "sources": {
    "geojson": {
      "type": "geojson",
      "data": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -10,
              -10
            ],
            [
              -10,
              10
            ],
            [
              10,
              10
            ],
            [
              10,
              -10
            ],
            [
              -10,
              -10
            ]
          ]
        ]
      }
    }
  },
  "layers": [
    {
      "id": "extrusion",
      "type": "fill-extrusion",
      "source": "geojson",
      "paint": {
        "fill-extrusion-height": 0,
        "fill-extrusion-color":"blue"
      }
    }
  ]
}
```

**Comment by mollymerp** [comment]
@jfirebaugh thanks – I wasn't thinking that a test w a no-height extrusion would fail on master but it does 🙇‍♀️ 
> The pixelmatch thing is related to the layer being semitransparent

interesting – is this related to https://github.com/mapbox/pixelmatch/issues/21 or does it warrant a new bug report?

**Pull request merged**
