### PR TITLE
Add Geocoder example & clean up Directions example

### PR DESCRIPTION
**Pull request by tristen**

### CODE REVIEW

**Comment by tristen** [comment]
@jfirebaugh :+1: :-1: ?

**Comment by jfirebaugh** [comment]
* 4 space indent
* Title should be a verb phrase (#1836)

**Comment by jfirebaugh** [comment]
* `api.tiles.mapbox.com` ⇢ `api.mapbox.com`

**Comment by jfirebaugh** [comment]
:+1: 

When merging this, please rebase+squash to a single commit, then fast-forward merge via the command line.

**Pull request merged**
