### PR TITLE
Ensure _rerender is called if _styleDirty is true

### LINKED ISSUE #2936: Removing a layer causes map.loaded() to return false until map is moved.
**mapbox-gl-js version**:0.21.0

**jsBin**: http://jsbin.com/fewegikejo/edit?html,console,output

### Steps to Trigger Behavior

 1. Check that map.loaded() returns true
 2. Remove any layer from the map
 3. Check that map.loaded() returns false a few times
 4. Pan or zoom the map
 5. See that map.loaded() now returns true

### PR DESCRIPTION
**Pull request by anandthakker**
Closes #2936

Second attempt - either the fix or the unit test were causing problems in the original attempt (#2961)

### CODE REVIEW

**Comment by anandthakker** [comment]
@lucaswoj I'm still not totally sure about this unit test -- it's working consistently locally, but the previous one was too.  Maybe we can leave this PR open and kick the build a few times to see if it appears to work consistently on Circle?

**Comment by anandthakker** [comment]
Update: throughout the evening I've restarted the CircleCI build four times, and it's passed each time.  Not a huge sample, but promising.

**Comment by anandthakker** [comment]
Okay, I've hit "Rebuild" 7 times, for a total of 8 successful builds.  If the unit test was [failing 50% of the time before](https://github.com/mapbox/mapbox-gl-js/issues/2936#issuecomment-239306091), then I think this is statistically significant (p < 0.005 heh)

**Comment by mourner** [comment]
I've checked the PR before and I think it's correct — the dirty flag should be always set to true while the animation loop is still running. Let's merge and see if it causes any more problems. The volatility may have been caused but our switch to OS X image on Circle.

**Pull request merged**
