### PR TITLE
control Map's resize trigger

### PR DESCRIPTION
**Pull request by behnammodi**
So, By this PR we can control Map's resize trigger

ex:
```js
({
  ...
  shouldTrackResize: () => {
    if (window.innerWidth < window.innerHeight) {
      return true;
    }
    
    return false;
  }
  ...
})
```

### CODE REVIEW

**Comment by rreusser** [comment]
Thanks for the PR, @behnammodi! I understand the use case, but I suspect that it might be too much of a breaking change and too inconsistent to for a single option to permit a function rather than a boolean.

You can modify this property at runtime as follows using the private API (which may change, though such a change is not currently planned):

```js
window.addEventListener('resize', function () {
  if (window.innerWidth < window.innerHeight) {
    map._trackResize = true;
  }
  map._trackResize = false;
});
```

Perhaps instead of a function, runtime-modifiable properties which reflect user inputs could be public properties.

**Comment by ryanhamley** [comment]
Hi @behnammodi unfortunately this isn't a PR that we'll be able to accept. Changing a public API like this without it being backwards compatible would require a major version update and the gain here is very minimal for such a drastic change. If you need to control the conditions in which the map resizes, the best solution will be to manually call `map.resize()` in your application.

**Comment by behnammodi** [comment]
@rreusser Thanks 🙏🏻

**Comment by behnammodi** [comment]
@ryanhamley Thanks, we can have it without breaking change, I mean `trackResize` can accept `boolean` or `function`

**Comment by behnammodi** [comment]
@ryanhamley I updated PR, and remove all breaking changes, `trackResize` can accept `boolean` and `function`, please open PR and review again.

Also, I know we have `resize`, but it is very huge process.

**Comment by ryanhamley** [comment]
I am inclined to say that even if we maintain backwards compatibility, this change would increase the complexity of our API and its attendant documentation for a fairly negligible improvement, especially since there's an easy workaround here with `resize`. But if anyone else on GL JS has other thoughts, I'd be happy to reconsider.

**Comment by behnammodi** [comment]
@ryanhamley Thanks, for heard anyone else comment we need to open this PR

**Pull request closed without merging**
