### PR TITLE
bump feature filter, fix bug where 'in' filter drops features

### PR DESCRIPTION
**Pull request by samanpwbb**
See https://github.com/mapbox/feature-filter/pull/14

### CODE REVIEW

**Comment by lucaswoj** [comment]
:shipit: when ready

**Comment by mourner** [comment]
BTW the build should already include the fix, since ^2.0.0 range in package.json includes 2.0.1.

**Comment by samanpwbb** [comment]
Feel free to close this if you want, I was not thinking about `^` when I submitted this PR. Still might be nice to force the upgrade though since this is a bad bug.

**Comment by lucaswoj** [comment]
Developers of mapbox-gl-js won't get the upgraded package unless they run `npm update` (which I personally don't do regularly). If it fixes a serious bug, bumping the minor version of a dependency is prudent.

**Comment by jfirebaugh** [comment]
:+1: to updating package.json. But feature-filter v2.0.1 _was_ in v0.14.2 right?

**Comment by mourner** [comment]
Yes, it was. Although we need to quickly release 0.14.3 anyway because of a critical bugfix #2168.

**Pull request merged**
