### PR TITLE
Allow users to add CSS classes

### PR DESCRIPTION
**Pull request by infacq**
please refer to https://github.com/mapbox/mapbox-gl-js/issues/2848#issuecomment-231807671

### CODE REVIEW

**Comment by mourner** [comment]
There may be use cases when you want to target the popup instead of internal HTML. However I'm not sure we need a special UI for this. You can already do `popup._container.classList.add('my-class');`, and to make that cleaner, I would rather add a `popup.getContainer` method.

**Comment by infacq** [comment]
@peterqliu create a child an be solve by using setHTML or setDOMContent but you definitely don't have control over anchor tip. To have that, I must have access to inject a class into `.mapboxgl-popup`

@mourner i never knew we can alter it by using plain `js`. But of course it's a bit hacky and not preferable

**Comment by andrewharvey** [comment]
I wanted to try using https://daneden.github.io/animate.css/ to fade in popups and a public API change to Popup allowing custom CSS classes to be added to the popup, would be great, since you could just do `var popup = new mapboxgl.Popup({ classes: 'animated fadeIn' })`.

 * Using setHTML misses the anchor tip, so won't work.
 * Directly overriding the `.mapboxgl-popup` class isn't ideal as in the example above adding the `animated fadeIn` classes is better abstraction.
 * Relying on private `popup._container` I don't like, it's undocumented and subject to change. But a public popup.getContainer would be okay, but the classes option feels much cleaner, simpler and encourages adding your own classes rather than overriding GL JS css which I feel is much cleaner. It seems you need to do this once you add it to the map (otherwise the DOM element doesn't exist?), at first I thought that delay in then setting the classes would be an issue, but it seems to be fine for the `animated fadeIn` classes.

Is supporting a classes option ruled out? If so then as an alternative solution would you likely accept a PR adding the `getContainer` method?

**Comment by jcarenza** [comment]
@mourner I'm using mapbox-gl@0.43.0, and it doesn't appear that `popup._container` exists as a property, or any other methods like `getContainer` or `getElement`...is there another workaround to this issue that you could share?

**Comment by mourner** [comment]
@jcarenza for a workaround, you can use `popup._container` — it should exist as soon as you add it to the map. https://github.com/mapbox/mapbox-gl-js/blob/master/src/ui/popup.js#L256

**Comment by jcarenza** [comment]
Perhaps my use case is a bit different...I'm using it in combination with a Marker:
```javascript
marker = new mapboxgl.Marker(el).setLngLat([lng, lat]).addTo(map)
marker._popup._container.classList.add('my-class')
```
This throws `Uncaught TypeError: Cannot read property 'classList' of undefined`

**Pull request closed without merging**
