### PR TITLE
Create standard benchmark interface

### PR DESCRIPTION
**Pull request by lucaswoj**
This pull request defines a standard benchmark interface.

Having a consistent interface for benchmarks allows us to use the same test runner and, in the future, collect benchmark results in an automated way.

I haven't yet moved the `fps` benchmark over to this new interface. Once I get some :eyes: and :+1: on the spec I'll tackle that. 

cc @ansis @mourner @jfirebaugh

### CODE REVIEW

**Comment by jfirebaugh** [comment]
Looks good, I especially like capturing motivation and quality criteria in the README.

Do you think browser-based benchmarks are the way to go? Would we ever want headless / pure node benchmarks?

**Comment by lucaswoj** [comment]
> Do you think browser-based benchmarks are the way to go? Would we ever want headless / pure node benchmarks?

We should explore headless and pure node benchmarks (especially #1362). The bench interface was designed to accommodate use in headless and pure node environments. For this PR, sticking to browser environments makes the most sense because it is simple and most representative of real-world usage.

**Comment by ansis** [comment]
It would be good to document how access tokens can be set and provided

Other than that, this looks good!

**Comment by lucaswoj** [comment]
One remaining task: I just realized that the env variables won't work for the debug page because it isn't run through browserify. I think it's time to combine the debug server and bench server into one.

**Comment by lucaswoj** [comment]
Fixes #2007

**Comment by mourner** [comment]
Still needs a few minor ESLint fixes.

**Comment by lucaswoj** [comment]
Oops. I could've sworn I had fixed and pushed those.

:eyes:?

**Comment by lucaswoj** [comment]
Fixes #954

**Pull request merged**
