### PR TITLE
Don't append .json to sprite URLs

### LINKED ISSUE #1155: Don't append .json to sprite URLs
Our current sprite interface doesn't require a .json extension, like the rest of Mapbox's REST APIs. We'll either need to make it diverge from the REST custom, or gl-js shouldn't automatically append .json when it looks for sprite metadata json

### PR DESCRIPTION
**Pull request by bhousel**
Don't append .json to sprite URLs (closes #1155)

### CODE REVIEW

**Comment by jfirebaugh** [comment]
This would be a breaking change for any homesteaders that have set up their own sprite server that doesn't support an unsuffixed sprite URL, which we've never documented as a requirement. I think we should WONTFIX #1155, and instead wait for https://github.com/mapbox/mapbox-gl-style-spec/issues/220 to make breaking changes to how sprites are loaded.

**Comment by bhousel** [comment]
This only applies to `mapbox://` urls.  Does that affect homesteaders?

**Comment by jfirebaugh** [comment]
Oh, I see. Still not sure I see the value in making `mapbox://` behave differently. It's not like we'll ever be able to drop `.json` support from the public API, since there are versions out in the wild requiring it.

**Comment by bhousel** [comment]
I seem to be really good at picking WONTFIX things to work on.

**Pull request closed without merging**
