### PR TITLE
Prevent default on mousedown

### PR DESCRIPTION
**Pull request by mourner**
See #2334. Along with #2337, makes point dragging example much smoother.

### CODE REVIEW

**Comment by mourner** [comment]
cc @bhousel @lucaswoj

**Comment by bhousel** [comment]
eh @jfirebaugh was :-1: on this:  https://github.com/mapbox/mapbox-gl-js/issues/1907#issuecomment-171386026

**Comment by mourner** [comment]
Ah, you're right. Let's try to find an alternative fix.

**Comment by bhousel** [comment]
The slowness could be from `getBoundingClientRect` in `DOM.mousePos` triggering layout thrashing.  I know we previously considered this as WONTFIX, but I'll profile the handlers some more this week and, if that's what it is, find a way to cache the container dimensions.

**Comment by mourner** [comment]
@bhousel `getBoundingClientRect` would show up noticeably in the profiler, so I believe this is something else. Need to try `DOM.disableDrag` too...

**Pull request closed without merging**
