### PR TITLE
rename get and getWithoutRemoving method in lru_cache

### PR DESCRIPTION
**Pull request by jingsam**

### CODE REVIEW

**Comment by jingsam** [comment]
Relate to #5645

**Comment by jingsam** [comment]
Ops, I have checked but found no clues on why this PR cause the tests failed.

**Comment by mollymerp** [comment]
@jingsam looks like there was a failure in the lru_cache tests. it was a timeout issue so I restarted the build in case its being flaky. 

```
test/unit/util/lru_cache.test.js .................... 26/27 31s
  LRUCache#setMaxSize
  not ok timeout!
    expired: test/unit/util/lru_cache.test.js
```

**Comment by jfirebaugh** [comment]
`setMaxSize` uses `get` and needed to pick up the rename.

**Pull request merged**
