### PR TITLE
improved dashed lines

### PR DESCRIPTION
**Pull request by ansis**
A new attempt improving dashed lines. Replaces #649

#### no sliding
Dashes no longer slid along the lines as you zoom. Instead they stretch and then reset at every zoom.

#### scaled by width
Dashes size units are now scaled up by the line width. This should make it easier to use dashes that look right at every zoom without creating functions for them. So this is what `"line-dasharray": [1, 1]` looks like at line widths 2, 8, 16:

screen shot 2015-01-16 at 1 55 23 pm screen shot 2015-01-16 at 1 55 52 pm screen shot 2015-01-16 at 1 56 11 pm

If you still need functions, you can use them. They look like this:

```
"line-dash-array": {
    "stops": [ [0, [1.2, 0.8]], [15, [1.7, 0.3]]]
}
```
#### longer patterns

Previously dash arrays could only have on dash length value and one gap length. Dash patterns can now be any length. `"line-dasharray": [5, 1, 1, 1, 1, 1, 1, 1]`:

screen shot 2015-01-16 at 1 50 30 pm

#### round dashes

The ends of the dashes now obey the line-cap layout property, so you can have rounded dashes:

screen shot 2015-01-16 at 2 03 18 pm screen shot 2015-01-16 at 2 04 02 pm

---

Style spec changes: https://github.com/mapbox/mapbox-gl-style-spec/pull/234
Native port: https://github.com/mapbox/mapbox-gl-native/pull/761
Updated tests: https://github.com/mapbox/mapbox-gl-test-suite/pull/12
Style migration: https://github.com/mapbox/mapbox-gl-style-lint/pull/37
Styles: https://github.com/mapbox/mapbox-gl-styles/pull/24

TODO

- [x] update render tests
- [x] style migration scripts, migrate styles. This is going to be tricky for dashes that used to be functions.

### CODE REVIEW

**Comment by nickidlugash** [comment]
@ansis Did we decide to [scale dashes by line-gap-width](https://github.com/mapbox/mapbox-gl-native/commit/4791bac6753e16ef910a47c514e48b355e20295f)? – I think it makes more sense for dashes to always be scaled by line-width (https://github.com/mapbox/mapbox-gl-js/pull/860#issuecomment-69067900).

**Comment by ansis** [comment]
> @ansis Did we decide to scale dashes by line-gap-width? – I think it makes more sense for dashes to always be scaled by line-width (#860 (comment)).

It's implemented, but can easily be reverted. I don't have enough experience to have an opinion about this. @jfirebaugh are you fine with reverting a5fb9f9, or do you still think scaling by gap-width is better?

**Comment by ljbade** [comment]
Love the improvements, particularly the more flexible dash pattern.

**Comment by ansis** [comment]
Updated tests: https://github.com/mapbox/mapbox-gl-test-suite/pull/12
Style migration: https://github.com/mapbox/mapbox-gl-style-lint/pull/37
Styles: https://github.com/mapbox/mapbox-gl-styles/pull/24

remaining:
- [ ] choose whether dash size should be scaled by line-gap-width
- [ ] review (if anyone wants to)

**Comment by jfirebaugh** [comment]
If we always scale by `line-width`, is it still possible to manually scale the values to get exactly aligned casing and fill dashes? I'm worried that float rounding or something will screw that up.

**Comment by nickidlugash** [comment]
> choose whether dash size should be scaled by line-gap-width

My vote is to revert this. @jfirebaugh? 

Can't wait to try out the new dashes!

**Comment by ansis** [comment]
> If we always scale by line-width, is it still possible to manually scale the values to get exactly aligned casing and fill dashes? I'm worried that float rounding or something will screw that up.

Yeah, it seems to work fine.

Outer: `"line-dasharray": [2.5, 1.5, 2.5], "line-width": 2`
Inner: `"line-dasharray": [4.5, 4, 4.5], "line-width": 1`

screen shot 2015-01-20 at 7 38 28 pm

> My vote is to revert this.

Reverted.

**Comment by jfirebaugh** [comment]
@ansis I merged master here but rendering tests are currently failing. Can you take a look?

**Comment by jfirebaugh** [comment]
This will need to be merged to master manually (it's targeting mb-pages, which is no longer correct).

**Comment by ansis** [comment]
@jfirebaugh all render tests are passing for me. Which ones are failing for you? up to date test-suite?

**Comment by jfirebaugh** [comment]
I'm seeing the same error as the [Travis build](https://travis-ci.org/mapbox/mapbox-gl-js/builds/47867236#L1681):

```
# geojson default
/home/travis/build/mapbox/mapbox-gl-js/node_modules/tape/index.js:75
        throw err
              ^
TypeError: Cannot call method 'join' of undefined
    at LineAtlas.getDash (/home/travis/build/mapbox/mapbox-gl-js/js/render/line_atlas.js:21:25)
    at Object.drawLine [as line] (/home/travis/build/mapbox/mapbox-gl-js/js/render/draw_line.js:57:37)
    at GLPainter.drawLayers (/home/travis/build/mapbox/mapbox-gl-js/js/render/painter.js:255:25)
    at GLPainter.drawTile (/home/travis/build/mapbox/mapbox-gl-js/js/render/painter.js:241:10)
    at Object.exports._renderTiles [as render] (/home/travis/build/mapbox/mapbox-gl-js/js/source/source.js:58:17)
    at GLPainter.render (/home/travis/build/mapbox/mapbox-gl-js/js/render/painter.js:231:20)
    at util.extend.render (/home/travis/build/mapbox/mapbox-gl-js/js/ui/map.js:329:22)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

**Comment by ansis** [comment]
my spec was not up to date. Test fixed in 34fc5b4

**Comment by jfirebaugh** [comment]
Merged!

**Pull request closed without merging**
