### PR TITLE
Adding fog transition and moving globe transition to zoom 7-8

### PR DESCRIPTION
**Pull request by SnailBones**
## Launch Checklist

Since globe view does not support fog, fog currently appears abruptly after the transition to Mercator is complete. This PR adds a transition so that after entering Mercator, the fog fades in over the next zoom level. This value is flexible and could be fractional.

### Previous behavior (instant transition):

https://user-images.githubusercontent.com/14878684/154547940-626b9309-27f2-46f0-b2bd-6ad2bdc20b1d.mov

### GLOBE_FOG_TRANSITION_LENGTH = 1:

https://user-images.githubusercontent.com/14878684/154547952-8733d0a0-5f7e-4e38-aa64-1511ec3e0a34.mov

### GLOBE_FOG_TRANSITION_LENGTH = 2:

https://user-images.githubusercontent.com/14878684/154547927-5706e95e-5621-4bec-905c-ce59e44cbf30.mov

 - [X] briefly describe the changes in this PR
 - [x] include before/after visuals or gifs if this PR includes visual changes
 - [x] update all current tests
 - [ ] write test for fog transition
 - [ ] smooth sky transition
 - [X] manually test the debug page
 - [X] tagged `@mapbox/map-design-team` `@mapbox/static-apis` if this PR includes style spec API or visual changes
 - [ ] tagged `@mapbox/gl-native` if this PR includes shader changes or needs a native port
 - [X] apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog'
 
cc @mapbox/map-design-team

### CODE REVIEW

**Comment by karimnaaji** [comment]
cc @willymaps

**Comment by melanieimfeld** [comment]
just passing by, I think my favorite is `GLOBE_FOG_TRANSITION_LENGTH = 2`!

**Review by karimnaaji — COMMENTED** [review]
Code looks good to me, make sure to remove this ignored render test https://github.com/mapbox/mapbox-gl-js/blob/main/test/ignores.json#L45 as well as adding new ones covering this with fog.

**Comment by SnailBones** [comment]
> Code looks good to me, make sure to remove this ignored render test https://github.com/mapbox/mapbox-gl-js/blob/main/test/ignores.json#L45 as well as adding new ones covering this with fog.

@karimnaaji I don't think the behavior that this testing is correctly implemented yet. it doesn't match the current [`expected.png`](https://github.com/mapbox/mapbox-gl-js/blob/main/test/integration/render-tests/globe/globe-transition/horizon-during-transition/expected.png)

On `main` it looks like this:
image


With increased zoom to match the changes in this branch we get this strange appearance:
image

**Comment by karimnaaji** [comment]
>>@karimnaaji I don't think the behavior that this testing is correctly implemented yet. it doesn't match the current [`expected.png`](https://github.com/mapbox/mapbox-gl-js/blob/main/test/integration/render-tests/globe/globe-transition/horizon-during-transition/expected.png)

No, I think it should be enabled and removed from the ignored list to prevent issues, as this part is in active development. There must be something else to fix that makes this strange artifact appear and investigate what is causing that.

**Comment by karimnaaji** [comment]
I checked out this branch and compared the behavior with main:

**main**

https://user-images.githubusercontent.com/7061573/154761111-abdf4a73-e603-4fb2-bcdc-2a22777bb305.mp4

**this PR**

https://user-images.githubusercontent.com/7061573/154761115-c3057c2b-4e6c-4d35-ae4f-8448782e171f.mp4

Maybe something incorrect with the fog opacity triggers that issue when fog is entirely disabled?

**Comment by karimnaaji** [comment]
The issue isn't directly related to this PR, as there's a discontinuity issue in our globe atmosphere shader. It just gets accentuated when we move the transition to a higher value, refer this visualization of the `t` value from https://github.com/mapbox/mapbox-gl-js/blob/main/src/shaders/globe_atmosphere.fragment.glsl#L20. We can create a separate issue to track that and hold on merging that PR until it's fixed.

https://user-images.githubusercontent.com/7061573/154768906-592851a2-6d42-4a8d-9522-faf9acee8f78.mp4

The render test was actually useful in discovering that issue, so we should go ahead with removing it from the ignore list.

**Comment by mourner** [comment]
Are we set on pushing the transition by two zooms? The earlier we transition, the better for performance, so I'd prefer to keep the current transition range even if it comes at the expense of minor visual discrepancies... 

Also note that if we do change the range, render tests that target the transition will need to be updated so that it's still covered.

**Comment by SnailBones** [comment]
> Are we set on pushing the transition by two zooms? The earlier we transition, the better for performance, so I'd prefer to keep the current transition range even if it comes at the expense of minor visual discrepancies...

We've currently discussed changing the transition to this level and wait for customer feedback before making a final decision, which may involve a time-based transition or making the setting user-configurable. I've made some demonstrations [here](https://github.com/mapbox/gl-js-team/issues/352) of what transitions look like at different levels. At high pitch, the transition is quite obvious at zoom level 5-6.

**Comment by karimnaaji** [comment]
Closing this PR in favor of smaller scoped PR #11525 . Concerning fog transition, I have investigated fog support on globe as part of atmosphere styling and this will make the fog transition unnecessary.

**Pull request closed without merging**
