### PR TITLE
fire map load event for subsequent style loads

### PR DESCRIPTION
**Pull request by vicapow**
this fixes https://github.com/mapbox/mapbox-gl-js/issues/1465

### CODE REVIEW

**Comment by jfirebaugh** [comment]
@vicapow Thanks for the PR, however I don't think resetting the `_loaded` flag on any style change event produces the correct semantics -- that event is fired in many situations that _shouldn't_ trigger another load event from the map.

**Comment by vicapow** [comment]
@jfirebaugh good point. and yes, listening for `style.load` would address my use case.

Also, realizing now the description of the map `load` is pretty clear:

> Load event. This event is emitted immediately after all necessary resources have been downloaded and the first visually complete rendering has occurred.

So this change could break existing code that assumes the above will hold true in the future.

**Comment by danielduhh** [comment]
Is there any documentation on this style.load event?
I'm having the same issue.. I want an event to fire when the map has finished loading after I change styles with map.setStyle(). I've tried listening for the map.once('style.load') event, but it refuses to fire

**Comment by bengolder** [comment]
@danielduhh I encountered this same issue, and I added an event listener to `style.load` like this:

```javascript
map.setStyle(newBasemapStyle);
map.style.on('load', function(){
    batchUpdateLayers();
});
```

**Comment by phuongcv1112** [comment]
I saw this was fixed in version 0.24, but it failed in version 0.25 and 0.26,

please help to check!

**Comment by lucaswoj** [comment]
@phuongcv1112 Apologies, this advice was somewhat misleading as it relies on undocumented behavior. We now have a documented & recommended hook for listening for  this event, the [`Map#data` event](https://www.mapbox.com/mapbox-gl-js/api/#Map.event:data).

**Pull request closed without merging**
