### PR TITLE
sort icons and text together so icons can overlap text

### PR DESCRIPTION
**Pull request by xabbu42**
This pull request attempts to fix issue #10002 by sorting the icon and the text part of a symbol together
instead of one after the other. I'm not sure if this is just a bug fix or a change in the style spec. I'm also not
sure if this needs a port to mapbox-gl-native.

Keep in mind when reviewing this pull request that beside of javascript itself I'm not at all familiar
with any of the tech used (i.e. nodejs, webgl, flow etc).

@mapbox/map-design-team @mapbox/static-apis

 - [x] include before/after visuals or gifs if this PR includes visual changes
 - [ ] post benchmark scores
 - [x] manually test the debug page
 - [ ] apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog'

### CODE REVIEW

**Comment by xabbu42** [comment]
Screenshot 2020-11-30 at 18 42 59
Screenshot 2020-11-30 at 18 43 29

This two screenshots show the visual difference for two overlapping symbols. The first is from main and the text of both symbols are visible despite the overlap. The second shows the fix where the icon of the overlapping symbol is drawn over the text.

**Comment by xabbu42** [comment]
Even with a fresh checkout of mapbox-gl-js main I get an error for the SymbolLayout benchmark: TypeError: i.tileID is undefined.

**Comment by xabbu42** [comment]
possibly also fixes #4064

**Comment by shayanaijaz** [comment]
Any updates on this issue or a potential merge?

**Comment by ansis** [comment]
I apologize for the silence here.

Thanks for opening this! https://github.com/mapbox/mapbox-gl-js/issues/10002 is a messy bug to fix. Unfortunately the way this is implemented, it adds more performance overhead and would make some styles significantly slower. Right now we need to prioritize not regressing the performance of those styles over the ideal rendering. This fixes the rendering, and it's unfortunate that we can't merge it.

Since we're not able to move a complete fix forward right now, I'm going to close this. I apologize for not making this call earlier. I'll reopen if we pick this up again.

Thanks!

**Pull request closed without merging**
