### PR TITLE
Preserve expected type when parsing 'let' expressions

### PR DESCRIPTION
**Pull request by ryanhamley**
## Launch Checklist

Fixes https://github.com/mapbox/mapbox-gl-js/issues/7300

### CODE REVIEW

**Comment by ryanhamley** [comment]
Confirmed that the error goes away with this change

screen shot 2018-09-19 at 3 26 28 pm

cc: @ChrisLoer @malwoodsantoro

**Comment by ChrisLoer** [comment]
Awesome! This is a really good candidate for an expression regression test -- you can start from one of the existing "let" tests, and use add a "propertySpec" entry to the test.json to specify the expected type.

**Comment by ryanhamley** [comment]
@ChrisLoer I added a test that's passing. Does that look right to you?

**Comment by ChrisLoer** [comment]
Yeah, that looks right to me! Did you double-check that the test also fails if you revert your change?

You could probably make the test a little more focused/easier to read by getting rid of the nested interpolate? Just one interpolate expression ought to be enough to exercise the functionality. I've also started trying to annotate some of our render/query/expression tests with a "description" field that describes what's going on in the test (in this case something like "'let' should preserve expected type for child expressions. If it didn't, this test case would fail because the expected "color" type would not get passed into the interpolate and the literal strings wouldn't automatically coerce to the color type").

If you think this is ready for review, I'm ready to 🍏.

**Comment by ryanhamley** [comment]
I simplified the test, added a description and confirmed that the test fails if I revert the change in the `let` definition.

**Pull request merged**
