### PR TITLE
Popup on hover example

### LINKED ISSUE #1524: Popular Mapbox.js example: Show tooltips on hover
No. 14 most popular Mapbox.js example by analytics in the past year

https://www.mapbox.com/mapbox.js/example/v1.0.0/show-tooltips-on-hover/

### PR DESCRIPTION
**Pull request by tristen**
- Closes #1524

popup-hover

### CODE REVIEW

**Comment by jfirebaugh** [comment]
Let's get a GL JS patch release out with the fix for #1811 in it so the `Popup` can be reused. I'll do that today.

**Comment by tristen** [comment]
Awesome!

**Comment by jfirebaugh** [comment]
Updated. Looks like `Popup` still has a bug with the arrow positioning not getting reevaluated though:

popup

**Comment by jfirebaugh** [comment]
Fixed in e289cf1488c223acc3ef5c59e416b3f5c76b18bd but we'll need another patch release.

**Comment by mourner** [comment]
This one good to merge too.

**Pull request merged**
