### PR TITLE
add touch-action rules

### LINKED ISSUE #4259: Set `touch-action: none` on the map container
**mapbox-gl-js version**:

### Steps to Trigger Behavior

 1. While using mapbox gl-js on a mobile device or any device that uses (touch) to move the map, an error is thrown due to the event listener being treated as passive. I even looked into this on your own site, it does the same on any mapbox application using the gl-js version.

### Expected Behavior
Move fluid

### Actual Behavior
Moves slow, clunky

### PR DESCRIPTION
**Pull request by mollymerp**
fix #4259

I wasn't able to reproduce the original issue on the google pixel device I was testing with so I have no idea if this solves the problem or not. I'm looking around for another device to test with. 

@indus @IvanSanchez are you able to test this branch to see if it successfully resolves the issue you were seeing? 

## Launch Checklist

 - [ ] briefly describe the changes in this PR
 - [ ] write tests for all new functionality
 - [ ] document any changes to public APIs
 - [ ] post benchmark scores
 - [ ] manually test the debug page

### CODE REVIEW

**Comment by mollymerp** [comment]
Was able to reproduce this on Dan's Pixel and this PR fixed the issue (page reloading on drag down and pinch zoom/rotate probs) 😂

**Comment by indus** [comment]
@mollymerp same here. Fixed my issues when zooming. Thanks!

**Comment by IvanSanchez** [comment]
Can't test right now, but given that the changes look exactly like https://github.com/Leaflet/Leaflet/pull/4552 and we haven't had any more related problems in Leaflet since then, I'm confident this is good. :+1:

**Comment by ourmaninamsterdam** [comment]
@mollymerp I see your fix has been merged to master. Do you know when this will tagged and released?

**Comment by lucaswoj** [comment]
@ourmaninamsterdam We do a release during the first week of each month, barring any major bugs.

**Pull request merged**
