### PR TITLE
Fix canvas size issue when using CSS transform

### PR DESCRIPTION
**Pull request by avpeery**
Issue #11085 demonstrates a regression introduced in v2.5.0. PR #10936 introduced using getBoundingClientRect to obtain the canvas width and height for more precise values; instead of using clientWidth and clientHeight. However, an edge case was discovered that getBoundingClientRect returns its values after CSS transformations. 

In order to fix this issue, offsetHeight and offsetWidth can replace getBoundingClientRect. Though it does not return precise float values, it does take more values into account than the original clientWidth and clientHeight. Read the docs about [offsetWidth](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetWidth).

## Launch Checklist

 - [x] briefly describe the changes in this PR
 - [x] write tests for all new functionality
 - [x] manually test the debug page
 - [x] apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog'
 - [x] add an entry inside this element for inclusion in the `mapbox-gl-js` changelog: `<changelog>Replaces getBoundingClientRect with offsetHeight and offsetWidth to evaluate canvas size values, and fixes issue with using transform CSS properties on the map container.</changelog>`

### CODE REVIEW

**Comment by arindam1993** [comment]
I don't think we want this,
https://stackoverflow.com/questions/21064101/understanding-offsetwidth-clientwidth-scrollwidth-and-height-respectively
this says that `offsetWidth` and `offsetHeight` accounts for borders and scrollbars and the like, which wouldn;t be correct for what we want.

Did you consider using [getComputedStyle()](https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle) to extract the `transfrom`, which should be returned as a [matrix](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/matrix()).

You should be able to extract the scale value from the matrix string (based on the docs its 0th and 3rd elements )

**Comment by avpeery** [comment]
@arindam1993 I replaced it offsetWidth with `parseFloat(window.getComputedStyle(this._container).width)`, updating tests and will push update to PR soon!

**Comment by rreusser** [comment]
I'm not sure what the right solution is, but for the record, `getBoundingClientRect()` is the only method I can find which takes into account CSS transforms. If you get a computed style, the computed CSS width is _without_ transforms. You can query the transform and receive it as a matrix, from which you could compute the bounding box, but that's not done for you.

**Comment by chrisgervang** [comment]
Are there anything edge cases you'd like tested? We could try out proposed changes and share if it fixes our maps.

**Pull request closed without merging**
