### PR TITLE
Fix canvas size to round up to container size

### LINKED ISSUE #9455: Canvas size should be rounding up instead rounding.
The Canvas size is decided by rounded its container size. e.g., 100.3 to 100, 100.7 to 101.
With non-retina, it looks quite okay but with retina display(or with mobile device), the container may have a little empty space on the bottom or right.

when the container size is like this:
image

canvas size is:
image

so, it has empty on the bottom like(right is fine because it's oversized than its container):
image

### PR DESCRIPTION
**Pull request by avpeery**
Closes #9455.

Previous bug demonstrated that canvas pixel size would round down from container size, leaving a small gap between the difference of the two sizes (detectable on some retina and mobile displays as per the issue).  

[clientWidth](https://developer.mozilla.org/en-US/docs/Web/API/Element/clientWidth) and [clientHeight](https://developer.mozilla.org/en-US/docs/Web/API/Element/clientheight) were previously being used to calculate the size for the canvas which as per the documentation always rounds the value to an integer. Replacing these with [getBoundingClientRect()](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect) allows decimal values. 

EDITED LATER TO ADD: All references to clientWidth and clientHeight have been replaced with getBoundingClientRect in this PR. getBoundingClientRect provides a more exact value which will improve accuracy for calculations.

## Launch Checklist

 - [x] briefly describe the changes in this PR
 - [x] write tests for all new functionality
 - [x] manually test the debug page
 - [x] apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog'
 - [x] add an entry inside this element for inclusion in the `mapbox-gl-js` changelog: `<changelog> Rounds canvas size up to container size </changelog>`

### CODE REVIEW

**Comment by rreusser** [comment]
Makes sense. But hmm… the unit tests seem suspiciously far off for a subpixel difference in canvas size. (e.g. 584 --> 72). I wonder if something works differently when this is run in node.

```
test/unit/ui/popup.test.js .......................... 92/99
  Popup is positioned at the specified LngLat in a world copy
  not ok should be equivalent
    --- wanted
    +++ found
     {
    -  "x": 584
    +  "x": 72
       "y": 150
     }
```

I'm also not quite 100% clear on what the original example does. Is the author setting the map to the full page size? Is it possible maybe the burden of scaling the canvas to fill the full page without a gap may be on the developer and not the library?

**Comment by avpeery** [comment]
@rreusser  Thanks for taking a look! The PR is still in progress.. When I use the debug page getBoundingClientRect works but does not work in the tests so it's returning 0 and using the default values instead. I'm currently looking into why this is.

**Comment by rreusser** [comment]
Ah, now I see the draft status. Sorry to jump the gun. Carry on 😄👍

**Comment by avpeery** [comment]
@rreusser Thanks for checking it out though! That is a good thought to discuss though on if it is something we should be handling. I can only "see" this bug when the canvas isn't full-screen (I'm not sure what the specific use-cases are for someone having a canvas not full-screen). I fixed the unit tests (was missing a mock for getBoundingClient Rect). I discussed with @arindam1993 keeping the canvas.style.width and canvas.style.height as fractional values, but rounding up the canvas size.

**Comment by arindam1993** [comment]
Looks good to me @avpeery ! Nice job. Since this changes a bit of behaviour in the interaction between the browser and GL-JS, it would be helpful to be able to test this manually. Especially eventually during when this lands in a future release. Happy to show you how to add a manual testing page.

**Review by arindam1993 — APPROVED** [review]
Looks good to me and the render test output is perfect, it demonstrates that the pixel grid snapping is working along with the rounding up of the image size!

Nice work!

**Pull request merged**
