### PR TITLE
correct bounds for a rotated or tilted map

### PR DESCRIPTION
**Pull request by indus**
see https://github.com/mapbox/mapbox-gl-js/issues/1842

### CODE REVIEW

**Comment by ZhenanH** [comment]
+1

**Comment by ansis** [comment]
@indus thanks for the pull request

@mourner can you review this?

I'm wondering if it would be more useful to change LngLatBounds so that it holds all four corner values.

**Comment by lucaswoj** [comment]
@ansis @mourner What are the next actions for this PR? Do we want to merge it or close it in favor of a solution that changes `LngLatBounds`?

**Comment by ansis** [comment]
I'm in favour of merging and discussing a breaking `LngLatBounds` change separately.

**Comment by ansis** [comment]
I rebased and merged this as https://github.com/mapbox/mapbox-gl-js/commit/6dfd84180b5245cf13a0ad6737d76a20dcf9134e and added a test https://github.com/mapbox/mapbox-gl-js/commit/d50736a6e62c8ae48f7c6928344aca7fa6136e6f

Thanks @indus and sorry about the long wait!

**Comment by indus** [comment]
No problem.

**Pull request closed without merging**
