### PR TITLE
Fix issue #4859: allow loading RTL text plugin before first style load.

### PR DESCRIPTION
**Pull request by ChrisLoer**
Fixes issue #4859: this was a regression I introduced in https://github.com/mapbox/mapbox-gl-js/commit/171db6177a6a5e7246fcef4d74ed297ee5a196d8. Unfortunately I still haven't figured out a good way to exercise this code in our test suite, since it depends on running in the browser. :/

/cc @anandthakker @mollymerp

### CODE REVIEW

**Comment by ChrisLoer** [comment]
@mollymerp I had to hack things up a bit to do the stubbing (I'm not very experienced with Sinon), but I extracted the hard-to-test `createBlobURL` and put in a test that verifies a bogus `pluginBlobURL` gets passed down to the workers. Do you think that makes sense?

**Comment by mollymerp** [comment]
Thanks for adding that test!
Would adding a `calledWith` check to make sure the correct arguments are passed to the test here https://github.com/mapbox/mapbox-gl-js/blob/master/test/unit/style/style.test.js#L59 have caught this specific regression? Sorry if this is a dumb question – I'm not too familiar with the RTL plugin 😬

**Comment by ChrisLoer** [comment]
@mollymerp A `calledWith` check on the original test (https://github.com/mapbox/mapbox-gl-js/blob/master/test/unit/style/style.test.js#L59) wouldn't have worked originally because it didn't have a stubbed out `createBlobURL` (one confusing thing here is that the the URL we ultimately care about is the "blob URL", not the "plugin URL" that gets passed in to `setRTLTextPlugin`). I'll try adding a `setRTLTextPlugin` call to the test now that we've got the stubbing mechanism.

**Comment by ChrisLoer** [comment]
I had to add a `clearRTLTextPlugin` method for the tests to allow both tests to modify the plugin... global singletons don't play well with tests. :/

**Pull request merged**
