### PR TITLE
rotate-controllable marker: add comments, geojson formatting

### PR DESCRIPTION
**Pull request by danswick**
Added a couple of comments and changed `var point` to make it more obvious that it's GeoJSON since it's later added using `mapboxgl.GeoJSONSource()`.

cc: @tmcw, @jfirebaugh

### CODE REVIEW

**Comment by jfirebaugh** [comment]
Is there a reason to use a `Feature` rather than a simple `Point` geometry? They're both perfectly valid GeoJSON.

**Comment by tmcw** [comment]
(also, to totally nitpick, if it is going to be a feature it would need a properties object)

**Comment by danswick** [comment]
After talking with @jfirebaugh, I realized I was confused because (along with some of my own misunderstandings regarding GeoJSON) this doesn't pass [geojsonhint](https://www.mapbox.com/geojsonhint/): 

``` js
{
  type: 'Point',
  coordinates: [-74.50, 40]
}
```

Although technically valid as far as Mapbox GL JS is concerned, I would suggest we try not to use object literals when working with GeoJSON in examples just to keep things consistent. @tmcw and @jfirebaugh, what do you think of a simple change to: 

``` js
{
  "type": "Point",
  "coordinates": [-74.50, 40]
}
```

**Comment by jfirebaugh** [comment]
:+1:

**Pull request merged**
