### PR TITLE
 Move esm to devDependencies

### LINKED ISSUE #8450: esm dependency vunerability
Getting some github alerts while using this lib due to  `"esm": "~3.0.84",`

Screen Shot 2019-07-09 at 4 34 33 PM

Do you think you could give them a bump?

### PR DESCRIPTION
**Pull request by DatGreekChick**
## Launch Checklist

 - [x] briefly describe the changes in this PR
 - [ ] write tests for all new functionality
 - [ ] document any changes to public APIs
 - [ ] post benchmark scores
 - [ ] manually test the debug page
 - [ ] tagged `@mapbox/studio` and/or `@mapbox/maps-design` if this PR includes style spec changes
 - [ ] tagged `@mapbox/gl-native` if this PR includes shader changes or needs a native port

@ryanhamley @mourner @asheemmamoowala 

I moved `esm` to `devDependencies` ~and ran `yarn install` to update the `yarn.lock` file~.

Using `yarn` removed any errors with tests that I was having previously in #8513 due to `npm` - thanks for that! I saw the docs, but didn't realize it would have this type of impact.

CLOSES #8450

### CODE REVIEW

**Comment by DatGreekChick** [comment]
Hey @ryanhamley! I updated my `yarn` version to 1.17.3 as well. I'm using `node` v11.6.0, though. I still see some changes to `yarn.lock`, but now the entire diff is 122 lines:

```
Elenis-MacBook-Pro : ~/mapbox-gl-js  (other/move-esm-to-dev-dependency)
🤓  git diff | wc -l
     122
```

**Comment by DatGreekChick** [comment]
Ok... that didn't actually work like I expected given my bash output 🤣
It's either because I'm using a higher version of `node` (I suspect this isn't it) or simply because when I run `yarn install` it's updating the minor versions if there are any new ones with packages using `^`.

**Comment by asheemmamoowala** [comment]
@DatGreekChick Could you rewrite your commit without the `yarn.lock` file?

**Comment by DatGreekChick** [comment]
@asheemmamoowala will do 👍

**Comment by DatGreekChick** [comment]
@asheemmamoowala I removed the `yarn.lock` file from the commit

**Comment by asheemmamoowala** [comment]
@mapbox/gl-native Do you still depend on `esm` from the gl-js package for running integration tests? If not, we'd like to get this PR merged

**Comment by mourner** [comment]
@asheemmamoowala looks like Native has `esm` [in their devDeps](https://github.com/mapbox/mapbox-gl-native/blob/master/package.json#L28), so we're safe to move to `devDeps` as well.

**Comment by DatGreekChick** [comment]
@ryanhamley can you dismiss your review?

**Pull request merged**
