### PR TITLE
Fix bad if statement in vector_tile_work_souce

### LINKED ISSUE #5005: Code bug in vector_tile_source
There is a bug that might lead to worker number 0 not being utilized properly.
```javascript
if (!tile.workerID || tile.state === 'expired') {
   tile.workerID = this.dispatcher.send('loadTile', params, done.bind(this));
} else if (tile.state === 'loading') {
   // schedule tile reloading after it has been loaded
   tile.reloadCallback = callback;
} else {
   this.dispatcher.send('reloadTile', params, done.bind(this), tile.workerID);
}
```
If the worker is assigned index 0, it will never be re-utilized for reloading. I believe the tile will constantly be loaded instead of reloaded if it was being handled by worker 0.
Correct if statement should be `if (tile.workerID !== undefined && tile.workerID !== null ... )`

### PR DESCRIPTION
**Pull request by sanjin-saric**
Closes #5005

### CODE REVIEW

**Comment by mollymerp** [comment]
great! thank you!

I think we also need to change the condition here https://github.com/mapbox/mapbox-gl-js/blob/master/src/source/geojson_source.js#L188

would you be able to add some unit tests that check for this error?

**Comment by sanjin-saric** [comment]
Sure. Will do.

**Comment by mollymerp** [comment]
@sanjin-saric do you think you'll have time to add the requested changes and rebase this PR? If not I'd be happy to wrap it up for you. 

Thanks!

**Comment by sanjin-saric** [comment]
i was on vacation and I couldn't find time to finish this up. I'll try to wrap this up within a week.

**Comment by sanjin-saric** [comment]
I fixed GeoJSON source but I do not know how to write test for this. I cannot write a test that tests the validity of code.

**Pull request merged**
