### PR TITLE
Disable scroll zoom example

### PR DESCRIPTION
**Pull request by mannylopez**
@lyzidiamond can I get your :eyes: to post this example? Thanks!

### CODE REVIEW

**Comment by lyzidiamond** [comment]
I can look but I would prefer @lucaswoj or @jfirebaugh eyes!

**Comment by lucaswoj** [comment]
The code looks good to me. My only reservation is that we should document this method (#1497) before/soonthereafter merging this example.

**Comment by lucaswoj** [comment]
@mannylopez Are you up for adding a jsdoc comment to `ScrollZoom#disable` as part of this PR?

**Comment by mannylopez** [comment]
I'm up for taking a stab at it @lucaswoj. @lyzidiamond walked me through how to do this earlier in the week.

**Comment by lucaswoj** [comment]
Perfect timing, then! :tada: 

I’ll hit https://github.com/mapbox/mapbox-gl-js/issues/1497 and https://github.com/mapbox/mapbox-gl-js/issues/2069 in the next couple days to round things out.

**Comment by lucaswoj** [comment]
@mannylopez I just hit the docs in https://github.com/mapbox/mapbox-gl-js/pull/2088. I'd love your :eyes: on that PR! Feel free to merge this one whenever.

**Pull request merged**
