### PR TITLE
update exports._queryRenderedVectorFeatures

### PR DESCRIPTION
**Pull request by gertcuykens**
Check if map is loaded. (https://github.com/mapbox/mapbox-gl-js/issues/2614)

### CODE REVIEW

**Comment by lucaswoj** [comment]
The CI failure should be fixed by #2610. Can you rebase and re-push? Thanks!

**Comment by lucaswoj** [comment]
Happy to merge this with the addition of a unit test 😄 Thank you!

**Comment by gertcuykens** [comment]
Ok but where does the current `queryRenderedVectorFeatures` get tested so I can figure out how to do it?

Don't find it in https://github.com/mapbox/mapbox-gl-js/tree/master/test/js/source

**Comment by lucaswoj** [comment]
I'll take care of the tests! Thanks @gertcuykens! Continued in #2621. (I'll make sure you get commit credit)

**Pull request closed without merging**
