### PR TITLE
[not ready] apply Math.round for tile loading

### PR DESCRIPTION
**Pull request by peterqliu**
- [ ] update tests

cc/ @jfirebaugh

### CODE REVIEW

**Comment by jfirebaugh** [comment]
@peterqliu This needs to be conditional on whether it's a raster tile or not. Vector tiles are dense for `Math.round`.

**Comment by 1ec5** [comment]
@peterqliu, does 1744e5837bde859383f0ecfb9e7af122e62a7943 look reasonable to you?

**Comment by peterqliu** [comment]
Looks good, given my cursory familiarity. @ansis wanna take a pass, since @jfirebaugh is out?

**Comment by ansis** [comment]
Looks good! squashed and merged

**Pull request merged**
