### PR TITLE
Prevent elementGroups null value errors

### LINKED ISSUE #1933: Fix "TypeError: Cannot read property 'circle' of undefined" error
@mourner hit this bug at https://github.com/mapbox/mapbox-gl-js/commit/5739dd09a1216770984d512a390074046fa2c7d9

I just hit the same bug with @kelvinabrokwa by using the `mapbox-gl-draw` plugin on `mapbox-gl-js@master`.

cc @ansis @bhousel @jfirebaugh @kelvinabrokwa @mourner

### PR DESCRIPTION
**Pull request by lucaswoj**
fixes #1933 

cc @mourner @kelvinabrokwa @ansis

### CODE REVIEW

**Comment by lucaswoj** [comment]
# Next Steps

 - [ ] How can we test for regressions?
 - [ ] Should we publish a new release when this lands?

**Comment by bhousel** [comment]
> Should we publish a new release when this lands?

I think this is important enough that we should do a new release.. I was hitting it a lot today in testing anything with circles.

**Comment by lucaswoj** [comment]
Confirm the fix, merge, and release at will.

**Comment by bhousel** [comment]
> Confirm the fix, merge, and release at will.

Looks good - this fixes the crashes I see in the jsfiddle on #1892

**Comment by bhousel** [comment]
merged as b24b6a1

**Pull request closed without merging**
