### PR TITLE
In-browser polygon tesselation

### LINKED ISSUE #682: tesselate polygons instead of rendering with stencil buffer
We should draw polygons by tesselating them instead of using the stencil buffer trick. Native already does this. https://github.com/mapbox/mapbox-gl-js/commit/7b353122b46503b57e6d5073184883c1c2e21404 is a first attempt that uses libtess.js. Rendering is faster but the tesselation is slow. The buildings layer can take up to 500ms to tesselate.

- take a look at poly2tri.js (which only accepts simple polygons)
- revisit tesselating polygons in the tiles

### PR DESCRIPTION
**Pull request by mourner**
Closes #682. Not ready yet. To do:

- [x] implement holed polygon -> single ring polygon conversion algorithm as described in FIST paper
- [x] implement outer/inner rings classification
- [x] ditch libtess code completely
- [x] fix artifacts on some complex water polygons
- [x] make triangulation code a separate repo https://github.com/mapbox/earcut
- [x] fix fill antialiasing @ansis 
- [x] fix fill patterns @ansis 
- [x] try out indexed vertices approach and see if it improves performance @ansis 
- [x] wait for https://github.com/mapbox/mapnik-vector-tile/issues/59 and ditch ring classification code to fix low-zoom water bleeding artifacts
- [x] make sure there are no other glaring artifacts browsing through the map
- [x] fix tests

### CODE REVIEW

**Comment by mourner** [comment]
@ansis you can try out the indexed approach using earcut `indexed` branch. https://github.com/mapbox/earcut/pull/5 Lets do it in a separate `earcut-indexed` branch.

Earcut returns `{vertices: [...], indices: [...]}` object. Vertices is a flat JS array. You can turn it into a typed one with e.g. `new Int16Array(vertices)`.

**Comment by jfirebaugh** [comment]
@mourner Modulo fixing the tests, is this good to merge as-is, leaving investigation of the indexed approach as a follow-up ticket?

**Comment by mourner** [comment]
@jfirebaugh no, https://github.com/mapbox/mapnik-vector-tile/issues/59 is a blocker — we need to ditch unreliable ring classification hack, otherwise low zoom levels (<7) are completely broken.

**Comment by jfirebaugh** [comment]
Is that something we need to worry about for user supplied GeoJSON as well?

**Comment by mourner** [comment]
@jfirebaugh no, because GeoJSON spec explicitly defines the first ring as outer and other rings as holes for each polygon, and differentiates between polygons in a multipolygon.

**Comment by ansis** [comment]
@mourner It looks like -native already assumes winding order is clockwise for outer rings and counterclockwise for holes: https://github.com/mapbox/mapbox-gl-native/blob/47966a143176a337733fe63b4121d2d00c48359a/src/mbgl/renderer/fill_bucket.cpp#L98

Is fixing the order of rings all that we need? https://github.com/mapbox/mapnik-vector-tile/issues/59#issuecomment-70696468

Do we also need better clipping/unioning in the vector tiles?

**Comment by mourner** [comment]
@ansis we need to try this. It may produce incorrect ring classification sometimes due to degeneracies — points can belong to several rings at once. This problem is solved by doing a union in native, but we can't afford operations like this in JS because they're expensive (probably more expensive than triangulation).

Once we can classify rings reliably, cleaner geometries (union, etc. https://github.com/mapbox/mapnik-vector-tile/issues/53) will be nice to solve minor artifacts on bad data, but not a blocker.

**Comment by mourner** [comment]
I'll probably squash the PR into 2 commits, the first one and the rest. Such a mess currently after all the conflicting rebases...

**Comment by mourner** [comment]
-> https://github.com/mapbox/mapbox-gl-js/pull/1606

**Pull request closed without merging**
