### PR TITLE
added support for enum type in style-spec as per #6116

### PR DESCRIPTION
**Pull request by jay-manday**
## Launch Checklist

I added support for Enum types in the style spec as requested by @samanpwbb in #6116, this feels right but if anyone sees anything funky please lmk! 👍 

 - [x] briefly describe the changes in this PR
 - [x] write tests for all new functionality
 - [x] document any changes to public APIs
 - [x] manually test the debug page

### CODE REVIEW

**Comment by anandthakker** [comment]
Thanks for contributing, @jay-manday !

This PR adds an `enum` type to the _expression_ type system, but (at least for now), we've chosen to treat enums as strings during expression evaluation.  So while, for example, `line-join` is defined in the _style specification_ as an enum, an expression for `line-join` would just be typed `string`.

I believe @samanpwbb 's intent in #6116 was that the enum type that's used for various properties in the style specification should be listed in the documentation page under "Types".

Sorry for the confusion!

**Comment by jay-manday** [comment]
@anandthakker, of course! n_n

ahhhh I see, I see, no worries! Thanks for explaining, I think I read to deeply into your comment on #5438 mentioning how the docs are generated from the style spec. I'll reset this branch and push the changes @samanpwbb wanted :)

**Comment by jfirebaugh** [comment]
Hold off on that too actually -- we removed enums there intentionally. See #5577 and #5578.

**Comment by jay-manday** [comment]
ahhh gotcha sounds good

**Pull request closed without merging**
