### PR TITLE
fix data driven line width and gap

### PR DESCRIPTION
**Pull request by ansis**
Lines weren't getting drawn correctly if they had
- a data driven line-gap-width
- a data driven line-width with a nonzero line-gap-width

This fixes those cases.

@lucaswoj

### CODE REVIEW

**Comment by lucaswoj** [comment]
Looks good overall. Do you know if `mapbox-gl-test-suite` caught this error?

**Comment by ansis** [comment]
No, because the test-suite doesn't have any data driven tests yet. We should add lots of those

**Comment by lucaswoj** [comment]
Ya, being tracked in https://github.com/mapbox/mapbox-gl-test-suite/issues/29.

If this fixes the problem for you, :shipit: 

cc @jfirebaugh

**Comment by jfirebaugh** [comment]
:+1:

**Comment by jfirebaugh** [comment]
@ansis Even after applying this, `line-dasharray` test cases in the test suite are still failing.

**Comment by jfirebaugh** [comment]
Oh, never mind, I thought this included a dasharray-related change and it doesn't.

**Comment by jfirebaugh** [comment]
However, `npm run test-suite` before this PR:

```
    90 failed, 160 passed assertions.
```

And after:

```
    93 failed, 157 passed assertions.
```

**Comment by lucaswoj** [comment]
Newly failing test suite cases are 

 - line-color function
 - line-gap-width literal
 - line-gap-width constant
 - line-gap-width function

**Pull request merged**
