### PR TITLE
Rationalize map view method options

### LINKED ISSUE #1051: setView should use current zoom, bearing, pitch if undefined
From https://github.com/mapbox/mapbox-gl-js/pull/1049#discussion_r25761481

> This starts to get pretty inconvenient... Lets have setView use current zoom, bearing and pitch if undefined.

### PR DESCRIPTION
**Pull request by jfirebaugh**
* Map#setView is replaced with Map#jumpTo.
* Map#jumpTo, Map#easeTo, and Map#flyTo now all accept the
  same set of view options.

Fixes #1051

### CODE REVIEW

**Comment by jfirebaugh** [comment]
@tmcw @mourner Look good?

**Comment by tmcw** [comment]
:+1: looks good to me, though there should be a tail ticket for matching this on native.

**Comment by jfirebaugh** [comment]
Covered by https://github.com/mapbox/mapbox-gl-native/issues/256.

**Comment by mourner** [comment]
:+1:

**Pull request closed without merging**
