### PR TITLE
added mouseover event handler

### PR DESCRIPTION
**Pull request by jay-manday**
Hi there,

I added an event handler for mouseover as requested in #3217. I ran the test suite and everything checks out, fairly new to contributing to open source and would love some feedback!

I've been really enjoying working and learning with mapbox on creative projects like printmaking and custom map vis. Thought it would be a fun learning experience to make some pr's! 🎊 

Cheers!
-Jason 

## Launch Checklist

 - [x] briefly describe the changes in this PR
 - [x] write tests for all new functionality
 - [x] document any changes to public APIs
 - [ ] manually test the debug page
 - [ ] post benchmark scores

### CODE REVIEW

**Comment by jay-manday** [comment]
Thanks @mourner! :seedling: :tada: Yeaa I was thinking about that as well, I decided to borrow it from `mousemove` so that it would be specified to the desired dom node on default. I can splice that into a separate function on a future issue/pr request though! 👍

**Comment by jay-manday** [comment]
Apologies for the noise on this pull request!

I was working on another issue and realized I had merged it to the same branch I was working on. 
I went back and reverted that commit to keep things clean on this PR. 😅

**Comment by mourner** [comment]
No worries! BTW, you can force-push to the branch with the original commit hash instead of reverting.

**Comment by jay-manday** [comment]
mmmh good to know! Will deff keep that in mind.

**Pull request merged**
