### PR TITLE
pass GeoJSON in stringified form

### PR DESCRIPTION
**Pull request by mourner**
This is a reapplication of #2001 without changing the API, and serves as the middle ground for improving `setData` performance as discussed in #1504.

cc @lucaswoj @jfirebaugh @dcervelli

### CODE REVIEW

**Comment by jfirebaugh** [comment]
Given http://nolanlawson.com/2016/02/29/high-performance-web-worker-messages/ I wonder if we should just build `JSON.stringify` / `JSON.parse` into `Actor`.

**Comment by mourner** [comment]
@jfirebaugh I thought about that, but it's tricky because of transferables — you don't want to stringify an array buffer.

**Comment by jfirebaugh** [comment]
Yeah, it would have to be only if the `buffers` argument to `send` is undefined.

**Comment by lucaswoj** [comment]
I'm :+1: on shipping this as-is and continuing to optimize per #1504 :shipit:

**Pull request merged**
