### PR TITLE
[MAPSNAT-799] fix terrain wireframe with exaggeration

### PR DESCRIPTION
**Pull request by alexey-romanov**
## Launch Checklist

 - [x] briefly describe the changes in this PR
 - [x] include before/after visuals or gifs if this PR includes visual changes
 - [ ] write tests for all new functionality
 - [ ] document any changes to public APIs
 - [ ] post benchmark scores
 - [ ] manually test the debug page
 - [ ] tagged `@mapbox/map-design-team` `@mapbox/static-apis` if this PR includes style spec API or visual changes
 - [ ] tagged `@mapbox/gl-native` if this PR includes shader changes or needs a native port
 - [x] apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog'
 - [ ] add an entry inside this element for inclusion in the `mapbox-gl-js` changelog: `<changelog></changelog>`

### CODE REVIEW

**Comment by alexey-romanov** [comment]
Terrain wireframe material for some reason had wireframe offset multiplied by squared skirt height, which caused the wireframe to be totally out-of-sync with actual rendered terrain.

Removing the unnecessary offset multipliers.

Before:


https://user-images.githubusercontent.com/1542101/207604484-f698361a-8d4a-43cc-b8f7-3543ae303313.mov

After:


Screenshot 2022-12-14 at 15 13 43

**Review by karimnaaji — APPROVED** [review]
Good catch :+1: LGTM % CI

**Comment by alexey-romanov** [comment]
> Good catch 👍 LGTM % CI: some render tests may need their baseline to be regenerated https://output.circle-artifacts.com/output/job/53e83ae0-e44e-4fa7-bfbc-42d319f10dbf/artifacts/0/test/integration/render-tests/index.html

Render tests regeneration done

**Review by SnailBones — APPROVED** [review]
Looks like this test is still failing on CI, probably because of a difference in rendering between environments (Likely MacOS vs Linux).

image

IMO in this case it's probably ok to raise the test's "allowed" value. In general that's higher than we'd want, but this feature doesn't affect customers and a less accurate test seems preferable to removing the test entirely.

**Pull request merged**
