### PR TITLE
Add symbol-z-order symbol layout property to style spec

### PR DESCRIPTION
**Pull request by ryanhamley**
## Launch Checklist

 - [x] briefly describe the changes in this PR
    - Adds symbol-sort-by-y symbol layout property to style spec
    - closes https://github.com/mapbox/mapbox-gl-js/issues/7076
    - Native port: https://github.com/mapbox/mapbox-gl-native/pull/12783
 - [x] write tests for all new functionality
 - [x] document any changes to public APIs
 - [x] manually test the debug page
 - [x] tagged @mapbox/studio and/or @mapbox/maps-design if this PR includes style spec changes

### CODE REVIEW

**Comment by ryanhamley** [comment]
See https://github.com/mapbox/mapbox-gl-js/issues/7076 for background on this PR.

I can think of two alternatives to adding a new style spec property.

1) We can make this a runtime setting.
    - Downside: I don't think it makes much sense semantically and organizationally since the sorting only applies to symbols, not all layers on a map. Disabling this sorting is closely linked to the existing style spec symbol layout properties `*-allow-overlap` and `*-ignore-placement` so it's logical to include this as another style spec property.

2) We could push forward with adding a mechanism such as some expression syntax to allow for generalized manual sorting of all feature types as discussed in https://github.com/mapbox/mapbox-gl-js/issues/4361.
    - Downside: This is significantly more work and possibly overkill for this particular use case.

The downside of this PR's approach obviously is a new property on the style-spec which is something we have to be prepared to maintain for awhile. If/when #4361 is implemented, does this feature become obsolete? I feel like symbol sorting by y is a specialized case that users may want a simple way to disable even if they plan on doing further sorting. And of course this concern assumes we eventually implement general sorting.

Two further thoughts/questions:

1) Is `symbol-sort-by-y` an appropriate name or would we prefer something more descriptive like `sort-overlapping-symbols` (which doesn't specify *how* the symbols are sorted).

2) Is the description of the property in `v8.json` accurate and informative enough for users? And is it true that non-skeumorphic icons won't benefit from symbol sorting and are therefore good candidates for `symbol-sort-by-y: false`?

Tagging Carto and Studio into this discussion: @nickidlugash @samanpwbb

**Comment by samanpwbb** [comment]
Overall approach looks good to me. I think it's fine to make this a new spec property since it's a  straightforward boolean. if/when we take on #4361 we can deprecate or de-emphasize the property.

> Is symbol-sort-by-y an appropriate name or would we prefer something more descriptive like sort-overlapping-symbols (which doesn't specify how the symbols are sorted).

What about `sort-relative-to-viewport`? I find `sort-by-y` a little unclear - I needed to read the description to understand what it meant.

**Comment by ryanhamley** [comment]
Renamed `symbol-sort-by-y` to more descriptive `symbol-sort-relative-to-viewport`

**Comment by ryanhamley** [comment]
screen shot 2018-08-31 at 4 38 12 pm

**Comment by jfirebaugh** [comment]
Let's make this `symbol-z-order`, an enum-valued property with possible values `"viewport-y"` and `"source"`. That gives us the flexibility to extend the property with other options. (I can imagine a request for `"map-y"` for example.)

**Comment by samanpwbb** [comment]
> Let's make this symbol-z-order, an enum-valued property with possible values "viewport-y" and "source". That gives us the flexibility to extend the property with other options. (I can imagine a request for "map-y" for example.)

I like this option 👍

**Comment by ryanhamley** [comment]
Yep. Makes sense. I'll change this and the native PR over to `symbol-z-order`.

**Comment by ryanhamley** [comment]
Ah yeah. I think most front end developers will understand it pretty intuitively as being analogous to the CSS z-order property though.

**Pull request merged**
