### PR TITLE
Bublé / ES6

### PR DESCRIPTION
**Pull request by jfirebaugh**
Refs #3368

### CODE REVIEW

**Comment by mourner** [comment]
This looks great, I'm excited! Two things to keep in mind:

- Uglifyify currently seems not to work properly with Bubleify, with a pending fix here https://github.com/hughsk/uglifyify/pull/48 (not sure why it's still not merged)
- Bubleify currently uses Buble 0.12, but there's 0.14 already, so it needs to be updated (in particular, destructuring assignment landed after 0.12) https://github.com/garthenweb/bubleify/issues/7

**Comment by jfirebaugh** [comment]
@mourner We're using `minifyify` rather than `uglifyify` though. I'll check well source maps are working on this PR (they seem to be broken about 90% of the time for me regardless of toolchain).

Besides destructuring assignment, which would be nice but not essential, are there important fixes from 0.12 ⇢ 0.14?

**Comment by jfirebaugh** [comment]
My test case for source maps is as follows:

1. `rm -rf node_modules && yarn install && npm run build-min && jekyll serve`
2. Open http://127.0.0.1:4000/mapbox-gl-js/examples/
3. Open developer tools to "Sources" tab
4. ⌘-O, open `vector_tile_source.js`
5. Set a breakpoint on [the first line of `loadTile`](https://github.com/mapbox/mapbox-gl-js/blob/8fb8a9af2fe184bafc5bd249f84f6f7e032fe6bb/js/source/vector_tile_source.js#L52)
6. Refresh the page

Expected result is that the debugger stops at the breakpoint, in `vector_tile_source.js` (not in concatenated or minified source code), with correct stack and local variable names.

Current status on `master` is that at step 5, setting the breakpoint fails: when I click the sidebar at that line, the breakpoint instead gets set at [this line](https://github.com/mapbox/mapbox-gl-js/blob/8fb8a9af2fe184bafc5bd249f84f6f7e032fe6bb/js/source/vector_tile_source.js#L77). So, source maps for the production build are already broken. (This has pretty consistently been my experience across a variety of libraries and build toolchains -- source maps for minified code just don't really seem to work.)

For the `build-dev` version and http://localhost:9966/debug/, this test case does work as expected.

No change to this status quo on the `bublé` branch.

**Comment by jfirebaugh** [comment]
# Benchmarks

## map-load

**master 57af5e3:** 288 ms
**bublé 3542376:** 110 ms

## style-load

**master 57af5e3:** 143 ms
**bublé 3542376:** 135 ms

## buffer

**master 57af5e3:** 1,072 ms
**bublé 3542376:** 1,040 ms

## fps

**master 57af5e3:** 60 fps
**bublé 3542376:** 60 fps

## frame-duration

**master 57af5e3:** 7.7 ms, 0% > 16ms
**bublé 3542376:** 7.3 ms, 0% > 16ms

## query-point

**master 57af5e3:** 1.01 ms
**bublé 3542376:** 1.16 ms

## query-box

**master 57af5e3:** 90.88 ms
**bublé 3542376:** 89.12 ms

## geojson-setdata-small

**master 57af5e3:** 9 ms
**bublé 3542376:** 7 ms

## geojson-setdata-large

**master 57af5e3:** 94 ms
**bublé 3542376:** 99 ms

**Pull request merged**
