### PR TITLE
Remove React from benchmark view page

### PR DESCRIPTION
**Pull request by andycalder**
This PR removes React and renders the benchmark page with D3. This lets us drop four dependencies (`react`, `react-dom`, `eslint-plugin-react` and `htm`) that are only used for this one file. Previous discussion here: https://github.com/mapbox/mapbox-gl-js/pull/10343#pullrequestreview-579578678

@mourner what do you think?

 - [x] briefly describe the changes in this PR

### CODE REVIEW

**Comment by andycalder** [comment]
You can't use the benchmark page to compare against the latest release at the moment since the ["latest" endpoint](https://api.github.com/repos/mapbox/mapbox-gl-js/releases/latest) points to the latest style spec release instead of the main library. I guess this is a separate issue. Comparing against main works fine.

**Comment by andycalder** [comment]
Hmm, I'm not sure why that test is failing CI since its passing locally.

**Comment by mourner** [comment]
@andycalder seems like just a flaky test — filed #10364.

**Review by mourner — CHANGES_REQUESTED** [review]
This looks great overall — thank you! Needs rebasing / resolving conflicts after #10367, but otherwise good to merge.

**Comment by andycalder** [comment]
Thanks. I rebased/resolved and now there's a query test that's passing locally and failing CI. Any Ideas?

**Comment by mourner** [comment]
The failing tests are https://github.com/mapbox/mapbox-gl-js/issues/10383, not sure what's causing that but definitely not related to the changes in the PR.

**Review by mourner — APPROVED** [review]

**Comment by mourner** [comment]
Personally I find the new d3-only code much easier to follow. And getting rid of dependencies feels great! Thanks so much again for working on this.

**Comment by andycalder** [comment]
Great! Happy to help

**Pull request merged**
