### PR TITLE
bump geojson-vt to 2.2.0

### LINKED ISSUE #2704: Multipolygons disappearing from map at certain zoom levels.
I have a TopoJSON map of europe which I'm loading into mapbox (0.19.1). I have an issue where one of my country layers (Spain) disappears at certain zoom levels. I think this could also be an earcut issue  (similar to https://github.com/mapbox/mapbox-gl-js/issues/2657) as the issue is not present in 0.18.0.

See the attached gif

choro

### PR DESCRIPTION
**Pull request by mourner**
Closes #2704.

### CODE REVIEW

**Comment by mourner** [comment]
Needs updated GeoJSON fixtures in test-suite because of a different ring winding order. :(

**Comment by lucaswoj** [comment]
I pinned master to 2.1.8 pending a fix to the GeoJSON test fixtures.

**Comment by mourner** [comment]
Needs PRs to:

- [ ] mapbox-gl-test-suite (updated query tests for polygons)
- [ ] geojson-vt-cpp (port the change)
- [ ] mason (publish newer geojson-vt-cpp)
- [ ] mapbox-gl-native (newer geojson-vt-cpp version)

**Comment by mourner** [comment]
@jfirebaugh suggested just rewinding input polygons in fixtures so that native has the same results without changing geojson-vt-cpp (which is not necessary), and maybe adding a non-matching winding order test that is disabled in native.

**Comment by andrewharvey** [comment]
Also closes https://github.com/mapbox/mapbox-gl-js/issues/2616

**Pull request merged**
