### PR TITLE
include tile weight in tile debug

### PR DESCRIPTION
**Pull request by andrewharvey**
## Launch Checklist

 - [x] briefly describe the changes in this PR

screenshot from 2019-02-28 13-19-06

Include file size of tiles in tile debug.

It's okay if this isn't merged, but I found it useful...

If it's acceptable to include, I'll try to fix up the failing checks.

 - [ ] write tests for all new functionality
 - [ ] document any changes to public APIs
 - [ ] post benchmark scores
 - [x] manually test the debug page

### CODE REVIEW

**Comment by mourner** [comment]
Nit: can you also shift the center of the render test so that it includes the new info?

**Comment by andrewharvey** [comment]
> Nit: can you also shift the center of the render test so that it includes the new info?

Sure. The new tile size info is still showing up in the bottom left of the existing render test, so the test works, nonetheless I've repositioned it to the center so it's more obvious.

**Comment by mourner** [comment]
Oops, the render test failed :(

**Comment by andrewharvey** [comment]
Yikes, it passes for me locally, and all files are committed and pushed. :confused: 

```
> yarn run test-render debug/tile
yarn run v1.13.0
warning ../../package.json: No license field
$ node --max-old-space-size=2048 test/render.test.js debug/tile
This page appears to be missing CSS declarations for Mapbox GL JS, which may cause the map to display incorrectly. Please ensure your page includes mapbox-gl.css, as described in https://www.mapbox.com/mapbox-gl-js/api/.
* passed debug/tile-overscaled
* passed debug/tile
2 passed (100.0%)
Results at: mapbox-gl-js/test/integration/render-tests/index.html
Done in 3.28s.
```

**Comment by mourner** [comment]
@andrewharvey it's because of some antialiasing differences: https://38787-8629417-gh.circle-artifacts.com/0/root/mapbox-gl-js/test/integration/render-tests/index.html — not sure how to go about this one... Maybe experiment more with the coordinates, or up the tolerance diff (which is fine for a debug test).

**Comment by andrewharvey** [comment]
> @andrewharvey it's because of some antialiasing differences: https://38787-8629417-gh.circle-artifacts.com/0/root/mapbox-gl-js/test/integration/render-tests/index.html — not sure how to go about this one... Maybe experiment more with the coordinates, or up the tolerance diff (which is fine for a debug test).

Thanks! Tweaking the coordinates did the trick.

**Pull request merged**
