### PR TITLE
Animate point along route example

### PR DESCRIPTION
**Pull request by tristen**
animate-marker

cc @jfirebaugh @lucaswoj for review

### CODE REVIEW

**Comment by jfirebaugh** [comment]
Is this concealing the great circle vs. rhumb line difference via strategic choice of endpoints, or did you find another way to resolve that?

**Comment by tristen** [comment]
> Is this concealing the great circle vs. rhumb line difference via strategic choice of endpoints, or did you find another way to resolve that?

Ahh you got me. point placement was strategic to avoid that. I wanted to avoid getting to complex here by adding code that just draws a linear point from one to the other.

**Comment by jfirebaugh** [comment]
I think it's important that the example work for reasonable real-world modifications. How about adapting [this example](https://www.mapbox.com/mapbox.js/example/v1.0.0/arcjs/) and drawing the line as a great circle arc?

**Comment by peterqliu** [comment]
@tristen since you're using turf to calculate transitional position anyway for the animation, you can use those waypoints to draw the linepath itself. Calculate once, draw the line, animate markers to new positions on the line.

I believe that achieves the same thing as arc.js, but with simpler control of increment distance (km/miles vs fractions of the whole).

**Comment by tristen** [comment]
Okie dokie updated to draw an arc first then animate a point along it:

animate-point-along-route-example

**Comment by jfirebaugh** [comment]
👍

**Comment by tristen** [comment]
https://github.com/mapbox/mapbox-gl-js/commit/ce48e3ef36d0ecec009a5ccf12f0b6b19723d8d7

**Pull request closed without merging**
