### PR TITLE
Added live GeoJSON example

### LINKED ISSUE #1641: Build 'live GeoJSON' example
Per chat w/ @jfirebaugh and several user requests to me and @geografa, let's build an example for the API page that shows how to replicate https://www.mapbox.com/mapbox.js/example/v1.0.0/live-data-marker/ in GJ-JS using setData on a timer.

cc/ @lucaswoj

### PR DESCRIPTION
**Pull request by lucaswoj**
resolves #1641 

cc @lyzidiamond @mtirwin @jfirebaugh

### CODE REVIEW

**Comment by jfirebaugh** [comment]
:+1:

**Comment by lucaswoj** [comment]
Going to get this to re-center the map on the marker, like the old Mapbox.js example, before merging.

**Comment by mtirwin** [comment]
@lucaswoj @jfirebaugh :pray:.

cc/ @geografa

**Comment by lyzidiamond** [comment]
Beautiful! Nice work @lucaswoj.

**Comment by lucaswoj** [comment]
I think I've run into a bug or two while working on map centering. I'll merge this as-is and try to diagnose those separately.

**Pull request merged**
