### PR TITLE
update rest of examples for queryRenderedFeatures

### LINKED ISSUE #2328: Remove layer.interactive from examples
`layer.interactive` is no longer necessary. We should remove it from examples such as https://www.mapbox.com/mapbox-gl-js/example/queryrenderedfeatures/. As a consequence, this example will also no longer need to use `mapboxgl.util.getJSON`; it can instead load the style normally.

### LINKED ISSUE #2329: "Create a draggable point" example isn't working
https://www.mapbox.com/mapbox-gl-js/example/drag-a-point/

When you click and drag the blue circle, the map pans. It should move the point.

### PR DESCRIPTION
**Pull request by ansis**
- remove interactive
- fix draggable point example

fix #2328
fix #2329

:eyes: @lucaswoj or @bhousel

### CODE REVIEW

**Comment by lucaswoj** [comment]
Looks good. 

This needs to be merged into my-pages, not master.

**Comment by mourner** [comment]
Merged to mb-pages.

**Comment by ansis** [comment]
Should this also be merged/cherry-picked into master?

**Comment by lucaswoj** [comment]
> Should this also be merged/cherry-picked into master?

No. We do this during releases.

**Pull request closed without merging**
