### PR TITLE
Made Bucket#add* methods "less magic"

### PR DESCRIPTION
**Pull request by lucaswoj**
Namely, I removed the following behaviors:

 - auto incrementing element group lengths
 - auto subtracting element group vertex start index

This commit brings the buffer benchmark time down from **941 ms** to **752 ms**.

### CODE REVIEW

**Comment by lucaswoj** [comment]
... we can't have nice things because this is :fire: code.

**Comment by lucaswoj** [comment]
Read for :eyes: @jfirebaugh

**Comment by lucaswoj** [comment]
cc @mourner

**Comment by mourner** [comment]
:+1: less magic is good here

**Pull request merged**
