### PR TITLE
Remove source from GeoJsonWorkerSource._geoJSONIndexes when the source is removed from the map, to fix a memory leak

### PR DESCRIPTION
**Pull request by Que3216**
https://github.com/mapbox/mapbox-gl-js/issues/3595

### CODE REVIEW

**Comment by mourner** [comment]
This is great! Can you fix the build and possibly add a test that exercises the new code (removing a GeoJSON source)?

**Comment by Que3216** [comment]
Yep I'll add this now

**Comment by Que3216** [comment]
@mourner I've added a test, let me know what you think.

**Comment by anandthakker** [comment]
> I don't see anything cleaning up this.workerSources[mapId] when a map is removed. Is this another leak?

@jfirebaugh yeah, this is an open leak, although my guess is that this is less urgent than the one addressed in this change, since (at least in my experience) destroying a map is much less common than removing a particular source.  Also, after this fix, the actual size of a lingering WorkerSource is minimal.  (Not that we shouldn't fix it, just pointing out that it probably isn't severe enough to be blocking.)

**Pull request merged**
