### PR TITLE
[docs] Fix typo

### PR DESCRIPTION
**Pull request by karlguillotte**

### CODE REVIEW

**Comment by mollymerp** [comment]
Thanks for your PR @karlguillotte! Our docs are generated from the `mb-pages` branch, so can you please re-target this PR to that branch?

**Comment by lucaswoj** [comment]
I'll merge and cherry-pick. Thanks @karlguillotte & @mollymerp

**Comment by lucaswoj** [comment]
🍒 -picked to `mb-pages` as 4536c2cef9b752f1753094132fcd6f970bef49f2

**Comment by karlguillotte** [comment]
Sorry for the delay! 

Thanks.

**Pull request merged**
