### PR TITLE
Simpler and nicer WorkerTile

### PR DESCRIPTION
**Pull request by mourner**
Cleans up the code, removes leftovers, and makes it slightly faster in theory by filtering out buckets earlier. @jfirebaugh to review.

### CODE REVIEW

**Comment by mourner** [comment]
No idea WTF is going on with the build, it now fails trying to install gdb. @jfirebaugh any ideas? Maybe the Circle VM setup changed?

```bash
The following packages have unmet dependencies:
 gdb : Depends: libpython3.4 (>= 3.4~b1) but it is not going to be installed

sudo apt-get update; sudo apt-get -y install python-pip libglew-dev gdb returned exit code 100
```

**Comment by jfirebaugh** [comment]
Looks like a ubuntu apt repository issue. I reran the build and it's failing for different reason -- removal of `bucket.layers`, which is needed for `featuresAt`.

**Comment by mourner** [comment]
Right, will fix.

**Comment by mourner** [comment]
@jfirebaugh OK ready to go now.

**Comment by jfirebaugh** [comment]
Changes look good, though when I saw the title of this PR I was hoping for a removal of `bucketsBySourceLayer` / `bucket.features` entirely. Did you benchmark anything along the lines of https://github.com/mapbox/mapbox-gl-js/pull/1510#issuecomment-142393988?

**Comment by mourner** [comment]
@jfirebaugh right, I will look into this separately. Trying to keep refactor commits small.

**Pull request merged**
