### PR TITLE
Fix warping when rotating / zooming really fast

### LINKED ISSUE #1818: Rotated rasters don't align
When rotating map with raster layer, tiles don't always align. That leads to gap effects and torn rasters.
It looks like this:

![torn raster1]
(https://www.dropbox.com/s/es253kwee1truu9/IMG_0022.PNG?dl=1)

![torn raster2]
(https://www.dropbox.com/s/jv5m95dxokfsk0n/IMG_0021.PNG?dl=1)

![torn raster3]
(https://www.dropbox.com/s/q2dimjahiv0375s/IMG_0020.PNG?dl=1)

### PR DESCRIPTION
**Pull request by lucaswoj**
... this turned out to be easier than I expected, and then easier than that. 

fixes #1818 

cc @mourner @1ec5 @jfirebaugh

### CODE REVIEW

**Comment by mourner** [comment]
:+1:

**Comment by lucaswoj** [comment]
For the record, this should have no perf impact on non-mobile browsers because https://github.com/mapbox/mapbox-gl-js/blob/1d03d916a28b55f811fc859b01ec5c16ebb69836/js/render/gl_util.js#L25

**Comment by jfirebaugh** [comment]
Was there any reason 335700409b1ee69b592fb73a68894e60f7450a1d didn't apply to all shaders to begin with? Or just an oversight?

**Comment by jfirebaugh** [comment]
Should see if this fixes #1575 or #1285.

**Comment by mourner** [comment]
@jfirebaugh the reason is that bumping to highp apparently also increases memory footprint and may affect performance, so at the time I only bumped attributes that affected the bug, not everything.

**Pull request merged**
