### PR TITLE
Remove GeoJSONSource constructor from docs

### LINKED ISSUE #3050: Clarify documentation to indicate that Source constructors are deprecated
**mapbox-gl-js version**: v0.22.1

### Steps to Trigger Behavior

 1. index.js have code like 
```
var mapboxgl = require('mapbox-gl');
var geojsonsource = new mapboxgl.GeoJSONSource();
```
 2. in index.html  have a javascript link as bundle.js
 3.using webpack to build index.js to bundle.js following [webpack.config.example.js](https://github.com/mapbox/mapbox-gl-js/blob/master/webpack.config.example.js)

### Expected Behavior
no error in devtool console
### Actual Behavior
get an error in devtool console `mapboxgl.GeoJSONSource is not a constructor `

if I include the mapbox-gl.js in index.html directly, there will not be error.

Please give a hint to fix. Thanks.

### PR DESCRIPTION
**Pull request by anandthakker**
Closes #3050

### CODE REVIEW

**Comment by anandthakker** [comment]
> I think we can mark the constructor as private but keep the method public.

@lucaswoj marking the constructor private removes the class from the list;  instead, I used the same approach here as for ImageSource and VideoSource, namely, to document it as an interface rather than a class.

**Comment by lucaswoj** [comment]
> document it as an interface rather than a class.

Perfect 👌 

# Next Steps

 - [ ] find a new home for the cluster parameter documentation
 - [ ] merge this change into `mb-pages`
 - [ ] 🚢

**Comment by anandthakker** [comment]
> find a new home for the cluster parameter documentation

Ah shoot, I forgot that this wasn't part of the style spec.

**Comment by mourner** [comment]
It's a [part of the style spec](https://github.com/mapbox/mapbox-gl-style-spec/blob/5905f13c1db24fbd665fae07d20c991c5ad9eb8e/reference/v8.json#L173-L186), I'm not sure why it's not documented on the site...

**Comment by anandthakker** [comment]
> It's a part of the style spec, I'm not sure why it's not documented on the site...

@mourner heh, well this is funny -- apparently I should have known this: https://github.com/mapbox/mapbox-gl-style-spec/issues/463

**Comment by anandthakker** [comment]
@lucaswoj @mourner seems to me like "find a new home for the cluster parameter documentation" is this upstream issue: https://github.com/mapbox/mapbox-gl-style-spec/issues/463.  Should this PR hold till that issue's resolved?  If so, what are your preferences on how to resolve it?

**Comment by lucaswoj** [comment]
> Should this PR hold till that issue's resolved?

In this case we should hold this PR until https://github.com/mapbox/mapbox-gl-style-spec/issues/463 is resolved. If we merged this PR into `mb-pages` before https://github.com/mapbox/mapbox-gl-style-spec/issues/463, there will be no documentation on the clustering API. 

>  If so, what are your preferences on how to resolve it?

🐟 Let's discuss upstream 🐟

**Comment by anandthakker** [comment]
Upstream blocker is merged

**Comment by lucaswoj** [comment]
Rad! Thanks for the diligence @anandthakker 😄

**Comment by lucaswoj** [comment]
Merged into `mb-pages` as db62cad58665f4554f11fd93a30e09e302fdbf89

**Pull request closed without merging**
