### PR TITLE
add in-place source addition support in addLayer #3857

### PR DESCRIPTION
**Pull request by stepankuzmin**
Hi there, @mourner and @lucaswoj! Is this a correct approach to #3857?

### CODE REVIEW

**Comment by mollymerp** [comment]
Thanks for your contribution @stepankuzmin!! This looks good to me, but I will let @mourner @lucaswoj give it some 👀 before ✅

**Comment by stepankuzmin** [comment]
Another approach is to support `source` as object in `layer`. Would it be more suitable solution?

**Comment by lucaswoj** [comment]
@mourner Just added a commit which clones rather than mutates `layerObject`. Planning to 🚢 on pass.

**Comment by stepankuzmin** [comment]
Great! Thanks!

**Comment by lucaswoj** [comment]
TY @stepankuzmin 😄

**Comment by lucaswoj** [comment]
I've identified a some follow-ups which I'll ticket out separately:

 - add support for this syntax in the validator
 - port this feature to GL native
 - migrate GL JS examples to use this feature when it reduces boilerplate
 - write documentation about this feature
 - write code to deduplicate identical sources internally

**Pull request merged**
