### PR TITLE
Optimize line drawing by avoiding per-tile work

### PR DESCRIPTION
**Pull request by mourner**
This is a slightly messy attempt at winning back some of the performance that regressed with #3342 back, until we solve the challenge of ensuring all tiles are always rendered with the same style.

The idea is to simply check whether the program changed after `useProgram` call, and not do a big portion of the drawing work if it didn't.

On my [3342 benchmark](http://jsfiddle.net/Mourner/2bzyLLp5/4/), results are as follows:

- v0.19: 8.3ms
- v0.25: 17.2ms
- master: 15.3ms (looks like some of your recent changes saved us some ms @jfirebaugh!)
- this PR: ~~12.2ms~~ 11.7ms

👀 @lucaswoj @jfirebaugh

### CODE REVIEW

**Comment by jfirebaugh** [comment]
I'd prefer to follow the optimization that native uses: each program object records the value which was last set for each uniform, and avoids calling `glUniform*` when the value isn't changing. This optimization benefits every layer type as well as the `k === 0` case here (you can reuse the uniform values set by a previous layer, if they're not changing).

**Comment by mourner** [comment]
@jfirebaugh yes, but that sounds like a more involved refactor (#145). Meanwhile this PR is an easy short-term stopgap that we can revert at any time.

**Comment by mourner** [comment]
@jfirebaugh added another commit that removes redundant state changes for pattern/dash-related line drawing code by tracking if the tile zoom changed between tiles. Also cleaned it up a bit. This brings the benchmark result a little further down, from 12.2 to 11.7.

**Comment by mourner** [comment]
`frame-duration` benchmark result isn't as significant because of the averaging I mentioned in #3342, but still noticeable:

benchmark | master | optimize-line-draw
--- | --- | ---
**frame-duration** | 9.6 ms, 5% > 16ms  | 8.9 ms, 1% > 16ms

**Pull request merged**
