### PR TITLE
add icon image setLayoutProperty example

### PR DESCRIPTION
**Pull request by danswick**
We get a lot of questions about markers/icons. This basic example uses `setLayoutProperty` to change a layer's `icon-image` property. 

image

cc: @lyzidiamond

### CODE REVIEW

**Comment by samanpwbb** [comment]
This should look better: can you use a set of images that won't result in the text and icon overlapping?

**Comment by danswick** [comment]
@samanpwbb It probably makes more sense to change the icon for a layer already designed to look good with an icon. How do you feel about this? 

image

**Comment by samanpwbb** [comment]
Is there a way to do this so the example shows a meaningful transition between two states? Can't think of any good examples with default styles that don't also require using setFilter. Would be easy to do this with a custom style, that had a few different POI layers, and 'active' and 'inactive' marker images.

**Comment by danswick** [comment]
@samanpwbb I was thinking the same thing, but thought it might be best to keep it simple, especially since we don't want to use custom styles for examples. 

This does get into fuzzy territory of where examples and API docs diverge (cc @lyzidiamond and @tmcw). Theoretically, someone should be able to figure out how to set a layer's `icon-image` property just by looking at https://www.mapbox.com/mapbox-gl-js/api/#Map.setLayoutProperty, so I'm totally open to your suggestion of filtering markers and setting their icon-image conditionally. 

How about filtering rail stations based on their `network` property? There are lots of places where `rail` and `subway` markers are right next to each other.

**Comment by samanpwbb** [comment]
Go for it – with how complex the mapbox street style is, you might want to switch over to using basic or bright for this.

**Comment by lucaswoj** [comment]
@danswick I'm going to close this as "stale." Feel free to re-open once you address @samanpwbb's feedback.

**Comment by danswick** [comment]
@lucaswoj sounds good. Thanks for putting this one out of its misery. It was becoming more of a filtering example anyway!

**Pull request closed without merging**
