### PR TITLE
feat: add isHighAccurate property to Marker

### LINKED ISSUE #11135: Add isHighAccurate property to Marker
## Motivation
For animating a point the example that Mapbox provided is [animate point along a route](https://docs.mapbox.com/mapbox-gl-js/example/animate-point-along-route/). This convention has bad performance and triggers a repaint map on every update source.  
image
as you can see The CPU is involved throughout the airplane movement.

If we use Marker instead of symbol layer the result is very different, because it works with CSS and doesn't trigger a repaint. 
image
As you can see this convention uses less CPU and memory, but if you check this you can see [Codesandbox link](https://codesandbox.io/s/beautiful-dew-ummh0?file=/index.html) that movement is not smooth and sometimes the marker shakes. This behavior happens because round `marker._pos` property of Marker(maybe for performance) but if we want to implement animation movement, we should have highAccuracy.

### Implementation
We can add `isHighAccuracy` property and check if we want high accurate marker don't round `marker._pos`.

### PR DESCRIPTION
**Pull request by malekeym**
Add `isHighAccurate` property to `Marker`. for disable rounding `marker._pos`
close #11135 
## Launch Checklist

 - [x] briefly describe the changes in this PR
 - [ ] include before/after visuals or gifs if this PR includes visual changes
 - [ ] write tests for all new functionality
 - [ ] document any changes to public APIs
 - [ ] post benchmark scores
 - [ ] manually test the debug page
 - [ ] tagged `@mapbox/map-design-team` `@mapbox/static-apis` if this PR includes style spec API or visual changes
 - [ ] tagged `@mapbox/gl-native` if this PR includes shader changes or needs a native port
 - [ ] apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog'
 - [ ] add an entry inside this element for inclusion in the `mapbox-gl-js` changelog: `<changelog></changelog>`

### CODE REVIEW

**Comment by SnailBones** [comment]
Thanks for the contribution @malekym!

One small piece of feedback so far: I don't think `isHighAccurate` is the most descriptive name for this property. Perhaps `snapToPixel` would give a more clear description of the behavior?

**Comment by SnailBones** [comment]
I _think_ this should close #8614.

**Comment by SnailBones** [comment]
@ryanhamley As @malekeym describes in #11135, the use case is to create smoother animated markers. The current jitter is demonstrated in this [demo](https://github.com/mapbox/mapbox-gl-js/issues/11135).

I wonder if there's a way to fix this problem without expanding the API -  perhaps specifically disabling snapping on recently-moved markers?

**Comment by SnailBones** [comment]
> In line 536, we can adjust it from if (!e || e.type === "moveend") to if (e && e.type === "moveend"). I'm trying to figure out if there's a use case where that would be an issue, but I'm not really coming up with much.

That would disable snapping on `Marker.setLngLat`, which would mean we lose the advantages of snapping in cases where the marker is moved on user interaction ([geocoder](https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-geocoder-accept-coordinates/) and [dragable marker](https://docs.mapbox.com/mapbox-gl-js/example/drag-a-marker/)).

Ideally, I think we want the Marker to snap on discrete position changes or when it finishes moving, but not during ongoing animations. I don't see any easy way to do that automatically without adding an extra `_update()` call.

@malekeym @ryanhamley As an alternative to a class property, what about an optional argument to `Popup.setLngLat()`? I think that would provide the same functionality while avoiding extra update calls and user complexity required by `setSnapToPixel()`.

**Comment by malekeym** [comment]
@SnailBones with merging this #11167 I close this PR, Thank you!

**Pull request closed without merging**
