### PR TITLE
Allow 'sprite' to take stringified JSON of sprite data and image.

### PR DESCRIPTION
**Pull request by dcervelli**

### CODE REVIEW

**Comment by dcervelli** [comment]
This is mostly just for discussion purposes, feel free to decline the PR.

The general idea is that we are programmatically generating sprite sheets for our app and we'd love to get some sort of first class support for setting the sprite sheet without hitting a remote URL.

Thoughts?

**Comment by dcervelli** [comment]
This is our workaround for #2059.

**Comment by mourner** [comment]
Remove the dist commit please — we don't commit build files in the repo.

**Comment by dcervelli** [comment]
@mourner Apologies on the dist, an artifact of the way we are pulling this in. I'll go ahead and close this PR and comment on #2059.

**Pull request closed without merging**
