### PR TITLE
Fix tile cover during globe-to-Mercator transition

### PR DESCRIPTION
**Pull request by SnailBones**
Closes https://github.com/mapbox/gl-js-team/issues/443

Follow up to https://github.com/mapbox/mapbox-gl-js/pull/11988 and https://github.com/mapbox/mapbox-gl-js/pull/12075.

Solves several issues with https://github.com/mapbox/mapbox-gl-js/pull/11988, most critically an issue in `mercatorTileCornersInCameraSpace` where camera position in Mercator now multiplied by `mercatorScale`, now correctly multiplied by`numTiles` .

I've verified that this function is working as intended with the AABB visualization introduced in https://github.com/mapbox/mapbox-gl-js/pull/12131
image

 - [X] briefly describe the changes in this PR
 - [ ] include before/after visuals or gifs if this PR includes visual changes
 - [X] write tests for all new functionality
 - [ ] post benchmark scores
 - [X] manually test the debug page
 - [ ] tagged `@mapbox/map-design-team` `@mapbox/static-apis` if this PR includes style spec API or visual changes
 - [ ] tagged `@mapbox/gl-native` if this PR includes shader changes or needs a native port
 - [X] apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog'
 - [X] add an entry inside this element for inclusion in the `mapbox-gl-js` changelog: `<changelog>Fix occasional missing tiles at bottom of screen during globe-Mercator transition</changelog>`

### CODE REVIEW

**Comment by akoylasar** [comment]
is there a test that validating the fix?

**Comment by SnailBones** [comment]
> is there a test that validating the fix?

Yes, the test [here](https://github.com/mapbox/mapbox-gl-js/blob/abcb5c55591b10baf45e75d403e946348d23054c/test/integration/render-tests/globe/globe-transition/tiles-high-pitch/expected.png) validates the fix. Previously this test was ignored since tiles were missing at the bottom (see https://github.com/mapbox/mapbox-gl-js/pull/11988).

**Comment by avpeery** [comment]
I am seeing the the issue while tile cover at bottom of globe is resolved! However, tile coverage missing during mercator-to-globe transition at the north pole still:
Screen Shot 2022-08-12 at 5 11 59 PM

**Review by avpeery — APPROVED** [review]
LGTM, tested a bunch with the AABB visualizer tool and fixes the issue and adds the render test! Nice word @SnailBones! As mentioned, I noticed a tile coverage issue near poles; however, may not be related to the fix in this PR and can be addressed separately.

**Comment by SnailBones** [comment]
Many thanks for the thorough testing @avpeery! Since https://github.com/mapbox/mapbox-gl-js/issues/12167) is an issue in pole coloring, not tile coverage, I think we're safe to merge in this PR and should address that separately.

**Review by avpeery — APPROVED** [review]
Sounds good @SnailBones !

**Pull request merged**
