### PR TITLE
update bundler quickstart

### PR DESCRIPTION
**Pull request by mollymerp**
to reflect changes in https://github.com/mapbox/mapbox-gl-js/pull/4423
@lucaswoj
## Launch Checklist

 - [ ] briefly describe the changes in this PR
 - [ ] write tests for all new functionality
 - [ ] document any changes to public APIs
 - [ ] post benchmark scores
 - [ ] manually test the debug page

### CODE REVIEW

**Comment by mollymerp** [comment]
It looks like master didn't get merged into `mb-pages` with `0.34.0` – perhaps you didn't successfully push ? @anandthakker

**Comment by lucaswoj** [comment]
> It looks like master didn't get merged into mb-pages with 0.34.0 – perhaps you didn't successfully push ? @anandthakker

Yes -- we should look into this!

**Comment by mollymerp** [comment]
@lucaswoj ooh @anandthakker fixed this yesterday I think!

**Comment by anandthakker** [comment]
Ah yeah I merged master back to mb-pages -- didn't realize that this PR was subsumed by that and thus could be closed.  Thanks @mollymerp

**Pull request closed without merging**
