### PR TITLE
shift horizon towards center to reduce the number of tiles loaded

### PR DESCRIPTION
**Pull request by ansis**
This shifts the horizon down a bit to reduce the number of tiles in highly pitched views. Everything beyond the new horizon is clipped. The skybox is shifted down to meet the horizon.

The horizon is currently shifted 10% of the distance from the true horizon to the center. Specifying the shift as a fraction keeps the horizon at the same real-world locations as pitch changes. The value is not user-configurable right now but we may want to expose it once fog lands. Fog might also make it possible to shift the horizon even further. By blending the map with the sky the sharp edge might be less jarring.

The number of tiles dropped depends on the view. This view loads 20% less tiles:

Screen Shot 2021-01-20 at 11 23 39 AMScreen Shot 2021-01-20 at 11 23 33 AM

The perspective of the map is not affected.

## Launch Checklist

 - [x] briefly describe the changes in this PR
 - [x] include before/after visuals or gifs if this PR includes visual changes
 - [x] write tests for all new functionality
 - [x] document any changes to public APIs
 - [x] post benchmark scores
 - [x] manually test the debug page
 - [x] tagged @mapbox/gl-native if this PR includes shader changes or needs a native port
 - [x] apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog'
 - [x] add an entry inside this element for inclusion in the `mapbox-gl-js` changelog: `<changelog>Shift horizon down slightly to reduce the number of tiles loaded for highly-pitched maps.</changelog>`

### CODE REVIEW

**Review by karimnaaji — COMMENTED** [review]
This looks really good and is very simple and effective. Once we have tests passing this should be good to go. Have you been able to run performance benchmarks on this? We have a fixture on heavily pitched views for 3d.

**Comment by karimnaaji** [comment]
@ansis I updated the 3d fixture and ran this branch against v2.0.0:

Screen Shot 2021-01-22 at 11 26 58 AM

**Review by karimnaaji — APPROVED** [review]
LGTM

**Comment by astojilj** [comment]
@ansis , @karimnaaji 
> The value is not user-configurable right now but we may want to expose it once fog lands
Isn't is already configurable by specifying top padding?

**Pull request merged**
