### PR TITLE
Added mvt-fixtures' real-world integration tests

### PR DESCRIPTION
**Pull request by brunoabinader**
Adds real-world integration tests with data coming from https://github.com/mapbox/mvt-fixtures:
- `real-world/bangkok`
- `real-world/chicago`
- `real-world/nepal`
- `real-world/norway`
- `real-world/sanfrancisco`
- `real-world/uruguay`

Changes were made in the integration test HTTP server:
- Added extra `/node_modules` path mount (for finding .mvt files from the mvt-fixtures node module)
- Resolve `local://` URLs also for source `tiles` field (if used instead of `url`)

The tests' styles are all based in `basic-v9`, with slight changes:
- In all tests, the `mapbox` source `tiles` field is unique for each test (because the .mvt files are stored in separate folders)
- For Bangkok, the fonts were all replaced to `NotoCJK` because these provide the extra glyphs
- For all tests containing terrain, a custom contour layer was added (missing in `basic-v9` style)

### CODE REVIEW

**Comment by brunoabinader** [comment]
Possible improvements include:
- Hillshading layers
- Complex styles (e.g. similar to streets-v9, but openly available)

**Comment by brunoabinader** [comment]
I've run these tests in GL native, and so far only tests that show road labels have failed - see e.g. Bangkok:

| GL JS | GL native | diff |
|--|--|--|
| bangkok-gl-js | bangkok-gl-native | bangkok-diff |

As pointed out by @ChrisLoer, there is a similar issue tracking label positioning diffs in https://github.com/mapbox/mapbox-gl-native/issues/10412

**Comment by brunoabinader** [comment]
@jfirebaugh I ended up using Map's `transformRequest` instead of transforming URLs on the HTTP server - much simpler, and also enabled us to clean up the remaining `../../node_modules` entries.

**Comment by mapsam** [comment]
@brunoabinader just seeing this for the first time - awesome work! Lemme know if you have any issues with mvt-fixtures, happy to help with updates.

**Comment by brunoabinader** [comment]
Thanks @mapsam :)

**Pull request merged**
