### PR TITLE
Add UI controls for pitch

### PR DESCRIPTION
**Pull request by scothis**
Use shift-up-arrow and shift-down-arrow to control the pitch. Clicking on
the rotation button will reset the pitch to 0.

This change exposes pitch for power users, but leaves the current UI
unchanged. More advanced UIs can still be built on top of this behavior.

Issue: #1063

### CODE REVIEW

**Comment by mushon** [comment]
:+1:

**Comment by tmcw** [comment]
This works, but the lack of pitch animation makes it seem a little out-of-place with the other, smoothly transitioned keyboard controls

**Comment by tmcw** [comment]
That said - I think we should merge this first and animate as a separate pass. Animation's a lower-level API change.

**Comment by jfirebaugh** [comment]
You should be able to use `easeTo({pitch: pitch})` to get animated tilt.

**Comment by scothis** [comment]
Updated to easeTo.

**Pull request merged**
