### PR TITLE
add transform clone

### PR DESCRIPTION
**Pull request by vicapow**
Could we add a `clone` method to the transform?

### CODE REVIEW

**Comment by mourner** [comment]
What's that used for?

**Comment by vicapow** [comment]
I'm building a React component that uses Mapbox. I've reimplemented some UI actions (like pan and zoom) because I want the map to be stateless. I also don't want to cause side effects by modifying the map transform directly. Instead, my component emits change events that the owner of the component could choose to ignore.

```js
// Within a React component that wraps mapbox.
_onMouseDrag: function _onMouseDrag(/*...*/) {
  // ...
  var transform = map.transform.clone();
  // `p2` = the new mouse position
   transform.setLocationAtPoint(this.state.startLatLng, p2);
   var bbox = getBBoxFromTransform(transform, width, height);
   this.props.onChangeViewport({
     latitude: transform.center.lat,
     longitude: transform.center.lng,
     zoom: transform.zoom,
     bbox: bbox
  });
}
```

**Comment by jfirebaugh** [comment]
I don't consider `map.transform` a public API and it's not publicly documented -- in fact it should be at `map._transform`. What's the set of functionality you need from it? I'd rather expose that directly.

**Comment by vicapow** [comment]
The end goal is support React rendered overlays that selectively capture events. ie., You have a React component overlay that allows for points to be dragged but if the user scrolls overtop of a draggable item, the map still zooms in as expected. 

To do this, I needed to re-implement some of the handler functionality to use React's [SyntheticEvents](https://facebook.github.io/react/docs/events.html) so things like `e.stopPropagation()` on a synthetic event would prevent it from bubbling up to the parent. For this to work, the parent needs to be capturing `SyntheticEvents`. (In React, native events completely cycle through bubble/capture phases before any `SyntheticEvents` fire.) These re-implemented handlers use the `Transform` class (since the original ones do as well). In addition, I don't want to modifying the original map `transform` directly because the change events could be ignored by the ["owner"](https://facebook.github.io/react/docs/multiple-components.html#ownership) of the component. If that were to happen, the state of the map would be out of sync with the state of the app.

I realize this isn't a typical use case of the `Transform` class so I'm fine with no guarantees the API wont change.

**Comment by mourner** [comment]
Given that it's not a public API, you could just as well hack around that without changing GL-JS source. E.g. `var clone = new map._transform.constructor(...)`.

**Pull request closed without merging**
