### PR TITLE
Support padding positions in fitBounds

### PR DESCRIPTION
**Pull request by tristen**
- ref #995 

cc @jfirebaugh

### CODE REVIEW

**Comment by jfirebaugh** [comment]
For the tests, try to find some bounds and padding values that make an appreciable difference in the result, and then assert equality using `fixedLngLat` (see other tests in the file for example). You could use `fixedLngLat` with the current values, and your tests would probably pass, but they wouldn't really be testing the different between not passing bounds, passing a single number, and passing an array, because the resulting difference is so small (< 0.0000000000001 degree of latitude / longitude).

**Comment by lucaswoj** [comment]
@tristen Do we still want to add this functionality? Is there anything I can do to help you :ship: this?

**Comment by tristen** [comment]
@lucaswoj this functionality would be amazing and I'd love help with it by basically making this commit legit - my change above isn't robust enough to flexibly adjust padding on all four sides.

**Comment by lucaswoj** [comment]
Ok. In an effort to clean out stale PRs, lets close this for now, re-open https://github.com/mapbox/mapbox-gl-js/issues/1339, and resume work when this feature becomes top-of-mind.

**Pull request closed without merging**
