### PR TITLE
Simpler and faster glyph/icon handling

### PR DESCRIPTION
**Pull request by mourner**
Previously, worker would send separate glyph and icon requests for each symbol bucket, spamming worker-UI communication and as a result, slowing down the main thread on tile load, leading to dropped frames and stuttering.

Now the logic is much simpler — we gather icon and glyph dependencies from all symbol buckets first and then do one glyph and one icon request. Thus we avoid spamming too many postMessage requests between the worker and the main thread, and also do less work because many buckets can share the same icons and glyphs (which would be requested multiple times in the previous approach).

In a sample DC to SF flyTo, a profiler shows that glyphs + icons processing goes down from 590ms (master) to 180ms (this PR).

@jfirebaugh to review. also cc @ansis in case there's anything I'm missing about the old approach.

### CODE REVIEW

**Comment by jfirebaugh** [comment]
Does this possibly increase tile parsing latency for individual symbol layers? Suppose there's one symbol layer that needs a single icon, and another symbol layer that needs tons of icons and glyphs, will the first one have to wait for everything, whereas before it could finish quickly?

**Comment by mourner** [comment]
In theory, it can increase the idle time of a particular worker while it loads resources. In practice though, this is unlikely since worker uses the waiting time to process all other buckets, symbol buckets without many resources are usually parsed pretty fast too, and slowdowns are compensated by less postMessage overhead. I can do more precise measurements if you're in doubt.

**Comment by ansis** [comment]
It looks like it parses all non-symbol buckets are [parsed](https://github.com/mapbox/mapbox-gl-js/blob/973d8cdf1e86e9d9b95212fa7ab3457de14ff348/js/source/worker_tile.js#L132-L134) before the icon/glyph requests are initiated. If the requests are initiated first, the data can start loading while the line and fill buckets are parsed.

If I'm reading it correctly, the new code will wait to parse a symbol bucket until all new glyphs are loaded even if that bucket doesn't need any new glyphs. The old implementation requested glyphs separately for each bucket to avoid this waiting.

**I never measured any of this so I don't know if it is significant, but I think it might be.** Symbol bucket parsing takes a significant amount of time, let's say 100ms. If we delay all parsing to wait for a glyph that only one bucket needs it will slow down loading by almost 100ms.

Again, I've never measured this. It could be that the extra complexity and performance overhead isn't worth it.

**Comment by ansis** [comment]
I think merging this and trying to optimize it later with actual benchmarks could be good. I don't want my evidence-less hunches to block cleanup. Your changes make loading much simpler and cleaner!

**Comment by mourner** [comment]
@ansis you're right about parsing non-symbol buckets! I'll move them down.

I'll also try to come up with better benchmark results before merging. The idea is that while this PR may delay parsing in some circumstances (which my hunch says are rare), it's not a big price to pay for less clogged main thread, since this is more noticeable for users. I noticed the original problem when recording "timeline" profiles in devtools for the main thread — you can notice that in many of the longer frames, there are lots of actor-related chunks grouped together (e.g. 70 in a row).

**Comment by mourner** [comment]
Fixed the symbol/other parsing order. About benchmarks — this is pretty hard to measure consistently since timing here depends on a lot of factors, but in my tests, the actual total tile loading time in Mapbox Streets stays about the same.

> the new code will wait to parse a symbol bucket until all new glyphs are loaded even if that bucket doesn't need any new glyphs. The old implementation requested glyphs separately for each bucket to avoid this waiting.

It will still wait often because it also has to wait for the previous buckets in the order to be parsed. Also note that in the old approach, every symbol bucket with icons or text will do a deps request even if previous buckets had all icons/glyphs this bucket needed, because when it figures out deps, the worker doesn't yet have deps responses.

I suggest merging now and optimizing later — perhaps we'll be able to find an approach somewhere in between this one in the old one that reduces idle worker time while not increasing main thread CPU time much.

**Comment by ansis** [comment]
:+1:

**Pull request merged**
