### PR TITLE
Add fill-opacity overlapping test-suite test

### PR DESCRIPTION
**Pull request by lucaswoj**
ref https://github.com/mapbox/mapbox-gl-test-suite/pull/117

### CODE REVIEW

**Comment by lucaswoj** [comment]
Blocked on merging this by some failing test-suite cases that have been added since the last GL JS sync

**Comment by lucaswoj** [comment]
Failing test cases:

 - layout-property-function-to-default
 - layout-property-function-to-literal
 - layout-property-literal-to-default
 - layout-property-literal-to-function
 - paint-property-function-to-default

**Comment by jfirebaugh** [comment]
@lucaswoj Those are tests I added and I belive the failures are indications of bugs in gl-js. Do you want me to file tickets and disable them for now, or are you on the case?

**Comment by lucaswoj** [comment]
Disabling tests doesn't allow test-suite to pass in the case of runtime exceptions (this case). I'm going to make some changes to the test-suite harness and fix these bugs first thing tomorrow.

**Comment by jfirebaugh** [comment]
Disabling with `"js": false` (rather than `"ignored": {...}`) will prevent the test from running entirely.

**Pull request merged**
