### PR TITLE
Remove use of coveredTiles

### PR DESCRIPTION
**Pull request by jfirebaugh**
@ansis Can you check my reasoning in the commit message?

### CODE REVIEW

**Comment by mourner** [comment]
@jfirebaugh I'm confused — the e-mail notification had a pull about your earlier style refactoring, but links to this pull about covered tiles. GitHub bug?

**Comment by jfirebaugh** [comment]
Bug in [`hub pull-request`](https://github.com/github/hub#git-pull-request) -- for some reason it reused a previous pull-request description. Sorry for the confusion.

**Comment by ansis** [comment]
Raster crossfading happens [within a shader](https://github.com/mapbox/mapbox-gl-js/blob/cb28ae6fc0ed52a9ce17993468f56a910458fef7/shaders/raster.fragment.glsl#L17-L21) that gets passed both the parent and child raster textures. I think since the parent is drawn with the child the parent doesn't need to be drawn again separately if it is covered.

For opaque rasters (satellite imagery) it should be ok, but not necessary, to draw the parent separately. 
But for semi-transparent rasters like prerendered/blurred hillshades it breaks crossfading. The parent tile will shine through the child tile. I think the only way to get the right blending is to fade the rasters together in a shader, drawing each fragment only once.

For the current approach to raster crossfading I think `coveringTiles` is necessary.

But the current raster crossfading approach might not be a good idea. For a while it seemed like semitransparent raster layers (included prerendered layers) could be pretty important. If they aren't anymore we could simplify how crossfading works. Or we could just not crossfade semi-transparent layers.

**Comment by jfirebaugh** [comment]
@ansis Thanks, that's super helpful.

**Pull request closed without merging**
