### PR TITLE
Allow disable() mid-drag (#2419)

### PR DESCRIPTION
**Pull request by krabbypattified**
This code allows the user to call dragPan.disable() mid-drag.
This is intended as a fix for touch (mobile) devices.
It enables draggable markers on touch devices.

### CODE REVIEW

**Comment by mollymerp** [comment]
@krabbypattified thanks for your contribution! the tests are failing because of linting errors right now. you can fix this by running `yarn lint --fix` or `npm run lint -- --fix`.

do you have a test case that you used to manually determine if this fix was working? I can investigate adding a unit test to test this fix as well.

**Comment by krabbypattified** [comment]
I've added a test for my code, but since there's [no `simulation.touch` events](https://github.com/mapbox/mapbox-gl-js/blob/master/test/node_modules/mapbox-gl-js-test/simulate_interaction.js), I wasn't able to include touch tests.

I've run `yarn lint --fix` which has come back with no errors. Granted, I did copy/paste from my local Atom files into the GitHub online commit system.

**Comment by krabbypattified** [comment]
Why is Flow doing this to me?
` if (e.touches) return this._onTouchEnd(e);
                                                        ^ MouseEvent. This type is incompatible with the expected param type of
195:     _onTouchEnd(e: TouchEvent)`

**Comment by mollymerp** [comment]
Ooo @krabbypattified sorry for the delay here. What's happening is that since you're not explicitly ensuring that `e` is of type `TouchEvent` before invoking `_onTouchEnd` flow thinks that the `e` passed to `_onTouchEnd` could possibly be of type `MouseEvent.`

I belive you can get rid of this error by changing your condition on L111 from `if (e.touches)` to `if (e instanceof TouchEvent)`

**Comment by jfirebaugh** [comment]
Thanks for the contribution @krabbypattified, and sorry that we weren't more responsive on this PR. It got overtaken by other event-related work, so I've opened an alternative fix for the issue in #6232.

**Pull request closed without merging**
