### PR TITLE
fix marker update with no options

### PR DESCRIPTION
**Pull request by runetvilum**
## Launch Checklist

 - [ ] briefly describe the changes in this PR
 - [ ] write tests for all new functionality
 - [ ] document any changes to public APIs
 - [ ] post benchmark scores
 - [ ] manually test the debug page

### CODE REVIEW

**Comment by jfirebaugh** [comment]
cc @mollymerp -- looks like this fixes `Marker#setLatLng` when the marker is already on the map. Also, the case where `_update` is called via `map.on('move', this._update.bind(this))` works by accident, because `options` is actually an event object without a `roundPos` property. Let's use this as an opportunity to get full code coverage on marker.js.

**Comment by mollymerp** [comment]
Thanks for the fix @runetvilum !

@jfirebaugh yes, I will work on some tests to get coverage up 😳 . 

My original approach used the `event` argument to determine whether to round (`633b986`) :
```js
var pos =  (e && e.type === "move") ? this._map.project(this._lngLat)._add(this._offset) : this._map.project(this._lngLat)._add(this._offset).round();
```

I'm thinking it might make sense to go back to that approach (DRY version) instead of adding an options parameter. 
```js
var pos = this._map.project(this._lngLat)._add(this._offset);
if (!e || e.type==="moveend") pos = pos.round();
```

cc @lucaswoj

**Comment by mollymerp** [comment]
Addressing this in #3294

**Comment by mollymerp** [comment]
Thanks again for contributing @runetvilum -- we decided to change the approach we're using to round the position coordinates and have merged a fix in #3294.

**Pull request closed without merging**
