### PR TITLE
Only shape point placement symbols

### PR DESCRIPTION
**Pull request by malwoodsantoro**
## Launch Checklist

Fixes https://github.com/mapbox/mapbox-gl-js/issues/8575

 - [x] briefly describe the changes in this PR
    - This PR fixes a bug in which newline characters were being ignored if `text-max-width` was set to zero. This was caused by a faulty check in the shaping code which equated "no max width" with "no shaping should occur". This PR fixes the issue and corrects the check by explicitly checking for `line` and `line-center` symbol placement and not shaping those symbols (e.g. only shape text when the symbol is placed as a point).
 - [x] write tests for all new functionality
 - [x] document any changes to public APIs
 - [x] post benchmark scores
 - [x] manually test the debug page
 - [x] tagged `@mapbox/studio` and/or `@mapbox/maps-design` if this PR includes style spec changes
 - [x] tagged `@mapbox/gl-native` if this PR includes shader changes or needs a native port
    - this will need a port to native cc: @mapbox/gl-native 

<changelog>Fix bug in which explicit newline characters were ignored when text-max-width was set to zero</changelog>

### CODE REVIEW

**Comment by ryanhamley** [comment]
This is working really well now. The only failing test is a render test `text-max-width/unlimited` which I believe to be an incorrect test. [The test](https://github.com/mapbox/mapbox-gl-js/tree/master/test/integration/render-tests/text-max-width/unlimited) uses `text-max-width: 0` and equates it with "unlimited" width is wrong. My recommendation is to convert this to an explicit test of `text-max-width: 0` with the expectation that there are line breaks on every possible whitespace character.

**Comment by ryanhamley** [comment]
https://github.com/mapbox/mapbox-gl-js/pull/3725 is the PR that introduced the `if (!maxWidth)` check that is being changed here. I don't really understand why Chris went this particular direction. Making this change seems to be more consistent with the expected behavior and removes a confusing semantic equivalence between 0 max width and effectively infinite max width. I think this change is ok, but I just wanted to note the original PR in case.

**Comment by asheemmamoowala** [comment]
> The only failing test is a render test text-max-width/unlimited which I believe to be an incorrect test.
> Making this change seems to be more consistent with the expected behavior and removes a confusing semantic equivalence between 0 max width and effectively infinite max width. I think this change is ok

@malwoodsantoro @ryanhamley It is unclear how this change affects existing styles that may be depending on this behavior. Maybe someone from @mapbox/map-design-team can comment on whether this change will require style changes for common use cases.

**Comment by ryanhamley** [comment]
@mapbox/map-design-team Does anyone have feedback on this change?

**Comment by ryanhamley** [comment]
Benchmarks look good

Screen Shot 2019-09-17 at 11 48 31 AM
Screen Shot 2019-09-17 at 11 48 40 AM
Screen Shot 2019-09-17 at 11 49 18 AM
Screen Shot 2019-09-17 at 11 49 26 AM

**Comment by ryanhamley** [comment]
*Visual Changes*

This style with `text-max-width: 0` and an explicit newline character in the text:
Screen Shot 2019-09-17 at 11 54 57 AM

Produces this output on `master`. Note that the newline is ignored.
Screen Shot 2019-09-17 at 11 54 23 AM

With this PR, this is the output. Since the text max width is 0, we break on every whitespace character.
Screen Shot 2019-09-17 at 11 53 34 AM

**Pull request merged**
