### PR TITLE
Swipe example

### PR DESCRIPTION
**Pull request by tristen**
swipe-example

cc @jfirebaugh for a review

### CODE REVIEW

**Comment by musicformellons** [comment]
Cool! An additional feature could be to have a moving daylight map!

**Comment by jfirebaugh** [comment]
:+1: This is great! Should we consider making this into a plugin?

**Comment by tristen** [comment]
> Should we consider making this into a plugin?

Hmm yeah! could be a super simple plugin: `map.addControl(new mapboxgl.Compare(mapA, mapB));`

**Comment by tristen** [comment]
https://github.com/mapbox/mapbox-gl-js/commit/495002269a1b0d675f425ada2bc5a5a433090f30

**Comment by pratikyadav** [comment]
I was just searching for this yesterday. Thanks  @tristen  :)

**Pull request closed without merging**
