### PR TITLE
Add WMS example. Fixes #2775

### LINKED ISSUE #2775: Add WMS example
@bhousel love the [new WMS support](https://github.com/mapbox/mapbox-gl-js/pull/2612) and excited to [see the docs roll](https://github.com/mapbox/mapbox-gl-style-spec/pull/464). 

Can you add an example to https://www.mapbox.com/mapbox-gl-js/examples/, maybe porting over https://www.mapbox.com/mapbox.js/example/v1.0.0/wms/?

cc/ @tmcw @lyzidiamond

### PR DESCRIPTION
**Pull request by tmcw**
This adds an example for the new WMS functionality created by @bhousel. cc @lucaswoj for the review

## Checklist

 - [x] briefly describe the changes in this PR
 - [x] write tests for all new functionality
 - [x] [document any changes or additions to public APIs](https://github.com/mapbox/mapbox-gl-js/blob/master/docs/README.md)
 - [x] [post scores for all benchmarks on your branch and `master`](https://github.com/mapbox/mapbox-gl-js/blob/master/bench/README.md#running-benchmarks) (if you made a non-trivial code change)
 - [x] [do a quick sanity check on the debug page](https://github.com/mapbox/mapbox-gl-js/blob/master/CONTRIBUTING.md#serving-the-debug-page)
 - [x] get a PR review :+1: / :-1:

### CODE REVIEW

**Comment by lucaswoj** [comment]
Looking good @tmcw! 

screen shot 2016-08-10 at 4 16 09 pm

I'm going to make one minor change, modifying the example title to match the part-of-speech precedent set by the other example titles.

**Comment by lucaswoj** [comment]
Rebased to incorporate 74883fe4bab2b9f435d1bde1cd5ae0d16474eb76 and hopefully make  CI pass

**Comment by tmcw** [comment]
Ah, crap, I realized too late that this source is http, not https... looks like it's SSL valid though

**Comment by bhousel** [comment]
Thanks @tmcw!

**Pull request merged**
