### PR TITLE
Validate container option

### LINKED ISSUE #5619: Need to check if container option is provided
Recently I am reviewing the source code. As I know, the `options.container` must be provided as string or HTMLElement. I think bellow code would fail to validate `container` if it is `undefined` or other types.

https://github.com/mapbox/mapbox-gl-js/blob/master/src/ui/map.js#L280-L289

```
        if (typeof options.container === 'string') {
            const container = window.document.getElementById(options.container);
            if (!container) {
                throw new Error(`Container '${options.container}' not found.`);
            } else {
                this._container = container;
            }
        } else {
            this._container = options.container;
        }
```

### PR DESCRIPTION
**Pull request by jingsam**
fix #5619

## Launch Checklist

 - [ ] briefly describe the changes in this PR
 - [ ] write tests for all new functionality
 - [ ] document any changes to public APIs
 - [ ] post benchmark scores
 - [ ] manually test the debug page

### CODE REVIEW

**Comment by jingsam** [comment]
Ops, seems need to expose HTMLElement in `util/window.js`

**Comment by jfirebaugh** [comment]
Thanks @jingsam. Can you resolve the CI failure?

**Comment by jingsam** [comment]
I need to export `HTMLElement` in util/window.js, but I have not figure out how to do it.

**Comment by jfirebaugh** [comment]
Add `HTMLElement: typeof HTMLElement ` here:

https://github.com/mapbox/mapbox-gl-js/blob/3a8ef5bcf825bcdcb0b32d3152170a03bd1099cd/flow-typed/window.js#L117

**Comment by jingsam** [comment]
Use #5695 instead

**Pull request closed without merging**
